import { SeedCategory } from '../seed'

export const newCategories: SeedCategory[] = [
  // ===================== DOMAIN 9: TEORÍAS CONSPIRATIVAS =====================
  {
    id: 'cat-conspiracy',
    name_es: 'Teorías Conspirativas',
    name_en: 'Conspiracy Theories',
    slug: 'conspiracy',
    description_es: 'Teorías que explican eventos significativos como resultado de complots secretos orquestados por grupos poderosos.',
    description_en: 'Theories explaining significant events as the result of secret plots orchestrated by powerful groups.',
    icon: '🕵️',
    parentId: 'cat-mysteries',
  },
  {
    id: 'cat-conspiracy-political',
    name_es: 'Conspiraciones Políticas',
    name_en: 'Political Conspiracies',
    slug: 'political-conspiracies',
    description_es: 'Teorías sobre complots políticos, gobiernos secretos y manipulación del poder a escala global.',
    description_en: 'Theories about political plots, shadow governments, and manipulation of power on a global scale.',
    icon: '🏛️',
    parentId: 'cat-conspiracy',
  },
  {
    id: 'cat-conspiracy-historical',
    name_es: 'Conspiraciones Históricas',
    name_en: 'Historical Conspiracies',
    slug: 'historical-conspiracies',
    description_es: 'Teorías que reinterpretan eventos históricos como encubrimientos o engaños deliberados.',
    description_en: 'Theories that reinterpret historical events as deliberate cover-ups or hoaxes.',
    icon: '📜',
    parentId: 'cat-conspiracy',
  },
  {
    id: 'cat-conspiracy-tech',
    name_es: 'Conspiraciones Tecnológicas',
    name_en: 'Technological Conspiracies',
    slug: 'technological-conspiracies',
    description_es: 'Teorías sobre tecnologías ocultas, control social mediante dispositivos y agendas tecnológicas secretas.',
    description_en: 'Theories about hidden technologies, social control through devices, and secret technological agendas.',
    icon: '💻',
    parentId: 'cat-conspiracy',
  },
  {
    id: 'cat-conspiracy-bio',
    name_es: 'Conspiraciones Biológicas',
    name_en: 'Biological Conspiracies',
    slug: 'biological-conspiracies',
    description_es: 'Teorías sobre manipulación genética, pandemias fabricadas y control de la población mediante agentes biológicos.',
    description_en: 'Theories about genetic manipulation, manufactured pandemics, and population control through biological agents.',
    icon: '🧬',
    parentId: 'cat-conspiracy',
  },

  // ===================== DOMAIN 10: PERSONAJES HISTÓRICOS Y LEGENDARIOS =====================
  {
    id: 'cat-historical-figures',
    name_es: 'Personajes Históricos y Legendarios',
    name_en: 'Historical and Legendary Figures',
    slug: 'historical-figures',
    description_es: 'Figuras que moldearon la historia y la leyenda: gobernantes, científicos, exploradores, artistas y héroes míticos.',
    description_en: 'Figures who shaped history and legend: rulers, scientists, explorers, artists, and mythical heroes.',
    icon: '👑',
    parentId: 'cat-history',
  },
  {
    id: 'cat-figures-rulers',
    name_es: 'Líderes y Gobernantes',
    name_en: 'Leaders and Rulers',
    slug: 'leaders-rulers',
    description_es: 'Emperadores, reyes, reinas y líderes que ejercieron el poder y transformaron sociedades enteras.',
    description_en: 'Emperors, kings, queens, and leaders who wielded power and transformed entire societies.',
    icon: '👑',
    parentId: 'cat-historical-figures',
  },
  {
    id: 'cat-figures-scientists',
    name_es: 'Científicos e Inventores',
    name_en: 'Scientists and Inventors',
    slug: 'scientists-inventors',
    description_es: 'Mentes brillantes que revolucionaron la ciencia, la tecnología y nuestra comprensión del mundo.',
    description_en: 'Brilliant minds who revolutionized science, technology, and our understanding of the world.',
    icon: '🔬',
    parentId: 'cat-historical-figures',
  },
  {
    id: 'cat-figures-explorers',
    name_es: 'Exploradores',
    name_en: 'Explorers',
    slug: 'explorers',
    description_es: 'Aventureros que cartografiaron lo desconocido, cruzaron océanos y descubrieron nuevos mundos.',
    description_en: 'Adventurers who mapped the unknown, crossed oceans, and discovered new worlds.',
    icon: '🌍',
    parentId: 'cat-historical-figures',
  },
  {
    id: 'cat-figures-artists',
    name_es: 'Artistas',
    name_en: 'Artists',
    slug: 'artists',
    description_es: 'Creadores cuya obra transformó la estética, la cultura y la forma en que percibimos la realidad.',
    description_en: 'Creators whose work transformed aesthetics, culture, and the way we perceive reality.',
    icon: '🎨',
    parentId: 'cat-historical-figures',
  },
  {
    id: 'cat-figures-legendary',
    name_es: 'Figuras Legendarias',
    name_en: 'Legendary Figures',
    slug: 'legendary-figures',
    description_es: 'Héroes semidivinos, figuras épicas y personajes legendarios cuyo estatus histórico es incierto.',
    description_en: 'Semidivine heroes, epic figures, and legendary characters whose historical status is uncertain.',
    icon: '⚔️',
    parentId: 'cat-historical-figures',
  },

  // ===================== DOMAIN 11: COSMOLOGÍA Y ORÍGENES =====================
  {
    id: 'cat-cosmology',
    name_es: 'Cosmología y Orígenes',
    name_en: 'Cosmology and Origins',
    slug: 'cosmology-origins',
    description_es: 'Estudio del origen y evolución del cosmos, la vida y el ser humano desde perspectivas científicas y filosóficas.',
    description_en: 'Study of the origin and evolution of the cosmos, life, and human beings from scientific and philosophical perspectives.',
    icon: '🌌',
    parentId: 'cat-science',
  },
  {
    id: 'cat-cosmology-universe',
    name_es: 'Origen del Universo',
    name_en: 'Origin of the Universe',
    slug: 'origin-universe',
    description_es: 'Teorías y modelos que explican cómo surgió el universo, desde el Big Bang hasta la cosmología moderna.',
    description_en: 'Theories and models explaining how the universe emerged, from the Big Bang to modern cosmology.',
    icon: '🌌',
    parentId: 'cat-cosmology',
  },
  {
    id: 'cat-cosmology-life',
    name_es: 'Origen de la Vida',
    name_en: 'Origin of Life',
    slug: 'origin-life',
    description_es: 'Hipótesis científicas sobre cómo surgió la vida a partir de materia inerte en la Tierra primitiva.',
    description_en: 'Scientific hypotheses about how life emerged from non-living matter on early Earth.',
    icon: '🧬',
    parentId: 'cat-cosmology',
  },
  {
    id: 'cat-cosmology-human',
    name_es: 'Origen del Ser Humano',
    name_en: 'Origin of Humankind',
    slug: 'origin-humankind',
    description_es: 'Teorías sobre la evolución humana, nuestros ancestros y el desarrollo de las civilizaciones.',
    description_en: 'Theories about human evolution, our ancestors, and the development of civilizations.',
    icon: '🧑',
    parentId: 'cat-cosmology',
  },

  // ===================== DOMAIN 12: CIENCIA (subcategorías) =====================
  {
    id: 'cat-physics',
    name_es: 'Física',
    name_en: 'Physics',
    slug: 'physics',
    description_es: 'Estudio de la materia, la energía, el espacio y el tiempo, y las leyes fundamentales que rigen el universo.',
    description_en: 'Study of matter, energy, space, and time, and the fundamental laws governing the universe.',
    icon: '⚛️',
    parentId: 'cat-science',
  },
  {
    id: 'cat-chemistry',
    name_es: 'Química',
    name_en: 'Chemistry',
    slug: 'chemistry',
    description_es: 'Estudio de la composición, estructura, propiedades y transformaciones de la materia.',
    description_en: 'Study of the composition, structure, properties, and transformations of matter.',
    icon: '🧪',
    parentId: 'cat-science',
  },
  {
    id: 'cat-mathematics',
    name_es: 'Matemáticas',
    name_en: 'Mathematics',
    slug: 'mathematics',
    description_es: 'Estudio de patrones, estructuras, cantidades y relaciones abstractas mediante el razonamiento lógico.',
    description_en: 'Study of patterns, structures, quantities, and abstract relationships through logical reasoning.',
    icon: '📐',
    parentId: 'cat-science',
  },
]
