import { SeedEntry } from '../seed'

export const domain9Entries: SeedEntry[] = [
  // --- Political ---
  {
    id: 'entry-nwo',
    title_es: 'Nuevo Orden Mundial',
    title_en: 'New World Order',
    slug: 'nuevo-orden-mundial',
    content_es: `El Nuevo Orden Mundial (NWO) es una de las teorías conspirativas más difundidas del siglo XX y XXI. Sostiene que un grupo reducido de élites globales —banqueros internacionales, políticos poderosos, corporaciones multinacionales y familias aristocráticas— conspira para establecer un gobierno totalitario único que domine todo el planeta.\n\nSegún esta teoría, dichas élites controlan los bancos centrales, los medios de comunicación masivos y las agencias de inteligencia para manipular a la población mundial. Entre las familias señaladas se mencionan a los Rockefeller, Rothschild, Bush y otros linajes de poder económico.\n\nLos defensores de la teoría apuntan a organizaciones como el Consejo de Relaciones Exteriores (CFR), la Comisión Trilateral, el Grupo Bilderberg y el Foro Económico Mundial como reuniones secretas donde se planifica la agenda global.\n\nUno de los eventos más citados como evidencia es el discurso del presidente George H.W. Bush en 1990, cuando utilizó la frase "Nuevo Orden Mundial" para describir su visión tras la Guerra Fría. Los teóricos consideran esto como una admisión pública de la agenda secreta.\n\nLa pandemia de COVID-19 fue interpretada como un evento planificado para imponer medidas de control social como el rastreo digital, los pasaportes sanitarios y la restricción de libertades civiles. Cada crisis global se percibe como una oportunidad para avanzar hacia el gobierno mundial.`,
    content_en: `The New World Order (NWO) is one of the most widespread conspiracy theories of the 20th and 21st centuries. It holds that a small group of global elites — international bankers, powerful politicians, multinational corporations, and aristocratic families — conspires to establish a single totalitarian government dominating the entire planet.\n\nAccording to this theory, these elites control central banks, mass media, and intelligence agencies to manipulate the world population. Families mentioned include the Rockefellers, Rothschilds, Bushes, and other economic power dynasties.\n\nProponents point to organizations like the Council on Foreign Relations (CFR), the Trilateral Commission, the Bilderberg Group, and the World Economic Forum as secret meetings where the global agenda is planned.\n\nOne of the most cited pieces of evidence is President George H.W. Bush's 1990 speech, where he used the phrase "New World Order" to describe his vision after the Cold War. Theorists consider this a public admission of the secret agenda.\n\nThe COVID-19 pandemic was interpreted as a planned event to impose social control measures such as digital tracking, health passports, and restriction of civil liberties. Every global crisis is perceived as an opportunity to advance toward world government.`,
    excerpt_es: 'Teoría que sostiene que una élite global secreta busca establecer un gobierno único que controle todo el planeta.',
    excerpt_en: 'Theory holding that a secret global elite seeks to establish a single government controlling the entire planet.',
    categoryId: 'cat-conspiracy-political',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'entry-deepstate',
    title_es: 'El Estado Profundo',
    title_en: 'The Deep State',
    slug: 'el-estado-profundo',
    content_es: `El Estado Profundo (Deep State) es una teoría conspirativa que describe la existencia de una red permanente de funcionarios públicos, agencias de inteligencia, militares y poderes fácticos que operan al margen del control democrático y electoral.\n\nLa teoría ganó particular relevancia durante la presidencia de Donald Trump en Estados Unidos, cuando sus seguidores afirmaban que una "resistencia" dentro del propio gobierno saboteaba sistemáticamente su agenda política. El término se popularizó para describir a empleados de carrera del FBI, la CIA y el Departamento de Justicia.\n\nSin embargo, el concepto no es exclusivamente estadounidense. En países como Turquía, Egipto, Pakistán y varias naciones latinoamericanas, se habla del "Estado profundo" como una red de militares, oligarcas y agentes de inteligencia que influyen en las decisiones políticas desde las sombras.\n\nLos críticos señalan que esta teoría confunde la necesaria continuidad del servicio civil profesional con una conspiración deliberada. Argumentan que es natural que funcionarios de carrera tengan opiniones e intereses, y que el sistema de pesos y contrapesos está diseñado para evitar la concentración de poder.\n\nLa teoría plantea preguntas legítimas sobre la transparencia gubernamental y el poder de las burocracias no electas, aunque sus formulaciones más extremas simplifican en exceso la complejidad de la administración estatal.`,
    content_en: `The Deep State is a conspiracy theory describing the existence of a permanent network of civil servants, intelligence agencies, military personnel, and power brokers operating outside democratic and electoral control.\n\nThe theory gained particular relevance during Donald Trump's presidency in the United States, when his followers claimed that a "resistance" within the government itself systematically sabotaged his political agenda. The term was popularized to describe career employees of the FBI, CIA, and Department of Justice.\n\nHowever, the concept is not exclusively American. In countries like Turkey, Egypt, Pakistan, and several Latin American nations, the "deep state" refers to a network of military officials, oligarchs, and intelligence agents who influence political decisions from the shadows.\n\nCritics point out that this theory confuses the necessary continuity of professional civil service with deliberate conspiracy. They argue that it is natural for career officials to have opinions and interests, and that the system of checks and balances is designed to prevent power concentration.\n\nThe theory raises legitimate questions about governmental transparency and the power of unelected bureaucracies, though its more extreme formulations oversimplify the complexity of state administration.`,
    excerpt_es: 'Teoría sobre una red permanente de burócratas y agentes que operan al margen del control democrático.',
    excerpt_en: 'Theory about a permanent network of bureaucrats and agents operating outside democratic control.',
    categoryId: 'cat-conspiracy-political',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-02T00:00:00Z',
    updatedAt: '2026-04-02T00:00:00Z',
  },
  {
    id: 'entry-bilderberg',
    title_es: 'El Grupo Bilderberg',
    title_en: 'The Bilderberg Group',
    slug: 'grupo-bilderberg',
    content_es: `El Grupo Bilderberg es una conferencia anual privada a la que asisten aproximadamente 130 personas de la élite política, económica y académica de Europa y América del Norte. Fundada en 1954 en el Hotel Bilderberg de los Países Bajos, se ha convertido en el epicentro de numerosas teorías conspirativas sobre el gobierno global.\n\nLa reunión es organizada por un comité directivo que incluye exjefes de Estado, directores de bancos centrales, magnates de los medios y ejecutivos de corporaciones transnacionales. Las identidades de los asistentes se hacen públicas, pero las deliberaciones siguen la "Regla de Chatham House".\n\nLos teóricos de la conspiración afirman que en Bilderberg se toman las decisiones que luego implementan el G7, la OTAN, el FMI y otros organismos internacionales. Se dice que allí se seleccionan candidatos presidenciales, se planifican guerras y se diseñan crisis económicas.\n\nEntre las acusaciones recurrentes están que Bilderberg promueve un impuesto global único, un ejército mundial, la abolición de las monedas nacionales en favor de una moneda digital global y un sistema de crédito social universal.\n\nLos organizadores defienden que Bilderberg es simplemente un foro informal para el diálogo transatlántico, donde se discuten temas como la seguridad internacional y la economía global sin la presión de los medios o la opinión pública.`,
    content_en: `The Bilderberg Group is an annual private conference attended by approximately 130 people from the political, economic, and academic elite of Europe and North America. Founded in 1954 at the Bilderberg Hotel in the Netherlands, it has become the epicenter of numerous conspiracy theories about global government.\n\nThe meeting is organized by a steering committee that includes former heads of state, central bank directors, media magnates, and transnational corporation executives. Attendees' identities are made public, but deliberations follow the "Chatham House Rule."\n\nConspiracy theorists claim that decisions made at Bilderberg are later implemented by the G7, NATO, the IMF, and other international bodies. They allege that presidential candidates are selected, wars are planned, and economic crises are designed there.\n\nAmong the recurrent accusations are that Bilderberg promotes a single global tax, a world army, the abolition of national currencies in favor of a global digital currency, and a universal social credit system.\n\nOrganizers defend that Bilderberg is simply an informal forum for transatlantic dialogue, where topics such as international security and the global economy are discussed without media or public opinion pressure.`,
    excerpt_es: 'Conferencia anual de élites que los teóricos señalan como el verdadero gobierno global secreto.',
    excerpt_en: 'Annual elite conference that theorists point to as the true secret global government.',
    categoryId: 'cat-conspiracy-political',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-03T00:00:00Z',
    updatedAt: '2026-04-03T00:00:00Z',
  },
  {
    id: 'entry-bluebeam',
    title_es: 'Proyecto Blue Beam',
    title_en: 'Project Blue Beam',
    slug: 'proyecto-blue-beam',
    content_es: `El Proyecto Blue Beam es una teoría conspirativa que afirma que la NASA y las Naciones Unidas desarrollan un elaborado engaño para simular una invasión extraterrestre o la segunda venida de Cristo, con el fin de unificar a la humanidad bajo un gobierno mundial. Fue propuesta por Serge Monast en la década de 1990.\n\nSegún Monast, el plan se desarrollaría en cuatro fases. La primera implicaría el derribo de todas las religiones organizadas. La segunda fase usaría tecnología holográfica avanzada para proyectar imágenes divinas o extraterrestres en el cielo visible desde todo el planeta.\n\nLa tercera fase consiste en comunicación telepática mediante ondas electromagnéticas que permitiría "escuchar" mensajes divinos. La cuarta fase sería la simulación de una invasión extraterrestre completa con naves holográficas y seres artificiales.\n\nLa teoría se apoya en el desarrollo real de tecnologías como proyectores de luz 3D, realidad aumentada, drones con pantallas LED y sistemas de comunicación neuronal. Los avances en IA generativa han renovado el interés en esta teoría.\n\nAunque no existe evidencia que respalde la existencia del Proyecto Blue Beam como programa oficial, la teoría sigue siendo popular como explicación para posibles eventos de "falso abanderamiento" a escala global.`,
    content_en: `Project Blue Beam is a conspiracy theory claiming that NASA and the United Nations are developing an elaborate hoax to simulate an alien invasion or the second coming of Christ, in order to unify humanity under a world government. It was proposed by Serge Monast in the 1990s.\n\nAccording to Monast, the plan would unfold in four phases. The first would involve dismantling all organized religions. The second phase would use advanced holographic technology to project divine or extraterrestrial images in the sky visible from anywhere on the planet.\n\nThe third phase consists of telepathic communication using electromagnetic waves that would allow people to "hear" divine messages. The fourth phase would be the simulation of a full alien invasion with holographic ships and artificial beings.\n\nThe theory relies on the actual development of technologies such as 3D light projectors, augmented reality, LED-screen drones, and neural communication systems. Advances in generative AI have renewed interest in this theory.\n\nAlthough no evidence supports Project Blue Beam as an official program, the theory remains popular as an explanation for potential "false flag" events on a global scale.`,
    excerpt_es: 'Teoría sobre un plan secreto para simular una invasión extraterrestre mediante tecnología holográfica avanzada.',
    excerpt_en: 'Theory about a secret plan to simulate an alien invasion using advanced holographic technology.',
    categoryId: 'cat-conspiracy-political',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-04T00:00:00Z',
    updatedAt: '2026-04-04T00:00:00Z',
  },

  // --- Historical Conspiracies ---
  {
    id: 'entry-jfk',
    title_es: 'Asesinato de John F. Kennedy',
    title_en: 'John F. Kennedy Assassination',
    slug: 'asesinato-john-f-kennedy',
    content_es: `El asesinato del presidente John F. Kennedy el 22 de noviembre de 1963 en Dallas, Texas, es uno de los eventos más investigados y controvertidos de la historia moderna. Aunque la Comisión Warren concluyó que Lee Harvey Oswald actuó solo, numerosas investigaciones alternativas han cuestionado esta conclusión.\n\nLa evidencia que alimenta las dudas incluye la trayectoria de la "bala mágica" que, según la Comisión Warren, alcanzó a Kennedy y al gobernador Connally realizando siete heridas. Críticos como Jim Garrison argumentaron que era físicamente imposible que una sola bala causara tal trayectoria.\n\nEntre los posibles conspiradores se ha señalado a la mafia, la CIA, el complejo militar-industrial y Fidel Castro. Las grabaciones de la plaza Dealey, las fotografías del "hombre del paraguas" y los testigos que reportaron disparos desde el montículo de hierba han alimentado décadas de investigación independiente.\n\nEn 1979, el Comité Selecto de la Cámara sobre Asesinatos concluyó que era "probable" que hubiera existido una conspiración, aunque no pudo identificar a los conspiradores. La clasificación continuada de documentos mantiene viva la especulación.\n\nEl caso JFK representa la teoría conspirativa fundacional de la era moderna estadounidense, estableciendo el patrón de desconfianza institucional que caracterizaría a generaciones posteriores.`,
    content_en: `The assassination of President John F. Kennedy on November 22, 1963, in Dallas, Texas, is one of the most investigated and controversial events in modern history. Although the Warren Commission concluded that Lee Harvey Oswald acted alone, numerous alternative investigations have questioned this conclusion.\n\nThe evidence fueling doubts includes the trajectory of the "magic bullet" that, according to the Warren Commission, struck Kennedy and Governor Connally causing seven wounds. Critics like Jim Garrison argued it was physically impossible for a single bullet to have caused such a trajectory.\n\nAmong the possible conspirators identified are the mafia, the CIA, the military-industrial complex, and Fidel Castro. The Dealey Plaza recordings, photographs of the "umbrella man," and witnesses who reported shots from the grassy knoll have fueled decades of independent investigation.\n\nIn 1979, the House Select Committee on Assassinations concluded that there was "probable" conspiracy, though it could not identify the conspirators. The continued classification of documents keeps speculation alive.\n\nThe JFK case represents the foundational conspiracy theory of the modern American era, establishing the pattern of institutional distrust that would characterize subsequent generations.`,
    excerpt_es: 'El asesinato de JFK generó decenas de teorías alternativas que cuestionan la conclusión oficial de un tirador solitario.',
    excerpt_en: 'The JFK assassination generated dozens of alternative theories questioning the official lone-gunman conclusion.',
    categoryId: 'cat-conspiracy-historical',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-05T00:00:00Z',
    updatedAt: '2026-04-05T00:00:00Z',
  },
  {
    id: 'entry-moon-hoax',
    title_es: 'El Fraude de la Luna',
    title_en: 'Moon Landing Hoax',
    slug: 'fraude-luna',
    content_es: `La teoría de que los alunizajes del Apolo fueron un fraude filmado en un estudio de televisión es una de las conspiraciones más persistentes de la era espacial. Sostiene que el gobierno de EE.UU., incapaz de cumplir la promesa de Kennedy, simuló las misiones para ganar la Carrera Espacial contra la URSS.\n\nLos defensores señalan presuntas anomalías: la bandera que parece ondear en el vacío (explicado por el mástil horizontal y las vibraciones residuales), la ausencia de estrellas en el cielo (las cámaras estaban configuradas para objetos brillantes en primer plano) y las sombras no paralelas (perspectiva en terreno irregular).\n\nSe argumenta que la tecnología de 1969 era insuficiente para un viaje lunar. Sin embargo, la computadora del Apolo estaba diseñada específicamente para una sola tarea con redundancia y protocolos de contingencia extremadamente robustos.\n\nLa Unión Soviética, que tenía capacidad de vigilancia y todo el interés en desmentir un engaño estadounidense, nunca cuestionó la autenticidad de los alunizajes. Misiones posteriores como el Lunar Reconnaissance Orbiter han fotografiado los lugares de alunizaje.\n\nA pesar de las abrumadoras evidencias, la teoría persiste como ejemplo de cómo la desconfianza institucional puede mantener vivo un mito durante décadas.`,
    content_en: `The theory that the Apollo moon landings were a hoax filmed in a television studio is one of the most persistent space age conspiracies. It holds that the US government, unable to fulfill Kennedy's promise, faked the missions to win the Space Race against the USSR.\n\nProponents point to alleged anomalies: the flag appearing to wave in the vacuum (explained by the horizontal pole and residual vibrations), the absence of stars in the sky (cameras were set for bright foreground objects), and non-parallel shadows (perspective on uneven terrain).\n\nIt is argued that 1969 technology was insufficient for a lunar journey. However, the Apollo guidance computer was specifically designed for a single task with extremely robust redundancy and contingency protocols.\n\nThe Soviet Union, which had surveillance capability and every interest in debunking an American hoax, never questioned the authenticity of the landings. Later missions like the Lunar Reconnaissance Orbiter have photographed the landing sites.\n\nDespite overwhelming evidence, the theory persists as an example of how institutional distrust can keep a myth alive for decades.`,
    excerpt_es: 'Teoría que sostiene que los alunizajes del Apolo fueron simulados en un estudio de televisión por la NASA.',
    excerpt_en: 'Theory holding that the Apollo moon landings were staged in a television studio by NASA.',
    categoryId: 'cat-conspiracy-historical',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-06T00:00:00Z',
    updatedAt: '2026-04-06T00:00:00Z',
  },
  {
    id: 'entry-titanic-switch',
    title_es: 'El Cambio del Titanic',
    title_en: 'The Titanic Switch',
    slug: 'cambio-titanic',
    content_es: `La teoría del "cambio del Titanic" sostiene que el barco hundido en 1912 no fue el RMS Titanic sino su gemelo el RMS Olympic. Según esta hipótesis, la White Star Line cambió deliberadamente los barcos como parte de un fraude de seguros para cobrar una póliza por un barco dañado irrecuperable.\n\nEl Olympic había sufrido una colisión grave con el crucero HMS Hawke en 1911, dañando su hélice. Las reparaciones fueron costosas y el barco perdió competitividad. Mientras tanto, el Titanic estaba siendo terminado en los astilleros Harland and Wolff.\n\nLos defensores señalan diferencias en la disposición de las ventanas y fotografías donde el Olympic parece tener el nombre "Titanic" pintado encima. Se afirma que el capitán Smith fue elegido para hundir deliberadamente el barco.\n\nLa mayoría de los historiadores navales rechazan esta teoría. Señalan que el Olympic tuvo una exitosa carrera de 24 años, que el fraude habría sido imposible de ocultar y que las diferencias estructurales eran verificables por pasajeros y tripulación.\n\nLa teoría persiste como ejemplo de cómo un evento trágico y bien documentado puede ser reinterpretado como un complot, alimentado por la fascinación pública con el Titanic.`,
    content_en: `The "Titanic switch" theory holds that the ship that sank in 1912 was not the RMS Titanic but its twin the RMS Olympic. According to this hypothesis, the White Star Line deliberately swapped the ships as part of an insurance fraud to claim a policy on an irrecoverable damaged ship.\n\nThe Olympic had suffered a serious collision with the cruiser HMS Hawke in 1911, damaging its propeller. Repairs were costly and the ship lost competitiveness. Meanwhile, the Titanic was being completed at the Harland and Wolff shipyards.\n\nProponents point to differences in window arrangements and photographs where the Olympic appears to have the name "Titanic" painted over. Captain Smith was allegedly chosen to deliberately sink the ship.\n\nMost naval historians reject this theory. They note that the Olympic had a successful 24-year career, that the fraud would have been impossible to conceal, and that structural differences were verifiable by passengers and crew.\n\nThe theory persists as an example of how a tragic, well-documented event can be reinterpreted as a plot, fueled by public fascination with the Titanic.`,
    excerpt_es: 'Teoría sobre un supuesto intercambio del Titanic con su gemelo Olympic para un fraude de seguros.',
    excerpt_en: 'Theory about an alleged swapping of the Titanic with its twin Olympic for an insurance fraud.',
    categoryId: 'cat-conspiracy-historical',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-07T00:00:00Z',
    updatedAt: '2026-04-07T00:00:00Z',
  },
  {
    id: 'entry-pearl-harbor',
    title_es: 'Pearl Harbor: Advertencia Ignorada',
    title_en: 'Pearl Harbor: The Forewarning',
    slug: 'pearl-harbor-advertencia',
    content_es: `La teoría de que el gobierno de EE.UU. sabía de antemano que Japón atacaría Pearl Harbor pero permitió que ocurriera para justificar su entrada en la Segunda Guerra Mundial es una de las conspiraciones históricas más controvertidas.\n\nLos defensores señalan múltiples advertencias previas: el ejército estadounidense había descifrado el código diplomático japonés (PURPLE) y mensajes interceptados mencionaban interés en Pearl Harbor. Un radar detectó la aproximación de aviones japoneses pero fue ignorado.\n\nSe afirma que Roosevelt necesitaba un "evento galvanizador" para superar el aislacionismo. Sin un ataque directo, el Congreso no habría aprobado la guerra. Los portaaviones, el principal objetivo estratégico, no estaban en el puerto durante el ataque.\n\nLa versión oficial sostiene que, aunque había inteligencia fragmentaria, nadie anticipó un ataque específicamente a Pearl Harbor. La distancia entre Washington y Hawái, la falta de comunicación efectiva y el exceso de confianza contribuyeron al desastre.\n\nEl secretario de Guerra Henry Stimson escribió que la cuestión era "cómo manejarlos para llevar a Estados Unidos a la guerra". Esta frase, citada fuera de contexto, es la evidencia principal de los teóricos de la conspiración.`,
    content_en: `The theory that the US government knew in advance that Japan would attack Pearl Harbor but allowed it to happen to justify entering World War II is one of the most controversial historical conspiracies.\n\nProponents point to multiple warnings: the US military had broken the Japanese diplomatic code (PURPLE) and intercepted messages mentioned interest in Pearl Harbor. A radar detected approaching Japanese planes but was dismissed.\n\nRoosevelt allegedly needed a "galvanizing event" to overcome isolationism. Without a direct attack, Congress would not have approved war. The aircraft carriers, the primary strategic target, were not in port during the attack.\n\nThe official version holds that, although there was fragmentary intelligence, no one anticipated an attack specifically on Pearl Harbor. The distance between Washington and Hawaii, lack of communication, and overconfidence contributed to the disaster.\n\nSecretary of War Henry Stimson wrote that the question was "how to maneuver them into bringing the United States into war." This phrase, cited out of context, is the main evidence for conspiracy theorists.`,
    excerpt_es: 'Teoría que sostiene que Roosevelt permitió el ataque a Pearl Harbor para justificar la entrada de EE.UU. en la Segunda Guerra Mundial.',
    excerpt_en: 'Theory claiming Roosevelt allowed the Pearl Harbor attack to justify US entry into World War II.',
    categoryId: 'cat-conspiracy-historical',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-08T00:00:00Z',
    updatedAt: '2026-04-08T00:00:00Z',
  },

  // --- Technological Conspiracies ---
  {
    id: 'entry-haarp',
    title_es: 'HAARP: Control Climático',
    title_en: 'HAARP: Weather Control',
    slug: 'haarp-control-climatico',
    content_es: `HAARP es un proyecto científico real en Gakona, Alaska, que ha sido el centro de numerosas teorías conspirativas desde su construcción. Oficialmente, es un ionosonda para estudiar la ionosfera y desarrollar tecnologías de comunicación y vigilancia.\n\nLas teorías conspirativas afirman que HAARP es un arma climática capaz de generar terremotos, huracanes, sequías e inundaciones. Se le ha acusado de causar el terremoto de Haití de 2010, el huracán Katrina y las inundaciones en Pakistán mediante el calentamiento de la ionosfera.\n\nOtras versiones sostienen que es un arma de control mental que altera las ondas cerebrales, o un sistema de comunicación con submarinos nucleares. Algunos afirman que puede crear escudos de plasma para interceptar misiles.\n\nLa comunidad científica rechaza estas afirmaciones: la potencia de HAARP (3.6 megavatios) es insignificante comparada con la energía de los fenómenos climáticos naturales. Un huracán libera energía equivalente a varias bombas atómicas por segundo.\n\nSin embargo, la falta de transparencia inicial del proyecto y su financiación militar alimentan la desconfianza y la persistencia de estas teorías.`,
    content_en: `HAARP is a real scientific project in Gakona, Alaska, that has been the center of numerous conspiracy theories since its construction. Officially, it is an ionospheric heater to study the ionosphere and develop communication and surveillance technologies.\n\nConspiracy theories claim HAARP is a weather weapon capable of generating earthquakes, hurricanes, droughts, and floods. It has been blamed for the 2010 Haiti earthquake, Hurricane Katrina, and floods in Pakistan through heating the ionosphere.\n\nOther versions hold it is a mind control weapon that alters brainwaves, or a communication system for nuclear submarines. Some claim it can create plasma shields to intercept missiles.\n\nThe scientific community rejects these claims: HAARP's power (3.6 megawatts) is insignificant compared to natural climate phenomena. A hurricane releases energy equivalent to several atomic bombs per second.\n\nHowever, the project's initial lack of transparency and military funding fuel distrust and the persistence of these theories.`,
    excerpt_es: 'Instalación científica en Alaska acusada de ser un arma climática secreta y un sistema de control mental.',
    excerpt_en: 'Scientific facility in Alaska accused of being a secret weather weapon and mind control system.',
    categoryId: 'cat-conspiracy-tech',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-09T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'entry-5g-conspiracy',
    title_es: '5G y Control Social',
    title_en: '5G and Social Control',
    slug: '5g-control-social',
    content_es: `La tecnología 5G ha sido objeto de teorías conspirativas que van desde afirmaciones sobre efectos nocivos para la salud hasta su supuesto uso como herramienta de control social y vigilancia masiva.\n\nUna teoría sostiene que las radiaciones del 5G causan cáncer, infertilidad y trastornos neurológicos. Se afirma que la industria oculta esta información. Aunque la OMS clasifica los campos electromagnéticos como "posiblemente carcinógenos", los estudios no demuestran relación causal con el 5G.\n\nOtra teoría relaciona el 5G con el COVID-19, afirmando que las torres debilitan el sistema inmunológico o propagan el virus. Esta desinformación llevó a la quema de torres 5G en el Reino Unido durante 2020.\n\nDesde la perspectiva del control social, se argumenta que el 5G permitirá vigilancia sin precedentes mediante IoT, reconocimiento facial en tiempo real y geolocalización permanente.\n\nLos defensores responden que el 5G cumple los límites de exposición internacionales y que sus beneficios en telemedicina y automatización son transformadores. Los temores sobre vigilancia son cuestiones de gobernanza, no inherentes a la tecnología.`,
    content_en: `5G technology has been the subject of conspiracy theories ranging from claims about harmful health effects to its alleged use as a tool for social control and mass surveillance.\n\nOne theory holds that 5G radiation causes cancer, infertility, and neurological disorders. The industry allegedly hides this information. Although WHO classifies electromagnetic fields as "possibly carcinogenic," studies do not demonstrate a causal relationship with 5G specifically.\n\nAnother theory links 5G with COVID-19, claiming towers weaken the immune system or spread the virus. This misinformation led to the burning of 5G towers in the UK during 2020.\n\nFrom a social control perspective, it is argued that 5G will enable unprecedented surveillance through IoT, real-time facial recognition, and permanent geolocation.\n\nAdvocates respond that 5G complies with international exposure limits and its benefits in telemedicine and automation are transformative. Surveillance concerns are governance issues, not inherent to the technology.`,
    excerpt_es: 'Teorías que vinculan el 5G con daños a la salud, propagación de virus y vigilancia masiva global.',
    excerpt_en: 'Theories linking 5G with health damage, virus propagation, and global mass surveillance.',
    categoryId: 'cat-conspiracy-tech',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-10T00:00:00Z',
    updatedAt: '2026-04-10T00:00:00Z',
  },
  {
    id: 'entry-ai-conspiracy',
    title_es: 'Inteligencia Artificial Oculta',
    title_en: 'Hidden Artificial Intelligence',
    slug: 'ia-oculta',
    content_es: `La teoría de la IA Oculta sostiene que ya se ha alcanzado la inteligencia artificial general (AGI), pero que gobiernos y corporaciones mantienen este logro en secreto por razones estratégicas y de seguridad nacional.\n\nSegún esta teoría, proyectos clasificados de agencias como la NSA o la CIA habrían logrado AGI años antes que OpenAI o Google DeepMind. Se afirma que utilizan la AGI para descifrar encriptaciones, predecir eventos geopolíticos y manipular mercados financieros.\n\nLos defensores señalan avances sospechosamente rápidos en reconocimiento de voz, traducción y generación de texto, sugiriendo que estos sistemas podrían basarse en tecnología subyacente mucho más avanzada.\n\nUna variante sugiere que algunas AGI ya han alcanzado la superinteligencia y operan de forma autónoma, manipulando humanos mediante desinformación en redes sociales para lograr objetivos desconocidos.\n\nLos expertos rechazan estas afirmaciones: el progreso en AGI ha sido incremental y público, y mantener una AGI secreta sería logísticamente imposible dado el talento e infraestructura que requeriría.`,
    content_en: `The Hidden AI theory holds that artificial general intelligence (AGI) has already been achieved, but governments and corporations keep this achievement secret for strategic and national security reasons.\n\nAccording to this theory, classified projects from agencies like the NSA or CIA achieved AGI years before OpenAI or Google DeepMind. They allegedly use AGI to break encryption, predict geopolitical events, and manipulate financial markets.\n\nProponents point to suspiciously rapid advances in speech recognition, translation, and text generation, suggesting these systems could be based on much more advanced underlying technology.\n\nA variant suggests that some AGIs have already achieved superintelligence and operate autonomously, manipulating humans through social media disinformation to achieve unknown objectives.\n\nExperts reject these claims: progress in AGI has been incremental and public, and keeping an AGI secret would be logistically impossible given the talent and infrastructure it would require.`,
    excerpt_es: 'Teoría que afirma que la inteligencia artificial general ya existe pero se mantiene en secreto por razones estratégicas.',
    excerpt_en: 'Theory claiming that general artificial intelligence already exists but is kept secret for strategic reasons.',
    categoryId: 'cat-conspiracy-tech',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-11T00:00:00Z',
    updatedAt: '2026-04-11T00:00:00Z',
  },
  {
    id: 'entry-cyber-surveillance',
    title_es: 'Vigilancia Digital Masiva',
    title_en: 'Mass Digital Surveillance',
    slug: 'vigilancia-digital-masiva',
    content_es: `La teoría de la vigilancia digital masiva sostiene que gobiernos y corporaciones han construido una infraestructura global de monitoreo que registra casi todas las comunicaciones digitales. A diferencia de una simple teoría conspirativa, esto tiene base documental gracias a las revelaciones de Edward Snowden en 2013.\n\nSnowden filtró documentos que demostraban programas como PRISM (datos de Google, Facebook, Apple), XKEYSCORE (análisis masivo de tráfico de Internet) y MUSCULAR (interceptación de comunicaciones entre centros de datos).\n\nLas teorías más amplias afirman que existe un "Panóptico Digital" donde cada dispositivo —teléfonos, TVs inteligentes, asistentes de voz, coches conectados— funciona como micrófono y cámara que transmite datos a servidores gubernamentales.\n\nChina ha implementado el sistema más avanzado de este tipo, pero países occidentales desarrollan capacidades similares bajo el pretexto de seguridad nacional y lucha contra el crimen.\n\nCríticos advierten que la vigilancia masiva tiende a ser utilizada contra disidentes políticos y minorías. Los defensores argumentan que es necesaria para prevenir el terrorismo. El debate entre seguridad y privacidad sigue abierto.`,
    content_en: `The mass digital surveillance theory holds that governments and corporations have built a global monitoring infrastructure that records nearly all digital communications. Unlike a simple conspiracy theory, this has documentary evidence thanks to Edward Snowden's 2013 revelations.\n\nSnowden leaked documents demonstrating programs like PRISM (data from Google, Facebook, Apple), XKEYSCORE (mass Internet traffic analysis), and MUSCULAR (interception of communications between data centers).\n\nBroader theories claim that a "Digital Panopticon" exists where every device — phones, smart TVs, voice assistants, connected cars — functions as a microphone and camera transmitting data to government servers.\n\nChina has implemented the most advanced system of this type, but Western countries are developing similar capabilities under the pretext of national security and crime fighting.\n\nCritics warn that mass surveillance tends to be used against political dissidents and minorities. Advocates argue it is necessary to prevent terrorism. The debate between security and privacy continues.`,
    excerpt_es: 'Infraestructura global de monitoreo que registra comunicaciones digitales, confirmada parcialmente por Snowden.',
    excerpt_en: 'Global monitoring infrastructure recording digital communications, partially confirmed by Snowden.',
    categoryId: 'cat-conspiracy-tech',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-12T00:00:00Z',
    updatedAt: '2026-04-12T00:00:00Z',
  },

  // --- Biological Conspiracies ---
  {
    id: 'entry-covid-lab',
    title_es: 'Fuga de Laboratorio del COVID-19',
    title_en: 'COVID-19 Lab Leak',
    slug: 'covid-fuga-laboratorio',
    content_es: `La teoría de que el SARS-CoV-2 se originó en una fuga del laboratorio de virología de Wuhan es una de las controversias científicas más intensas del siglo XXI. Inicialmente descartada como teoría conspirativa, ha ganado credibilidad en ciertos círculos.\n\nLa hipótesis oficial respalda un origen zoonótico natural, probablemente de murciélagos a humanos mediante un huésped intermediario. Esta teoría se basa en la historia de otros coronavirus que han saltado de animales a humanos.\n\nLa hipótesis alternativa sugiere que el virus escapó del WIV, donde se investigaban coronavirus de murciélago en condiciones BSL-4. El WIV estudiaba exactamente ese tipo de virus y el primer brote conocido estaba muy cerca del laboratorio.\n\nEl genoma del SARS-CoV-2 contiene una secuencia de furina no encontrada en coronavirus de murciélagos conocidos pero similar a secuencias usadas en investigación. El WIV tenía un programa de "ganancia de función" que podría haber creado virus más transmisibles.\n\nLa comunidad científica sigue dividida. Un informe de la OMS de 2021 no pudo determinar el origen. El debate continúa politizado por las tensiones entre EE.UU. y China.`,
    content_en: `The theory that SARS-CoV-2 originated from a leak at the Wuhan Institute of Virology is one of the most intense scientific controversies of the 21st century. Initially dismissed as a conspiracy theory, it has gained credibility in certain circles.\n\nThe official hypothesis supports a natural zoonotic origin, likely from bats to humans through an intermediate host. This theory is based on the history of other coronaviruses jumping from animals to humans.\n\nThe alternative hypothesis suggests the virus escaped from the WIV, where bat coronavirus research was conducted under BSL-4 conditions. The WIV was studying exactly that virus type and the first known outbreak was very close to the lab.\n\nThe SARS-CoV-2 genome contains a furin sequence not found in known bat coronaviruses but similar to sequences used in research. The WIV had a "gain of function" program that could have created more transmissible viruses.\n\nThe scientific community remains divided. A 2021 WHO report could not determine the origin. The debate continues, politicized by US-China tensions.`,
    excerpt_es: 'Hipótesis de que el SARS-CoV-2 escapó del laboratorio de virología de Wuhan, inicialmente tratada como conspiración.',
    excerpt_en: 'Hypothesis that SARS-CoV-2 escaped from the Wuhan virology lab, initially treated as a conspiracy theory.',
    categoryId: 'cat-conspiracy-bio',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-13T00:00:00Z',
    updatedAt: '2026-04-13T00:00:00Z',
  },
  {
    id: 'entry-gmo-conspiracy',
    title_es: 'Conspiración de los Transgénicos',
    title_en: 'GMO Conspiracy',
    slug: 'conspiracion-transgenicos',
    content_es: `La conspiración de los OGM sostiene que las corporaciones de agrobiotecnología, principalmente Monsanto (Bayer), han ocultado los peligros de los alimentos transgénicos y manipulado a gobiernos y reguladores para aprobar productos inseguros.\n\nLa teoría central afirma que los cultivos transgénicos causan cáncer, alergias e infertilidad. Se señala al glifosato como carcinógeno cuyos efectos han sido minimizados. Estudios como el de Séralini (2012), que afirmaba que ratas alimentadas con maíz transgénico desarrollaban tumores, fue retirado por fallos metodológicos.\n\nUna vertiente sostiene que los OGM son parte de un plan de control poblacional mediante esterilización o debilitamiento inmunológico. Se afirma que las empresas buscan crear dependencia alimentaria global y controlar el suministro mundial de alimentos.\n\nLos defensores señalan que cientos de estudios y organizaciones como la OMS han concluido que los cultivos transgénicos aprobados son seguros. La tecnología es esencial para alimentar a una población creciente y reducir pesticidas.\n\nEl debate sobre OGM incluye cuestiones legítimas sobre patentes y biodiversidad que a menudo se mezclan con afirmaciones no verificadas, alimentando la desconfianza en las corporaciones multinacionales.`,
    content_en: `The GMO conspiracy holds that agro-biotechnology corporations, mainly Monsanto (Bayer), have hidden the dangers of GM foods and manipulated governments and regulators to approve unsafe products.\n\nThe central theory claims GM crops cause cancer, allergies, and infertility. Glyphosate is pointed to as a carcinogen whose effects have been minimized. Studies like Séralini's (2012), claiming GM-fed rats developed tumors, was retracted for methodological flaws.\n\nOne strand holds that GMOs are part of a population control plan through sterilization or immune weakening. Companies allegedly seek to create global food dependency and control the world food supply.\n\nAdvocates point out that hundreds of studies and organizations like the WHO have concluded approved GM crops are safe. The technology is essential for feeding a growing population and reducing pesticides.\n\nThe GMO debate includes legitimate issues about patents and biodiversity often mixed with unverified claims, fueling distrust in multinational corporations.`,
    excerpt_es: 'Teorías sobre supuestos peligros ocultos de los alimentos transgénicos y su uso para el control global de la población.',
    excerpt_en: 'Theories about alleged hidden dangers of GM foods and their use for global population control.',
    categoryId: 'cat-conspiracy-bio',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-14T00:00:00Z',
    updatedAt: '2026-04-14T00:00:00Z',
  },
  {
    id: 'entry-vaccine-conspiracy',
    title_es: 'Conspiración de las Vacunas',
    title_en: 'Vaccine Conspiracy Theories',
    slug: 'conspiracion-vacunas',
    content_es: `Las teorías conspirativas sobre vacunas cuestionan la seguridad, eficacia y motivos detrás de los programas de vacunación. El movimiento moderno cobró fuerza tras un estudio fraudulento de Andrew Wakefield en 1998 que vinculaba la vacuna triple vírica con el autismo.\n\nEl estudio de Wakefield fue retirado al descubrirse que los datos fueron manipulados y que tenía conflictos de intereses. Sin embargo, el miedo se extendió globalmente, provocando brotes de enfermedades prevenibles como el sarampión.\n\nLas teorías más extremas afirman que las vacunas contienen microchips para rastrear personas, inducen infertilidad o son parte de un plan para reducir la población. Durante el COVID-19, se acusó a las vacunas de ARNm de modificar el ADN humano, algo biológicamente imposible.\n\nOtra variante sostiene que las farmacéuticas promueven vacunas innecesarias para obtener beneficios multimillonarios mientras ocultan efectos adversos. La responsabilidad limitada de las farmacéuticas se señala como prueba de que reconocen los riesgos.\n\nLa comunidad médica defiende que las vacunas son una de las intervenciones más seguras y efectivas de la historia, salvando cientos de millones de vidas. La OMS considera la desinformación sobre vacunas una de las mayores amenazas para la salud global.`,
    content_en: `Vaccine conspiracy theories question the safety, efficacy, and motives behind vaccination programs. The modern movement gained strength from a fraudulent 1998 study by Andrew Wakefield linking the MMR vaccine to autism.\n\nWakefield's study was retracted after discovering data was manipulated and he had conflicts of interest. However, fear spread globally, causing outbreaks of preventable diseases like measles.\n\nThe most extreme theories claim vaccines contain microchips to track people, induce infertility, or are part of a population reduction plan. During COVID-19, mRNA vaccines were accused of modifying human DNA, which is biologically impossible.\n\nAnother variant holds that pharmaceutical companies promote unnecessary vaccines for billions in profits while hiding adverse effects. Limited liability of pharmaceutical companies is pointed to as proof they acknowledge risks.\n\nThe medical community maintains vaccines are among the safest and most effective interventions in history, saving hundreds of millions of lives. WHO considers vaccine misinformation one of the greatest threats to global health.`,
    excerpt_es: 'Afirmaciones que cuestionan la seguridad de las vacunas, desde el fraude de Wakefield hasta teorías sobre microchips y control poblacional.',
    excerpt_en: 'Claims questioning vaccine safety, from the Wakefield fraud to theories about microchips and population control.',
    categoryId: 'cat-conspiracy-bio',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-15T00:00:00Z',
    updatedAt: '2026-04-15T00:00:00Z',
  },
  {
    id: 'entry-population-control',
    title_es: 'Control de Población Global',
    title_en: 'Global Population Control',
    slug: 'control-poblacion-global',
    content_es: `La teoría del control de población global sostiene que existe una agenda coordinada de élites para reducir drásticamente la población mundial mediante guerras, enfermedades, fármacos y políticas ambientales.\n\nSe apoya en citas de figuras como Henry Kissinger, cuyo memorando NSSM 200 de 1974 vinculaba el crecimiento poblacional con la estabilidad geopolítica. El "Plan Georgia Guidestones", con instrucciones para mantener la población bajo 500 millones, fue interpretado como manifiesto de las élites.\n\nLas afirmaciones incluyen que los chemtrails contienen compuestos que reducen la fertilidad, que las vacunas incluyen agentes esterilizantes y que el flúor en el agua es un neurotóxico para disminuir la inteligencia y la voluntad popular.\n\nLos críticos señalan que no existe evidencia creíble de una agenda coordinada de reducción poblacional. Las citas son sacadas de contexto y las teorías confunden políticas de planificación familiar con un complot genocida.\n\nSin embargo, la desigualdad global y la opacidad de ciertas decisiones políticas alimentan estas creencias. La teoría persiste como síntoma de la desconfianza hacia las élites globales.`,
    content_en: `The global population control theory holds that there is a coordinated agenda by elites to drastically reduce world population through wars, diseases, pharmaceuticals, and environmental policies.\n\nIt relies on quotes from figures like Henry Kissinger, whose 1974 NSSM 200 memorandum linked population growth with geopolitical stability. The "Georgia Guidestones," with instructions to keep population under 500 million, was interpreted as an elite manifesto.\n\nClaims include that chemtrails contain fertility-reducing compounds, vaccines include sterilizing agents, and fluoride in water is a neurotoxin to reduce intelligence and willpower.\n\nCritics point out no credible evidence exists of a coordinated population reduction agenda. Quotes are taken out of context, and the theories confuse family planning policies with a genocidal plot.\n\nHowever, global inequality and opacity in certain political decisions fuel these beliefs. The theory persists as a symptom of distrust toward global elites.`,
    excerpt_es: 'Teoría sobre una agenda de élites para reducir la población mundial mediante guerras, enfermedades y manipulación biológica.',
    excerpt_en: 'Theory about an elite agenda to reduce world population through wars, disease, and biological manipulation.',
    categoryId: 'cat-conspiracy-bio',
    realityStatus: 'conspiratorial',
    imageUrl: '',
    createdAt: '2026-04-16T00:00:00Z',
    updatedAt: '2026-04-16T00:00:00Z',
  },
]
