import { SeedEntry } from '../seed'

export const entries200Pt2: SeedEntry[] = [
  {
    id: 'entry-200-46',
    title_es: 'Budismo Zen',
    title_en: 'Zen Buddhism',
    slug: 'budismo-zen',
    content_es: `El Budismo Zen es una escuela del budismo Mahayana que se originó en China como Chan y se desarrolló en Japón. Enfatiza la meditación directa (zazen), la experiencia intuitiva de la iluminación (satori) y la transmisión de mente a mente más allá de las escrituras.\n\nLos koans, paradojas aparentemente absurdas como "¿cuál es el sonido de una sola mano aplaudiendo?", son utilizados por los maestros Zen para romper el pensamiento lógico y precipitar el despertar espiritual. El Zen ha influido profundamente en las artes japonesas como la ceremonia del té, la caligrafía, la jardinería y el tiro con arco.`,
    content_en: `Zen Buddhism is a school of Mahayana Buddhism that originated in China as Chan and developed in Japan. It emphasizes direct meditation (zazen), the intuitive experience of enlightenment (satori), and mind-to-mind transmission beyond scriptures.\n\nKoans, seemingly absurd paradoxes like "what is the sound of one hand clapping?", are used by Zen masters to break logical thinking and precipitate spiritual awakening. Zen has profoundly influenced Japanese arts such as the tea ceremony, calligraphy, gardening, and archery.`,
    excerpt_es: 'Escuela budista que enfatiza la meditación directa y la experiencia intuitiva de la iluminación espiritual.',
    excerpt_en: 'Buddhist school emphasizing direct meditation and the intuitive experience of spiritual enlightenment.',
    categoryId: 'cat-eastern-philosophy',
    realityStatus: 'philosophical',
    imageUrl: '',
    createdAt: '2026-06-16T00:00:00Z',
    updatedAt: '2026-06-16T00:00:00Z',
  },
  {
    id: 'entry-200-47',
    title_es: 'Sintoísmo',
    title_en: 'Shinto',
    slug: 'sintoismo',
    content_es: `El Sintoísmo es la religión indígena de Japón, centrada en la veneración de los kami, espíritus divinos que habitan en elementos naturales como montañas, ríos, árboles y fenómenos atmosféricos. Carece de un fundador, escrituras sagradas o doctrina sistemática.\n\nLos rituales sintoístas buscan mantener la pureza y la armonía con los kami, e incluyen ofrendas, oraciones, danzas sagradas (kagura) y festivales estacionales (matsuri). Los santuarios sintoístas, caracterizados por sus torii, son espacios sagrados donde lo divino y lo humano se encuentran.`,
    content_en: `Shinto is the indigenous religion of Japan, centered on the veneration of kami, divine spirits that inhabit natural elements such as mountains, rivers, trees, and atmospheric phenomena. It has no founder, sacred scriptures, or systematic doctrine.\n\nShinto rituals seek to maintain purity and harmony with the kami, and include offerings, prayers, sacred dances (kagura), and seasonal festivals (matsuri). Shinto shrines, characterized by their torii gates, are sacred spaces where the divine and human meet.`,
    excerpt_es: 'Religión indígena japonesa basada en la veneración de los kami, espíritus divinos de la naturaleza.',
    excerpt_en: 'Japanese indigenous religion based on the veneration of kami, divine spirits of nature.',
    categoryId: 'cat-eastern-philosophy',
    realityStatus: 'philosophical',
    imageUrl: '',
    createdAt: '2026-06-17T00:00:00Z',
    updatedAt: '2026-06-17T00:00:00Z',
  },
  {
    id: 'entry-200-48',
    title_es: 'Sijismo',
    title_en: 'Sikhism',
    slug: 'sijismo',
    content_es: `El Sijismo es una religión monoteísta fundada en el siglo XV por Guru Nanak en la región de Punjab, en el sur de Asia. Enseña la existencia de un solo Dios, la igualdad de todos los seres humanos y la importancia de la meditación en el nombre divino.\n\nLa Khalsa, la comunidad de iniciados, sigue los Cinco K: kesh (cabello sin cortar), kangha (peine), kara (pulsera de acero), kachera (pantalón corto ceremonial) y kirpan (espada ceremonial). El Templo Dorado en Amritsar es el centro espiritual más sagrado del Sijismo.`,
    content_en: `Sikhism is a monotheistic religion founded in the 15th century by Guru Nanak in the Punjab region of South Asia. It teaches the existence of one God, the equality of all human beings, and the importance of meditating on the divine name.\n\nThe Khalsa, the community of initiated Sikhs, follows the Five Ks: kesh (uncut hair), kangha (comb), kara (steel bracelet), kachera (ceremonial shorts), and kirpan (ceremonial sword). The Golden Temple in Amritsar is the holiest spiritual center of Sikhism.`,
    excerpt_es: 'Religión monoteísta fundada por Guru Nanak que enfatiza la igualdad y la meditación divina.',
    excerpt_en: 'Monotheistic religion founded by Guru Nanak emphasizing equality and divine meditation.',
    categoryId: 'cat-eastern-philosophy',
    realityStatus: 'philosophical',
    imageUrl: '',
    createdAt: '2026-06-18T00:00:00Z',
    updatedAt: '2026-06-18T00:00:00Z',
  },
  {
    id: 'entry-200-49',
    title_es: 'Jainismo',
    title_en: 'Jainism',
    slug: 'jainismo',
    content_es: `El Jainismo es una antigua religión india que enfatiza la no violencia absoluta (ahimsa), el ascetismo y la liberación del ciclo de reencarnaciones. Su enseñanza principal es que todos los seres vivos poseen un alma eterna y deben ser tratados con respeto.\n\nMahavira, el vigésimo cuarto Tirthankara, es considerado el fundador histórico del Jainismo moderno. Los monjes jainistas practican un ascetismo extremo, incluyendo el celibato, la pobreza total y, en algunos casos, el ayuno hasta la muerte como forma de purificación espiritual.`,
    content_en: `Jainism is an ancient Indian religion that emphasizes absolute non-violence (ahimsa), asceticism, and liberation from the cycle of reincarnation. Its core teaching is that all living beings possess an eternal soul and must be treated with respect.\n\nMahavira, the twenty-fourth Tirthankara, is considered the historical founder of modern Jainism. Jain monks practice extreme asceticism, including celibacy, total poverty, and in some cases, fasting unto death as a form of spiritual purification.`,
    excerpt_es: 'Antigua religión india basada en la no violencia absoluta y el ascetismo como camino de liberación.',
    excerpt_en: 'Ancient Indian religion based on absolute non-violence and asceticism as the path to liberation.',
    categoryId: 'cat-eastern-philosophy',
    realityStatus: 'philosophical',
    imageUrl: '',
    createdAt: '2026-06-19T00:00:00Z',
    updatedAt: '2026-06-19T00:00:00Z',
  },
  {
    id: 'entry-200-50',
    title_es: 'Tales de Mileto',
    title_en: 'Thales of Miletus',
    slug: 'tales-de-mileto',
    content_es: `Tales de Mileto, considerado el primer filósofo griego, propuso que el agua era el arjé, el principio fundamental del cual se origina toda la realidad. Su enfoque naturalista marcó el nacimiento de la filosofía occidental al buscar explicaciones racionales del cosmos.\n\nSegún la tradición, Tales predijo un eclipse solar en el año 585 a.C. y demostró que la naturaleza seguía leyes comprensibles por la razón humana. También contribuyó a las matemáticas con el teorema de Tales, estableciendo la proporcionalidad en triángulos semejantes.`,
    content_en: `Thales of Miletus, considered the first Greek philosopher, proposed that water was the arche, the fundamental principle from which all reality originates. His naturalistic approach marked the birth of Western philosophy by seeking rational explanations of the cosmos.\n\nAccording to tradition, Thales predicted a solar eclipse in 585 BC and demonstrated that nature follows laws understandable by human reason. He also contributed to mathematics with Thales' theorem, establishing proportionality in similar triangles.`,
    excerpt_es: 'Primer filósofo griego que propuso el agua como principio fundamental de toda la realidad.',
    excerpt_en: 'First Greek philosopher who proposed water as the fundamental principle of all reality.',
    categoryId: 'cat-ancient-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-20T00:00:00Z',
    updatedAt: '2026-06-20T00:00:00Z',
  },
  {
    id: 'entry-200-51',
    title_es: 'Pitágoras',
    title_en: 'Pythagoras',
    slug: 'pitagoras',
    content_es: `Pitágoras de Samos fue un filósofo y matemático griego que fundó una comunidad religioso-filosófica en el sur de Italia. Creía en la transmigración de las almas y veía en los números la estructura fundamental de la realidad.\n\nEl teorema de Pitágoras, que establece la relación entre los lados de un triángulo rectángulo, es uno de los descubrimientos matemáticos más conocidos de la historia. La escuela pitagórica combinó matemáticas, música, astronomía y misticismo en una cosmovisión donde el universo entero se entendía como armonía numérica.`,
    content_en: `Pythagoras of Samos was a Greek philosopher and mathematician who founded a religious-philosophical community in southern Italy. He believed in the transmigration of souls and saw numbers as the fundamental structure of reality.\n\nThe Pythagorean theorem, which establishes the relationship between the sides of a right triangle, is one of the most famous mathematical discoveries in history. The Pythagorean school combined mathematics, music, astronomy, and mysticism into a worldview where the entire universe was understood as numerical harmony.`,
    excerpt_es: 'Filósofo y matemático que fundó una escuela místico-matemática y descubrió el famoso teorema.',
    excerpt_en: 'Philosopher and mathematician who founded a mystical-mathematical school and discovered the famous theorem.',
    categoryId: 'cat-ancient-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-21T00:00:00Z',
    updatedAt: '2026-06-21T00:00:00Z',
  },
  {
    id: 'entry-200-52',
    title_es: 'Heráclito',
    title_en: 'Heraclitus',
    slug: 'heraclito',
    content_es: `Heráclito de Éfeso, conocido como el "filósofo del devenir", afirmó que el cambio constante es la esencia del universo. Su famosa máxima "no puedes bañarte dos veces en el mismo río" expresa su visión de que todo fluye y nada permanece.\n\nPara Heráclito, el logos es la ley universal que gobierna el flujo del cambio, una razón divina que mantiene la armonía a través de la oposición de contrarios. Consideraba el fuego como el elemento primordial que simboliza la transformación perpetua de todas las cosas.`,
    content_en: `Heraclitus of Ephesus, known as the "philosopher of becoming," asserted that constant change is the essence of the universe. His famous maxim "you cannot step twice into the same river" expresses his vision that everything flows and nothing remains.\n\nFor Heraclitus, the logos is the universal law governing the flow of change, a divine reason that maintains harmony through the opposition of contraries. He considered fire the primordial element symbolizing the perpetual transformation of all things.`,
    excerpt_es: 'Filósofo del devenir que afirmó que el cambio constante es la esencia fundamental del universo.',
    excerpt_en: 'Philosopher of becoming who asserted that constant change is the fundamental essence of the universe.',
    categoryId: 'cat-ancient-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-22T00:00:00Z',
    updatedAt: '2026-06-22T00:00:00Z',
  },
  {
    id: 'entry-200-53',
    title_es: 'Parménides',
    title_en: 'Parmenides',
    slug: 'parmenides',
    content_es: `Parménides de Elea fue el fundador de la escuela eleática y uno de los filósofos presocráticos más influyentes. En su poema "Sobre la Naturaleza", distinguió entre la Vía de la Verdad, basada en el ser inmutable, y la Vía de la Opinión, basada en la apariencia engañosa de los sentidos.\n\nPara Parménides, el ser es único, inmutable, eterno e indivisible, y el cambio es una ilusión de los sentidos. Su argumento de que "lo que es, es, y lo que no es, no es" estableció los fundamentos de la lógica ontológica e influyó profundamente en Platón y toda la metafísica occidental.`,
    content_en: `Parmenides of Elea was the founder of the Eleatic school and one of the most influential pre-Socratic philosophers. In his poem "On Nature," he distinguished between the Way of Truth, based on immutable being, and the Way of Opinion, based on the deceptive appearance of the senses.\n\nFor Parmenides, being is unique, immutable, eternal, and indivisible, and change is an illusion of the senses. His argument that "what is, is, and what is not, is not" established the foundations of ontological logic and profoundly influenced Plato and all of Western metaphysics.`,
    excerpt_es: 'Fundador de la escuela eleática que afirmó la unidad e inmutabilidad del ser frente a la apariencia.',
    excerpt_en: 'Founder of the Eleatic school who asserted the unity and immutability of being against appearance.',
    categoryId: 'cat-ancient-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-23T00:00:00Z',
    updatedAt: '2026-06-23T00:00:00Z',
  },
  {
    id: 'entry-200-54',
    title_es: 'Demócrito',
    title_en: 'Democritus',
    slug: 'democrito',
    content_es: `Demócrito de Abdera fue el principal defensor del atomismo, una teoría filosófica que sostenía que toda la realidad está compuesta por partículas indivisibles e invisibles llamadas átomos que se mueven en el vacío. Esta visión materialista anticipó en más de dos milenios la física atómica moderna.\n\nPara Demócrito, todo cuanto existe —desde los objetos inanimados hasta la mente humana— es resultado de combinaciones y movimientos de átomos en el espacio vacío. Las cualidades sensibles como el color o el sabor son convenciones subjetivas, mientras que los átomos y el vacío son la única realidad objetiva.`,
    content_en: `Democritus of Abdera was the main proponent of atomism, a philosophical theory holding that all reality is composed of invisible, indivisible particles called atoms moving in the void. This materialist vision anticipated modern atomic physics by more than two millennia.\n\nFor Democritus, everything that exists — from inanimate objects to the human mind — is the result of combinations and movements of atoms in empty space. Sensory qualities like color or taste are subjective conventions, while atoms and the void are the only objective reality.`,
    excerpt_es: 'Filósofo atomista que propuso que toda la realidad se compone de partículas indivisibles en el vacío.',
    excerpt_en: 'Atomist philosopher who proposed that all reality is composed of indivisible particles in the void.',
    categoryId: 'cat-ancient-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-24T00:00:00Z',
    updatedAt: '2026-06-24T00:00:00Z',
  },
  {
    id: 'entry-200-55',
    title_es: 'Epicuro',
    title_en: 'Epicurus',
    slug: 'epicuro',
    content_es: `Epicuro fundó su escuela filosófica, el Jardín, en Atenas alrededor del 306 a.C., donde enseñaba que el objetivo supremo de la vida es alcanzar la ataraxia, un estado de serena tranquilidad libre de dolor y perturbaciones. Su filosofía malinterpretada como simple hedonismo es en realidad una ética de la moderación.\n\nPara Epicuro, el placer más elevado era la ausencia de dolor y la amistad verdadera. Sostenía que los dioses existen pero no se interesan por los humanos, que el alma es mortal y que el universo está compuesto de átomos. Su pensamiento buscaba liberar a las personas del miedo a los dioses y a la muerte.`,
    content_en: `Epicurus founded his philosophical school, the Garden, in Athens around 306 BC, where he taught that the supreme goal of life is to achieve ataraxia, a state of serene tranquility free from pain and disturbances. His philosophy, often misinterpreted as simple hedonism, is actually an ethics of moderation.\n\nFor Epicurus, the highest pleasure was the absence of pain and true friendship. He held that the gods exist but take no interest in humans, that the soul is mortal, and that the universe is composed of atoms. His thought sought to free people from the fear of gods and death.`,
    excerpt_es: 'Filósofo que fundó el epicureísmo y propuso la ataraxia como objetivo supremo de la vida.',
    excerpt_en: 'Philosopher who founded Epicureanism and proposed ataraxia as the supreme goal of life.',
    categoryId: 'cat-ancient-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-25T00:00:00Z',
    updatedAt: '2026-06-25T00:00:00Z',
  },
  {
    id: 'entry-200-56',
    title_es: 'Diógenes de Sinope',
    title_en: 'Diogenes of Sinope',
    slug: 'diogenes-de-sinope',
    content_es: `Diógenes de Sinope fue el filósofo cínico más famoso, conocido por su estilo de vida radicalmente simple y su desprecio por las convenciones sociales. Vivía en una tinaja, mendigaba su comida y se comportaba deliberadamente de manera provocativa para demostrar la artificialidad de las normas sociales.\n\nSu encuentro más célebre fue con Alejandro Magno, quien al ofrecerle conceder cualquier deseo, Diogenes simplemente le pidió que se apartara porque le tapaba el sol. Para Diógenes, la virtud consistía en vivir según la naturaleza, rechazando las comodidades y convenciones que corrompen al ser humano.`,
    content_en: `Diogenes of Sinope was the most famous Cynic philosopher, known for his radically simple lifestyle and contempt for social conventions. He lived in a tub, begged for his food, and deliberately behaved provocatively to demonstrate the artificiality of social norms.\n\nHis most celebrated encounter was with Alexander the Great, who offered to grant him any wish; Diogenes simply asked him to step aside because he was blocking the sunlight. For Diogenes, virtue consisted of living according to nature, rejecting the comforts and conventions that corrupt human beings.`,
    excerpt_es: 'El filósofo cínico más famoso, conocido por vivir en una tinaja y desafiar todas las convenciones sociales.',
    excerpt_en: 'The most famous Cynic philosopher, known for living in a tub and challenging all social conventions.',
    categoryId: 'cat-ancient-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-26T00:00:00Z',
    updatedAt: '2026-06-26T00:00:00Z',
  },
  {
    id: 'entry-200-57',
    title_es: 'Zenón de Citio',
    title_en: 'Zeno of Citium',
    slug: 'zenon-de-citio',
    content_es: `Zenón de Citio fue el fundador del estoicismo, una de las escuelas filosóficas más influyentes de la antigüedad. Enseñaba en la Stoa Pecile de Atenas, donde desarrolló una filosofía basada en la virtud como único bien y la razón como guía para vivir en armonía con la naturaleza.\n\nPara Zenón, la virtud es suficiente para la felicidad, y las emociones destructivas son el resultado de juicios erróneos. El sabio estoico vive de acuerdo con la ley natural, aceptando con serenidad lo que no puede controlar y actuando con justicia en lo que sí depende de su voluntad.`,
    content_en: `Zeno of Citium was the founder of Stoicism, one of the most influential philosophical schools of antiquity. He taught at the Stoa Poikile in Athens, where he developed a philosophy based on virtue as the only good and reason as the guide to living in harmony with nature.\n\nFor Zeno, virtue is sufficient for happiness, and destructive emotions are the result of erroneous judgments. The Stoic sage lives according to natural law, accepting with serenity what cannot be controlled and acting justly in what depends on their will.`,
    excerpt_es: 'Fundador del estoicismo, que postuló la virtud como único bien y la razón como guía de vida.',
    excerpt_en: 'Founder of Stoicism, who posited virtue as the only good and reason as life\'s guide.',
    categoryId: 'cat-ancient-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-27T00:00:00Z',
    updatedAt: '2026-06-27T00:00:00Z',
  },
  {
    id: 'entry-200-58',
    title_es: 'Plotino',
    title_en: 'Plotinus',
    slug: 'plotino',
    content_es: `Plotino fue el fundador del neoplatonismo, la última gran escuela filosófica de la antigüedad clásica. Su sistema metafísico se basa en tres hipóstasis: el Uno, la Inteligencia divina y el Alma, de las cuales emana toda la realidad en un proceso de expansión progresiva.\n\nPara Plotino, el Uno es una realidad trascendente e inefable más allá del ser y del pensamiento, de la cual todo procede por emanación. El objetivo de la filosofía es el retorno del alma individual al Uno mediante la contemplación y la purificación espiritual, alcanzando una unión mística con lo divino.`,
    content_en: `Plotinus was the founder of Neoplatonism, the last great philosophical school of classical antiquity. His metaphysical system is based on three hypostases: the One, the divine Intellect, and the Soul, from which all reality emanates in a process of progressive expansion.\n\nFor Plotinus, the One is a transcendent and ineffable reality beyond being and thought, from which everything proceeds by emanation. The goal of philosophy is the return of the individual soul to the One through contemplation and spiritual purification, achieving a mystical union with the divine.`,
    excerpt_es: 'Fundador del neoplatonismo que describió la realidad como emanación del Uno trascendente.',
    excerpt_en: 'Founder of Neoplatonism who described reality as emanation from the transcendent One.',
    categoryId: 'cat-ancient-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-28T00:00:00Z',
    updatedAt: '2026-06-28T00:00:00Z',
  },
  {
    id: 'entry-200-59',
    title_es: 'Séneca el Joven',
    title_en: 'Seneca the Younger',
    slug: 'seneca-el-joven',
    content_es: `Séneca fue un filósofo estoico, dramaturgo y político romano que sirvió como tutor y consejero del emperador Nerón. Sus escritos, incluyendo las "Cartas a Lucilio", son una de las fuentes más accesibles del pensamiento estoico y abordan temas como la brevedad de la vida, la ira y la serenidad.\n\nLa filosofía de Séneca es eminentemente práctica: enseñaba que la filosofía debe aplicarse a la vida cotidiana para alcanzar la virtud y la paz interior. Acusado de conspiración contra Nerón, fue obligado a suicidarse, y murió con la dignidad estoica que predicó en sus escritos.`,
    content_en: `Seneca was a Stoic philosopher, playwright, and Roman politician who served as tutor and advisor to Emperor Nero. His writings, including the "Letters to Lucilius," are among the most accessible sources of Stoic thought, addressing topics such as the brevity of life, anger, and serenity.\n\nSeneca's philosophy is eminently practical: he taught that philosophy must be applied to daily life to achieve virtue and inner peace. Accused of conspiracy against Nero, he was forced to commit suicide and died with the Stoic dignity he preached in his writings.`,
    excerpt_es: 'Filósofo estoico romano, tutor de Nerón, cuyas cartas son una guía práctica de vida virtuosa.',
    excerpt_en: 'Roman Stoic philosopher, tutor to Nero, whose letters are a practical guide to virtuous living.',
    categoryId: 'cat-ancient-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-29T00:00:00Z',
    updatedAt: '2026-06-29T00:00:00Z',
  },
  {
    id: 'entry-200-60',
    title_es: 'Marco Aurelio',
    title_en: 'Marcus Aurelius',
    slug: 'marco-aurelio',
    content_es: `Marco Aurelio fue emperador romano de 161 a 180 d.C. y uno de los filósofos estoicos más reconocidos. Su obra "Meditaciones", escrita durante sus campañas militares, es un diario personal de reflexiones sobre la virtud, el deber, la mortalidad y el gobierno del imperio.\n\nPara Marco Aurelio, la filosofía estoica era un manual de vida práctica: recordarse constantemente que la naturaleza es cambio, que la muerte es natural y que el deber del ser humano es actuar con justicia y benevolencia. Es considerado el último de los "cinco buenos emperadores" y su reinado representó la cúspide del Imperio Romano.`,
    content_en: `Marcus Aurelius was Roman emperor from 161 to 180 AD and one of the most recognized Stoic philosophers. His work "Meditations," written during his military campaigns, is a personal journal of reflections on virtue, duty, mortality, and the governance of the empire.\n\nFor Marcus Aurelius, Stoic philosophy was a manual for practical living: constantly reminding himself that nature is change, that death is natural, and that the human duty is to act with justice and benevolence. He is considered the last of the "five good emperors" and his reign represented the peak of the Roman Empire.`,
    excerpt_es: 'Emperador romano y filósofo estoico cuyas "Meditaciones" reflexionan sobre la virtud y la mortalidad.',
    excerpt_en: 'Roman emperor and Stoic philosopher whose "Meditations" reflect on virtue and mortality.',
    categoryId: 'cat-ancient-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-30T00:00:00Z',
    updatedAt: '2026-06-30T00:00:00Z',
  },
  {
    id: 'entry-200-61',
    title_es: 'Tomás de Aquino',
    title_en: 'Thomas Aquinas',
    slug: 'tomas-de-aquino',
    content_es: `Tomás de Aquino fue el más grande filósofo y teólogo de la escolástica medieval. Su obra monumental, la "Summa Theologica", busca integrar la filosofía aristotélica con la teología cristiana, estableciendo una síntesis racional de la fe.\n\nDesarrolló las cinco vías o pruebas de la existencia de Dios: el movimiento, la causalidad eficiente, la contingencia, los grados de perfección y el orden teleológico del universo. Su teoría de la ley natural sostiene que la moral humana se fundamenta en principios racionales universales derivados de la naturaleza creada.`,
    content_en: `Thomas Aquinas was the greatest philosopher and theologian of medieval Scholasticism. His monumental work, the "Summa Theologica," seeks to integrate Aristotelian philosophy with Christian theology, establishing a rational synthesis of faith.\n\nHe developed the five ways or proofs of God's existence: motion, efficient causality, contingency, degrees of perfection, and the teleological order of the universe. His theory of natural law holds that human morality is grounded in universal rational principles derived from created nature.`,
    excerpt_es: 'Máximo exponente de la escolástica que integró el aristotelismo con la teología cristiana.',
    excerpt_en: 'Greatest exponent of Scholasticism who integrated Aristotelianism with Christian theology.',
    categoryId: 'cat-medieval-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-01T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
  },
  {
    id: 'entry-200-62',
    title_es: 'Avicena (Ibn Sina)',
    title_en: 'Avicenna (Ibn Sina)',
    slug: 'avicena-ibn-sina',
    content_es: `Avicena, conocido en el mundo islámico como Ibn Sina, fue uno de los filósofos y médicos más importantes de la Edad de Oro islámica. Su obra "El Libro de la Curación" es una enciclopedia filosófica que abarca lógica, ciencias naturales, matemáticas y metafísica.\n\nEn metafísica, Avicena distinguió entre esencia y existencia, argumentando que la existencia es un accidente añadido a la esencia. Su prueba de la existencia de Dios, basada en la contingencia, influyó profundamente en la filosofía medieval europea. Como médico, su "Canon de Medicina" fue el texto médico más usado en Europa durante siglos.`,
    content_en: `Avicenna, known in the Islamic world as Ibn Sina, was one of the most important philosophers and physicians of the Islamic Golden Age. His work "The Book of Healing" is a philosophical encyclopedia covering logic, natural sciences, mathematics, and metaphysics.\n\nIn metaphysics, Avicenna distinguished between essence and existence, arguing that existence is an accident added to essence. His proof of God's existence, based on contingency, profoundly influenced medieval European philosophy. As a physician, his "Canon of Medicine" was the most used medical text in Europe for centuries.`,
    excerpt_es: 'Filósofo y médico islámico cuya obra sobre metafísica y medicina influyó en Oriente y Occidente.',
    excerpt_en: 'Islamic philosopher and physician whose work on metaphysics and medicine influenced East and West.',
    categoryId: 'cat-medieval-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-02T00:00:00Z',
    updatedAt: '2026-07-02T00:00:00Z',
  },
  {
    id: 'entry-200-63',
    title_es: 'Averroes (Ibn Rushd)',
    title_en: 'Averroes (Ibn Rushd)',
    slug: 'averroes-ibn-rushd',
    content_es: `Averroes, conocido en el mundo islámico como Ibn Rushd, fue el más importante comentarista de Aristóteles en la tradición islámica. Sus comentarios fueron tan influyentes en Europa que se le conocía simplemente como "el Comentarista" y desempeñaron un papel crucial en el redescubrimiento de Aristóteles en el Occidente latino.\n\nAverroes defendió la compatibilidad entre la filosofía y la religión, argumentando que ambas buscan la misma verdad pero a través de caminos diferentes. Su doctrina de la "doble verdad" sostenía que una proposición puede ser verdadera filosóficamente y falsa teológicamente, y viceversa. Su racionalismo influyó en el averroísmo latino y en pensadores como Tomás de Aquino.`,
    content_en: `Averroes, known in the Islamic world as Ibn Rushd, was the most important commentator on Aristotle in the Islamic tradition. His commentaries were so influential in Europe that he was known simply as "the Commentator" and played a crucial role in the rediscovery of Aristotle in the Latin West.\n\nAverroes defended the compatibility between philosophy and religion, arguing that both seek the same truth but through different paths. His doctrine of the "double truth" held that a proposition could be philosophically true and theologically false, and vice versa. His rationalism influenced Latin Averroism and thinkers like Thomas Aquinas.`,
    excerpt_es: 'El mayor comentarista de Aristóteles en el Islam, defensor del racionalismo y la doble verdad.',
    excerpt_en: 'The greatest commentator on Aristotle in Islam, defender of rationalism and double truth.',
    categoryId: 'cat-medieval-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-03T00:00:00Z',
    updatedAt: '2026-07-03T00:00:00Z',
  },
  {
    id: 'entry-200-64',
    title_es: 'Maimónides',
    title_en: 'Maimonides',
    slug: 'maimonides',
    content_es: `Maimónides, también conocido como Rambam, fue el más importante filósofo judío de la Edad Media. Su obra "Guía de los Perplejos" busca reconciliar la fe judía con la filosofía aristotélica, ofreciendo una interpretación racional de las escrituras para aquellos que dudan entre la tradición y la razón.\n\nMaimónides argumentaba que Dios existe necesariamente y que los atributos divinos descritos en la Biblia deben entenderse de manera negativa o analógica. También fue un renombrado médico personal de Saladino y sistematizó la ley judía en su "Mishné Torá", que sigue siendo una autoridad en el judaísmo ortodoxo.`,
    content_en: `Maimonides, also known as Rambam, was the most important Jewish philosopher of the Middle Ages. His work "Guide for the Perplexed" seeks to reconcile Jewish faith with Aristotelian philosophy, offering a rational interpretation of scripture for those who waver between tradition and reason.\n\nMaimonides argued that God exists necessarily and that the divine attributes described in the Bible must be understood negatively or analogically. He was also a renowned physician serving Saladin and systematized Jewish law in his "Mishneh Torah," which remains an authority in Orthodox Judaism.`,
    excerpt_es: 'Máximo filósofo judío medieval que buscó reconciliar la fe con la razón aristotélica.',
    excerpt_en: 'Greatest medieval Jewish philosopher who sought to reconcile faith with Aristotelian reason.',
    categoryId: 'cat-medieval-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-04T00:00:00Z',
    updatedAt: '2026-07-04T00:00:00Z',
  },
  {
    id: 'entry-200-65',
    title_es: 'Anselmo de Canterbury',
    title_en: 'Anselm of Canterbury',
    slug: 'anselmo-de-canterbury',
    content_es: `Anselmo de Canterbury fue un filósofo y teólogo medieval famoso por formular el argumento ontológico de la existencia de Dios. Su principio "creo para entender" (fides quaerens intellectum) establece que la fe busca la comprensión racional y que la creencia precede al entendimiento.\n\nEl argumento ontológico sostiene que Dios es "aquello mayor que lo cual nada puede pensarse" y que, como existe en el entendimiento, debe existir también en la realidad. Aunque criticado por Tomás de Aquino y Kant, este argumento ha sido retomado por filósofos contemporáneos como Alvin Plantinga.`,
    content_en: `Anselm of Canterbury was a medieval philosopher and theologian famous for formulating the ontological argument for God's existence. His principle "I believe in order to understand" (fides quaerens intellectum) establishes that faith seeks rational understanding and that belief precedes understanding.\n\nThe ontological argument holds that God is "that than which nothing greater can be conceived" and that, since it exists in the understanding, it must also exist in reality. Although criticized by Thomas Aquinas and Kant, this argument has been revived by contemporary philosophers like Alvin Plantinga.`,
    excerpt_es: 'Filósofo medieval que formuló el famoso argumento ontológico de la existencia de Dios.',
    excerpt_en: 'Medieval philosopher who formulated the famous ontological argument for God\'s existence.',
    categoryId: 'cat-medieval-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-05T00:00:00Z',
    updatedAt: '2026-07-05T00:00:00Z',
  },
  {
    id: 'entry-200-66',
    title_es: 'René Descartes',
    title_en: 'René Descartes',
    slug: 'rene-descartes',
    content_es: `René Descartes, considerado el padre de la filosofía moderna, inició su búsqueda filosófica con la duda metódica, dudando de todo hasta encontrar una certeza indubitable. Su famosa conclusión "Cogito, ergo sum" (Pienso, luego existo) se convirtió en el fundamento de su sistema filosófico.\n\nDescartes estableció un dualismo radical entre la mente (res cogitans) y el cuerpo (res extensa), argumentando que son dos sustancias distintas que interactúan en el ser humano. Su método racionalista y su geometría analítica transformaron tanto la filosofía como las matemáticas, sentando las bases del pensamiento moderno.`,
    content_en: `René Descartes, considered the father of modern philosophy, began his philosophical quest with methodic doubt, doubting everything until finding an indubitable certainty. His famous conclusion "Cogito, ergo sum" (I think, therefore I am) became the foundation of his philosophical system.\n\nDescartes established a radical dualism between mind (res cogitans) and body (res extensa), arguing they are two distinct substances that interact in the human being. His rationalist method and analytic geometry transformed both philosophy and mathematics, laying the foundations of modern thought.`,
    excerpt_es: 'Padre de la filosofía moderna que estableció el "Cogito, ergo sum" como fundamento del conocimiento.',
    excerpt_en: 'Father of modern philosophy who established "Cogito, ergo sum" as the foundation of knowledge.',
    categoryId: 'cat-modern-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-06T00:00:00Z',
    updatedAt: '2026-07-06T00:00:00Z',
  },
  {
    id: 'entry-200-67',
    title_es: 'John Locke',
    title_en: 'John Locke',
    slug: 'john-locke',
    content_es: `John Locke fue un filósofo inglés cuyas ideas sobre el empirismo y la filosofía política influyeron profundamente en la Ilustración. Sostenía que la mente humana es una tabula rasa o pizarra en blanco al nacer, y que todo conocimiento proviene de la experiencia sensible y la reflexión.\n\nEn política, Locke defendió los derechos naturales a la vida, la libertad y la propiedad, y argumentó que el gobierno legítimo se basa en el consentimiento de los gobernados. Su teoría del contrato social influyó directamente en la Declaración de Independencia de Estados Unidos y en el pensamiento democrático moderno.`,
    content_en: `John Locke was an English philosopher whose ideas on empiricism and political philosophy profoundly influenced the Enlightenment. He held that the human mind is a tabula rasa or blank slate at birth, and that all knowledge comes from sensory experience and reflection.\n\nIn politics, Locke defended the natural rights to life, liberty, and property, and argued that legitimate government is based on the consent of the governed. His social contract theory directly influenced the United States Declaration of Independence and modern democratic thought.`,
    excerpt_es: 'Filósofo empirista que defendió los derechos naturales y la teoría del contrato social.',
    excerpt_en: 'Empiricist philosopher who defended natural rights and the social contract theory.',
    categoryId: 'cat-modern-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-07T00:00:00Z',
    updatedAt: '2026-07-07T00:00:00Z',
  },
  {
    id: 'entry-200-68',
    title_es: 'David Hume',
    title_en: 'David Hume',
    slug: 'david-hume',
    content_es: `David Hume fue el filósofo empirista más radical de la Ilustración escocesa. Su obra "Tratado de la Naturaleza Humana" buscaba establecer una ciencia del ser humano basada en la experiencia, afirmando que todas las ideas derivan de impresiones sensibles.\n\nHume planteó el problema de la inducción, argumentando que no podemos justificar racionalmente la creencia en que el futuro se parecerá al pasado. Su escepticismo sobre la causalidad, el yo sustancial y los milagros desafió los fundamentos de la metafísica y la religión, despertando a Kant de su "sueño dogmático".`,
    content_en: `David Hume was the most radical empiricist philosopher of the Scottish Enlightenment. His work "A Treatise of Human Nature" sought to establish a science of human beings based on experience, asserting that all ideas derive from sensory impressions.\n\nHume posed the problem of induction, arguing that we cannot rationally justify the belief that the future will resemble the past. His skepticism about causality, the substantial self, and miracles challenged the foundations of metaphysics and religion, awakening Kant from his "dogmatic slumber."`,
    excerpt_es: 'Filósofo empirista radical que planteó el problema de la inducción y desafió la causalidad.',
    excerpt_en: 'Radical empiricist philosopher who posed the problem of induction and challenged causality.',
    categoryId: 'cat-modern-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-08T00:00:00Z',
    updatedAt: '2026-07-08T00:00:00Z',
  },
  {
    id: 'entry-200-69',
    title_es: 'Jean-Jacques Rousseau',
    title_en: 'Jean-Jacques Rousseau',
    slug: 'jean-jacques-rousseau',
    content_es: `Jean-Jacques Rousseau fue un filósofo suizo cuyas ideas sobre la libertad, la educación y la política revolucionaron el pensamiento ilustrado. Su obra "El Contrato Social" propone que la sociedad legítima debe basarse en la voluntad general, que busca el bien común por encima de los intereses particulares.\n\nRousseau imaginó un "estado de naturaleza" donde el ser humano era bueno y libre, corrompido posteriormente por la civilización y la propiedad privada. Su idea de que la educación debía adaptarse al desarrollo natural del niño, expresada en "Emilio", influyó profundamente en la pedagogía moderna y en los ideales de la Revolución Francesa.`,
    content_en: `Jean-Jacques Rousseau was a Swiss philosopher whose ideas on freedom, education, and politics revolutionized Enlightenment thought. His work "The Social Contract" proposes that legitimate society must be based on the general will, which seeks the common good above particular interests.\n\nRousseau imagined a "state of nature" where humans were good and free, later corrupted by civilization and private property. His idea that education should adapt to the child's natural development, expressed in "Emile," profoundly influenced modern pedagogy and the ideals of the French Revolution.`,
    excerpt_es: 'Filósofo ilustrado que propuso la voluntad general y el contrato social como base de la sociedad.',
    excerpt_en: 'Enlightenment philosopher who proposed the general will and social contract as society\'s foundation.',
    categoryId: 'cat-modern-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-09T00:00:00Z',
    updatedAt: '2026-07-09T00:00:00Z',
  },
  {
    id: 'entry-200-70',
    title_es: 'Immanuel Kant',
    title_en: 'Immanuel Kant',
    slug: 'immanuel-kant',
    content_es: `Immanuel Kant revolucionó la filosofía con su "Crítica de la Razón Pura", donde argumentó que el conocimiento surge de la combinación de la experiencia sensible con las categorías a priori del entendimiento. Esta "revolución copernicana" en filosofía sostiene que los objetos se conforman a nuestro conocimiento, no al revés.\n\nSu imperativo categórico, formulado como "obra solo según la máxima mediante la cual puedas querer que se convierta en ley universal", es el fundamento de su ética deontológica. Kant también defendió la Ilustración como la salida del hombre de su autoculpable minoría de edad, celebrando el lema "Sapere aude!".`,
    content_en: `Immanuel Kant revolutionized philosophy with his "Critique of Pure Reason," where he argued that knowledge arises from the combination of sensory experience with the a priori categories of understanding. This "Copernican revolution" in philosophy holds that objects conform to our knowledge, not the reverse.\n\nHis categorical imperative, formulated as "act only according to that maxim whereby you can at the same time will that it should become a universal law," is the foundation of his deontological ethics. Kant also defended the Enlightenment as humanity's exit from its self-incurred immaturity, celebrating the motto "Sapere aude!"`,
    excerpt_es: 'Filósofo que revolucionó la filosofía con su crítica de la razón y el imperativo categórico.',
    excerpt_en: 'Philosopher who revolutionized philosophy with his critique of reason and the categorical imperative.',
    categoryId: 'cat-modern-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-10T00:00:00Z',
    updatedAt: '2026-07-10T00:00:00Z',
  },
  {
    id: 'entry-200-71',
    title_es: 'Georg Hegel',
    title_en: 'Georg Hegel',
    slug: 'georg-hegel',
    content_es: `Georg Wilhelm Friedrich Hegel desarrolló un sistema filosófico integral basado en la dialéctica, donde el desarrollo de la realidad ocurre a través de la lucha y síntesis de opuestos. Su famosa triada dialéctica de tesis, antítesis y síntesis describe el movimiento del Espíritu Absoluto hacia la autoconciencia.\n\nPara Hegel, la historia universal es el progreso de la conciencia de la libertad, donde cada época realiza una etapa del desarrollo del Espíritu. Su "Fenomenología del Espíritu" narra el viaje de la conciencia desde la percepción sensorial hasta el saber absoluto, influyendo profundamente en Marx, Kierkegaard y la filosofía continental posterior.`,
    content_en: `Georg Wilhelm Friedrich Hegel developed a comprehensive philosophical system based on dialectics, where the development of reality occurs through the struggle and synthesis of opposites. His famous dialectical triad of thesis, antithesis, and synthesis describes the movement of the Absolute Spirit toward self-consciousness.\n\nFor Hegel, universal history is the progress of the consciousness of freedom, where each epoch realizes a stage of the Spirit's development. His "Phenomenology of Spirit" narrates the journey of consciousness from sensory perception to absolute knowledge, profoundly influencing Marx, Kierkegaard, and subsequent continental philosophy.`,
    excerpt_es: 'Filósofo del idealismo alemán que desarrolló la dialéctica del Espíritu Absoluto en la historia.',
    excerpt_en: 'German idealist philosopher who developed the dialectics of Absolute Spirit in history.',
    categoryId: 'cat-modern-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-11T00:00:00Z',
    updatedAt: '2026-07-11T00:00:00Z',
  },
  {
    id: 'entry-200-72',
    title_es: 'Arthur Schopenhauer',
    title_en: 'Arthur Schopenhauer',
    slug: 'arthur-schopenhauer',
    content_es: `Arthur Schopenhauer es conocido por su filosofía del pesimismo y su concepto de la Voluntad como fuerza fundamental del universo. En su obra principal "El mundo como voluntad y representación", argumenta que la realidad fenoménica es una representación, mientras que la esencia subyacente es una Voluntad ciega e irracional.\n\nPara Schopenhauer, la Voluntad es la fuente del sufrimiento eterno, ya que genera deseos insaciables que nunca se satisfacen plenamente. La liberación del sufrimiento solo puede alcanzarse mediante el arte, la compasión ética y la negación ascética de la voluntad. Fue el primer filósofo occidental importante en incorporar elementos del pensamiento budista e hindú.`,
    content_en: `Arthur Schopenhauer is known for his philosophy of pessimism and his concept of the Will as the fundamental force of the universe. In his main work "The World as Will and Representation," he argues that phenomenal reality is a representation, while the underlying essence is a blind and irrational Will.\n\nFor Schopenhauer, the Will is the source of eternal suffering, as it generates insatiable desires that are never fully satisfied. Liberation from suffering can only be achieved through art, ethical compassion, and the ascetic denial of the will. He was the first major Western philosopher to incorporate elements of Buddhist and Hindu thought.`,
    excerpt_es: 'Filósofo del pesimismo que identificó la Voluntad como la fuerza irracional que genera el sufrimiento.',
    excerpt_en: 'Philosopher of pessimism who identified the Will as the irrational force generating suffering.',
    categoryId: 'cat-modern-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-12T00:00:00Z',
    updatedAt: '2026-07-12T00:00:00Z',
  },
  {
    id: 'entry-200-73',
    title_es: 'Karl Marx',
    title_en: 'Karl Marx',
    slug: 'karl-marx',
    content_es: `Karl Marx fue un filósofo, economista y revolucionario alemán cuyo análisis del capitalismo y la lucha de clases transformó el pensamiento político y económico mundial. Su obra "El Capital" es un análisis crítico del modo de producción capitalista y sus contradicciones internas.\n\nMarx desarrolló el materialismo histórico, según el cual las condiciones económicas y materiales determinan la estructura social, política e ideológica de una sociedad. Sostenía que la historia es una sucesión de luchas de clases y que el capitalismo sería reemplazado por el comunismo a través de una revolución proletaria que aboliría la propiedad privada de los medios de producción.`,
    content_en: `Karl Marx was a German philosopher, economist, and revolutionary whose analysis of capitalism and class struggle transformed worldwide political and economic thought. His work "Capital" is a critical analysis of the capitalist mode of production and its internal contradictions.\n\nMarx developed historical materialism, according to which economic and material conditions determine the social, political, and ideological structure of a society. He held that history is a succession of class struggles and that capitalism would be replaced by communism through a proletarian revolution that would abolish private ownership of the means of production.`,
    excerpt_es: 'Filósofo y economista que analizó el capitalismo y propuso el comunismo como superación histórica.',
    excerpt_en: 'Philosopher and economist who analyzed capitalism and proposed communism as historical transcendence.',
    categoryId: 'cat-modern-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-13T00:00:00Z',
    updatedAt: '2026-07-13T00:00:00Z',
  },
  {
    id: 'entry-200-74',
    title_es: 'Søren Kierkegaard',
    title_en: 'Søren Kierkegaard',
    slug: 'soren-kierkegaard',
    content_es: `Søren Kierkegaard, considerado el padre del existencialismo, centró su filosofía en la experiencia subjetiva del individuo, la angustia y la fe. Criticó la filosofía sistemática de Hegel por ignorar la existencia concreta y singular del ser humano.\n\nPara Kierkegaard, la verdad es subjetividad y la vida presenta tres estadios: estético, ético y religioso. El "salto de fe" es un acto irracional y personal que no puede justificarse mediante la razón, ejemplificado en la historia bíblica de Abraham e Isaac. Su énfasis en la elección individual, la angustia y la autenticidad anticipó las preocupaciones centrales del existencialismo del siglo XX.`,
    content_en: `Søren Kierkegaard, considered the father of existentialism, centered his philosophy on the subjective experience of the individual, anxiety, and faith. He criticized Hegel's systematic philosophy for ignoring the concrete and singular existence of the human being.\n\nFor Kierkegaard, truth is subjectivity and life presents three stages: aesthetic, ethical, and religious. The "leap of faith" is an irrational and personal act that cannot be justified through reason, exemplified in the biblical story of Abraham and Isaac. His emphasis on individual choice, anxiety, and authenticity anticipated the central concerns of twentieth-century existentialism.`,
    excerpt_es: 'Padre del existencialismo que enfatizó la subjetividad, la angustia y el salto de fe individual.',
    excerpt_en: 'Father of existentialism who emphasized subjectivity, anxiety, and the individual leap of faith.',
    categoryId: 'cat-modern-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-14T00:00:00Z',
    updatedAt: '2026-07-14T00:00:00Z',
  },
  {
    id: 'entry-200-75',
    title_es: 'Friedrich Nietzsche',
    title_en: 'Friedrich Nietzsche',
    slug: 'friedrich-nietzsche',
    content_es: `Friedrich Nietzsche fue un filósofo alemán que proclamó la "muerte de Dios" y criticó la moral cristiana como una moral de esclavos que reprime los instintos vitales. Su filosofía celebra la vida, la voluntad de poder y la creación de nuevos valores.\n\nConceptos clave de Nietzsche incluyen el Übermensch, un ideal de ser humano que crea sus propios valores más allá del bien y del mal; el eterno retorno, la idea de que el universo y todos los eventos se repiten infinitamente; y la voluntad de poder como fuerza impulsora fundamental. Su estilo aforístico y provocador influyó en el existencialismo, el posmodernismo y el pensamiento crítico del siglo XX.`,
    content_en: `Friedrich Nietzsche was a German philosopher who proclaimed the "death of God" and criticized Christian morality as a slave morality that represses vital instincts. His philosophy celebrates life, the will to power, and the creation of new values.\n\nKey Nietzschean concepts include the Übermensch, an ideal human being who creates their own values beyond good and evil; the eternal recurrence, the idea that the universe and all events repeat infinitely; and the will to power as the fundamental driving force. His aphoristic and provocative style influenced existentialism, postmodernism, and twentieth-century critical thought.`,
    excerpt_es: 'Filósofo que proclamó la muerte de Dios y propuso la voluntad de poder y el Übermensch.',
    excerpt_en: 'Philosopher who proclaimed the death of God and proposed the will to power and the Übermensch.',
    categoryId: 'cat-modern-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-15T00:00:00Z',
    updatedAt: '2026-07-15T00:00:00Z',
  },
  {
    id: 'entry-200-76',
    title_es: 'John Stuart Mill',
    title_en: 'John Stuart Mill',
    slug: 'john-stuart-mill',
    content_es: `John Stuart Mill fue un filósofo y economista político inglés, principal exponente del utilitarismo clásico. Su obra "El Utilitarismo" defiende el principio de la mayor felicidad: las acciones son correctas en la medida en que promueven la felicidad general.\n\nMill también fue un defensor incansable de la libertad individual. En "Sobre la Libertad", formuló el principio del daño: el único propósito por el cual el poder puede ejercerse sobre un miembro de la comunidad es para prevenir el daño a otros. Además, fue uno de los primeros defensores del feminismo, argumentando en "La sujeción de la mujer" por la igualdad de derechos entre hombres y mujeres.`,
    content_en: `John Stuart Mill was an English philosopher and political economist, the main exponent of classical utilitarianism. His work "Utilitarianism" defends the greatest happiness principle: actions are right insofar as they promote general happiness.\n\nMill was also a tireless defender of individual liberty. In "On Liberty," he formulated the harm principle: the only purpose for which power can be exercised over a community member is to prevent harm to others. He was also an early advocate of feminism, arguing in "The Subjection of Women" for equal rights between men and women.`,
    excerpt_es: 'Filósofo utilitarista que defendió la libertad individual y el principio de la mayor felicidad.',
    excerpt_en: 'Utilitarian philosopher who defended individual liberty and the greatest happiness principle.',
    categoryId: 'cat-modern-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-16T00:00:00Z',
    updatedAt: '2026-07-16T00:00:00Z',
  },
  {
    id: 'entry-200-77',
    title_es: 'Jeremy Bentham',
    title_en: 'Jeremy Bentham',
    slug: 'jeremy-bentham',
    content_es: `Jeremy Bentham fue el fundador del utilitarismo, una teoría ética que sostiene que la moralidad de una acción se determina por su utilidad para producir la mayor felicidad para el mayor número de personas. Su "principio de la mayor felicidad" es la base de la ética consecuencialista moderna.\n\nBentham también es conocido por su diseño del Panóptico, una prisión circular donde los reclusos podían ser observados constantemente sin saber cuándo eran vigilados. Aunque nunca se construyó completamente, el Panóptico se ha convertido en un poderoso símbolo del control social y la vigilancia, analizado posteriormente por Michel Foucault en "Vigilar y Castigar".`,
    content_en: `Jeremy Bentham was the founder of utilitarianism, an ethical theory holding that the morality of an action is determined by its utility in producing the greatest happiness for the greatest number of people. His "greatest happiness principle" is the foundation of modern consequentialist ethics.\n\nBentham is also known for his design of the Panopticon, a circular prison where inmates could be constantly observed without knowing when they were being watched. Although never fully built, the Panopticon has become a powerful symbol of social control and surveillance, later analyzed by Michel Foucault in "Discipline and Punish."`,
    excerpt_es: 'Fundador del utilitarismo que propuso el principio de la mayor felicidad como fundamento moral.',
    excerpt_en: 'Founder of utilitarianism who proposed the greatest happiness principle as the moral foundation.',
    categoryId: 'cat-modern-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-17T00:00:00Z',
    updatedAt: '2026-07-17T00:00:00Z',
  },
  {
    id: 'entry-200-78',
    title_es: 'Martin Heidegger',
    title_en: 'Martin Heidegger',
    slug: 'martin-heidegger',
    content_es: `Martin Heidegger fue uno de los filósofos más influyentes del siglo XX, conocido por su obra "Ser y Tiempo", donde aborda la pregunta fundamental por el sentido del ser. Introdujo el concepto de Dasein para referirse al ser humano como un ser cuya existencia misma está en cuestión.\n\nHeidegger analiza la existencia humana en términos de autenticidad e inautenticidad, enfrentamiento con la muerte, temporalidad y cuidado. Su fenomenología existencial influyó profundamente en Sartre, Merleau-Ponty, Gadamer y toda la tradición hermenéutica y existencialista, aunque su controvertida afiliación al nazismo sigue siendo objeto de debate ético e intelectual.`,
    content_en: `Martin Heidegger was one of the most influential philosophers of the twentieth century, known for his work "Being and Time," which addresses the fundamental question of the meaning of being. He introduced the concept of Dasein to refer to the human being as a being whose very existence is in question.\n\nHeidegger analyzes human existence in terms of authenticity and inauthenticity, confrontation with death, temporality, and care. His existential phenomenology profoundly influenced Sartre, Merleau-Ponty, Gadamer, and the entire hermeneutic and existentialist tradition, though his controversial affiliation with Nazism remains a subject of ethical and intellectual debate.`,
    excerpt_es: 'Filósofo existencial que replanteó la pregunta por el ser mediante el análisis del Dasein.',
    excerpt_en: 'Existential philosopher who reopened the question of being through the analysis of Dasein.',
    categoryId: 'cat-contemporary-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-18T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
  },
  {
    id: 'entry-200-79',
    title_es: 'Jean-Paul Sartre',
    title_en: 'Jean-Paul Sartre',
    slug: 'jean-paul-sartre',
    content_es: `Jean-Paul Sartre fue el principal exponente del existencialismo francés y uno de los intelectuales más influyentes del siglo XX. Su obra "El Ser y la Nada" desarrolla una fenomenología de la conciencia y la libertad humana, afirmando que "la existencia precede a la esencia".\n\nPara Sartre, el ser humano está condenado a ser libre: no hay naturaleza humana predeterminada, y cada persona debe definirse a través de sus acciones. La "mala fe" es el autoengaño mediante el cual negamos nuestra libertad y nos refugiamos en roles sociales predeterminados. Su compromiso político y su relación con Simone de Beauvoir marcaron la vida intelectual francesa de posguerra.`,
    content_en: `Jean-Paul Sartre was the main exponent of French existentialism and one of the most influential intellectuals of the twentieth century. His work "Being and Nothingness" develops a phenomenology of consciousness and human freedom, asserting that "existence precedes essence."\n\nFor Sartre, humans are condemned to be free: there is no predetermined human nature, and each person must define themselves through their actions. "Bad faith" is the self-deception by which we deny our freedom and take refuge in predetermined social roles. His political commitment and his relationship with Simone de Beauvoir marked post-war French intellectual life.`,
    excerpt_es: 'Principal exponente del existencialismo que afirmó que la existencia precede a la esencia.',
    excerpt_en: 'Main exponent of existentialism who asserted that existence precedes essence.',
    categoryId: 'cat-contemporary-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-19T00:00:00Z',
    updatedAt: '2026-07-19T00:00:00Z',
  },
  {
    id: 'entry-200-80',
    title_es: 'Michel Foucault',
    title_en: 'Michel Foucault',
    slug: 'michel-foucault',
    content_es: `Michel Foucault fue un filósofo francés cuyo trabajo sobre el poder, el conocimiento y las instituciones sociales transformó las ciencias humanas. Sus análisis arqueológicos y genealógicos revelan cómo las prácticas discursivas e instituciones moldean la subjetividad y la verdad.\n\nObras como "Vigilar y Castigar" y "La Historia de la Sexualidad" examinan cómo el poder disciplinario opera a través de instituciones como la prisión, el hospital, la escuela y la clínica. Foucault desarrolló conceptos como biopolítica, gubernamentalidad y dispositivo, que han sido fundamentales para la teoría crítica, los estudios culturales y el pensamiento posmoderno.`,
    content_en: `Michel Foucault was a French philosopher whose work on power, knowledge, and social institutions transformed the human sciences. His archaeological and genealogical analyses reveal how discursive practices and institutions shape subjectivity and truth.\n\nWorks such as "Discipline and Punish" and "The History of Sexuality" examine how disciplinary power operates through institutions like the prison, hospital, school, and clinic. Foucault developed concepts such as biopolitics, governmentality, and apparatus, which have been fundamental for critical theory, cultural studies, and postmodern thought.`,
    excerpt_es: 'Filósofo francés que analizó las relaciones entre poder, conocimiento y las instituciones sociales.',
    excerpt_en: 'French philosopher who analyzed the relationships between power, knowledge, and social institutions.',
    categoryId: 'cat-contemporary-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-20T00:00:00Z',
    updatedAt: '2026-07-20T00:00:00Z',
  },
  {
    id: 'entry-200-81',
    title_es: 'Ludwig Wittgenstein',
    title_en: 'Ludwig Wittgenstein',
    slug: 'ludwig-wittgenstein',
    content_es: `Ludwig Wittgenstein fue uno de los filósofos más importantes del siglo XX, cuyo trabajo transformó la filosofía del lenguaje. Su primera obra, el "Tractatus Logico-Philosophicus", sostiene que el lenguaje representa la realidad mediante una estructura lógica compartida y que los límites de mi lenguaje son los límites de mi mundo.\n\nWittgenstein revolucionó posteriormente su propio pensamiento en "Investigaciones Filosóficas", donde introduce el concepto de juegos de lenguaje y el significado como uso. Para el segundo Wittgenstein, los problemas filosóficos surgen de confusiones lingüísticas y la labor del filósofo es terapéutica: disolver problemas mediante el análisis del lenguaje ordinario.`,
    content_en: `Ludwig Wittgenstein was one of the most important philosophers of the twentieth century, whose work transformed the philosophy of language. His early work, the "Tractatus Logico-Philosophicus," holds that language represents reality through a shared logical structure and that the limits of my language are the limits of my world.\n\nWittgenstein later revolutionized his own thought in "Philosophical Investigations," where he introduces the concept of language games and meaning as use. For the later Wittgenstein, philosophical problems arise from linguistic confusions and the philosopher's task is therapeutic: to dissolve problems through the analysis of ordinary language.`,
    excerpt_es: 'Filósofo del lenguaje que transformó la filosofía con sus teorías de la representación y los juegos de lenguaje.',
    excerpt_en: 'Philosopher of language who transformed philosophy with his theories of representation and language games.',
    categoryId: 'cat-contemporary-philosophers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-21T00:00:00Z',
    updatedAt: '2026-07-21T00:00:00Z',
  },
  {
    id: 'entry-200-82',
    title_es: 'Cinismo',
    title_en: 'Cynicism',
    slug: 'cinismo',
    content_es: `El Cinismo fue una escuela filosófica de la antigua Grecia fundada por Antístenes, discípulo de Sócrates, y popularizada por Diógenes de Sinope. Los cínicos sostenían que la virtud y la felicidad se alcanzan viviendo de acuerdo con la naturaleza y rechazando las convenciones sociales.\n\nSu estilo de vida radical incluía la pobreza voluntaria, la mendicidad, la indiferencia ante las normas sociales y la provocación como método pedagógico. El término "cínico" deriva de la palabra griega "kynos" (perro), en referencia a su forma de vida considerada "perruna". Aunque la escuela se extinguió, su actitud de desafío a las convenciones influyó en el estoicismo y en corrientes contraculturales posteriores.`,
    content_en: `Cynicism was a philosophical school of ancient Greece founded by Antisthenes, a disciple of Socrates, and popularized by Diogenes of Sinope. The Cynics held that virtue and happiness are achieved by living according to nature and rejecting social conventions.\n\nTheir radical lifestyle included voluntary poverty, begging, indifference to social norms, and provocation as a pedagogical method. The term "cynic" derives from the Greek word "kynos" (dog), referring to their "dog-like" way of life. Although the school died out, its attitude of defiance toward conventions influenced Stoicism and later countercultural movements.`,
    excerpt_es: 'Escuela filosófica griega que predicaba la vida según la naturaleza y el rechazo de las convenciones.',
    excerpt_en: 'Greek philosophical school that preached living according to nature and rejecting conventions.',
    categoryId: 'cat-philosophical-schools',
    realityStatus: 'philosophical',
    imageUrl: '',
    createdAt: '2026-07-22T00:00:00Z',
    updatedAt: '2026-07-22T00:00:00Z',
  },
  {
    id: 'entry-200-83',
    title_es: 'Escepticismo',
    title_en: 'Skepticism',
    slug: 'escepticismo',
    content_es: `El Escepticismo es una tradición filosófica que cuestiona la posibilidad del conocimiento cierto y aboga por la suspensión del juicio. Su fundador fue Pirrón de Elis, quien sostuvo que no podemos conocer la verdadera naturaleza de las cosas y que la epoché o suspensión del juicio conduce a la ataraxia.\n\nSexto Empírico sistematizó el escepticismo pirrónico en sus "Esbozos Pirrónicos", presentando argumentos contra el dogmatismo. El escepticismo filosófico no es la simple duda cotidiana, sino un método riguroso para examinar las pretensiones de conocimiento. Ha influido en Hume, Kant y la epistemología contemporánea, y sigue siendo una posición filosófica viva.`,
    content_en: `Skepticism is a philosophical tradition that questions the possibility of certain knowledge and advocates for the suspension of judgment. Its founder was Pyrrho of Elis, who held that we cannot know the true nature of things and that epochē or suspension of judgment leads to ataraxia.\n\nSextus Empiricus systematized Pyrrhonian skepticism in his "Outlines of Pyrrhonism," presenting arguments against dogmatism. Philosophical skepticism is not mere everyday doubt but a rigorous method for examining knowledge claims. It has influenced Hume, Kant, and contemporary epistemology, and remains a living philosophical position.`,
    excerpt_es: 'Corriente filosófica que cuestiona la certeza del conocimiento y propone la suspensión del juicio.',
    excerpt_en: 'Philosophical current that questions the certainty of knowledge and proposes suspension of judgment.',
    categoryId: 'cat-philosophical-schools',
    realityStatus: 'philosophical',
    imageUrl: '',
    createdAt: '2026-07-23T00:00:00Z',
    updatedAt: '2026-07-23T00:00:00Z',
  },
  {
    id: 'entry-200-84',
    title_es: 'Empirismo',
    title_en: 'Empiricism',
    slug: 'empirismo',
    content_es: `El Empirismo es una corriente filosófica que sostiene que todo conocimiento humano procede de la experiencia sensible, negando la existencia de ideas innatas. Sus principales representantes fueron John Locke, George Berkeley y David Hume, quienes desarrollaron diferentes versiones de esta teoría del conocimiento.\n\nLocke argumentó que la mente es una tabula rasa al nacer, Berkeley llevó el empirismo al extremo afirmando que "ser es ser percibido", y Hume desarrolló un escepticismo radical basado en la experiencia. El empirismo se opone al racionalismo y ha sido fundamental para el desarrollo de la ciencia moderna, la metodología experimental y la epistemología contemporánea.`,
    content_en: `Empiricism is a philosophical current holding that all human knowledge comes from sensory experience, denying the existence of innate ideas. Its main representatives were John Locke, George Berkeley, and David Hume, who developed different versions of this theory of knowledge.\n\nLocke argued that the mind is a tabula rasa at birth, Berkeley took empiricism to its extreme by claiming that "to be is to be perceived," and Hume developed a radical skepticism based on experience. Empiricism opposes rationalism and has been fundamental to the development of modern science, experimental methodology, and contemporary epistemology.`,
    excerpt_es: 'Corriente filosófica que afirma que todo conocimiento proviene de la experiencia sensible.',
    excerpt_en: 'Philosophical current affirming that all knowledge comes from sensory experience.',
    categoryId: 'cat-philosophical-schools',
    realityStatus: 'philosophical',
    imageUrl: '',
    createdAt: '2026-07-24T00:00:00Z',
    updatedAt: '2026-07-24T00:00:00Z',
  },
  {
    id: 'entry-200-85',
    title_es: 'Racionalismo',
    title_en: 'Rationalism',
    slug: 'racionalismo',
    content_es: `El Racionalismo es una corriente filosófica que sostiene que la razón, y no la experiencia sensible, es la fuente principal del conocimiento verdadero. Sus principales exponentes fueron René Descartes, Baruch Spinoza y Gottfried Leibniz en la Europa continental del siglo XVII.\n\nLos racionalistas defienden la existencia de ideas innatas y la capacidad de la razón para alcanzar verdades universales y necesarias independientemente de la experiencia. Descartes fundó el racionalismo moderno con su duda metódica y el cogito, Spinoza desarrolló un sistema geométrico de la realidad, y Leibniz propuso la teoría de las mónadas. El racionalismo se contrapone al empirismo inglés y su influencia llega hasta Kant y la filosofía contemporánea.`,
    content_en: `Rationalism is a philosophical current holding that reason, not sensory experience, is the main source of true knowledge. Its main exponents were René Descartes, Baruch Spinoza, and Gottfried Leibniz in seventeenth-century continental Europe.\n\nRationalists defend the existence of innate ideas and the capacity of reason to achieve universal and necessary truths independently of experience. Descartes founded modern rationalism with his methodic doubt and the cogito, Spinoza developed a geometric system of reality, and Leibniz proposed the theory of monads. Rationalism contrasts with English empiricism and its influence extends to Kant and contemporary philosophy.`,
    excerpt_es: 'Corriente filosófica que defiende la razón como fuente principal del conocimiento verdadero.',
    excerpt_en: 'Philosophical current defending reason as the main source of true knowledge.',
    categoryId: 'cat-philosophical-schools',
    realityStatus: 'philosophical',
    imageUrl: '',
    createdAt: '2026-07-25T00:00:00Z',
    updatedAt: '2026-07-25T00:00:00Z',
  },
  {
    id: 'entry-200-86',
    title_es: 'Existencialismo',
    title_en: 'Existentialism',
    slug: 'existencialismo',
    content_es: `El Existencialismo es un movimiento filosófico del siglo XX que enfatiza la libertad individual, la responsabilidad personal y la creación de significado en un universo sin propósito inherente. Sus figuras principales incluyen a Jean-Paul Sartre, Simone de Beauvoir, Albert Camus y Karl Jaspers.\n\nLos existencialistas sostienen que "la existencia precede a la esencia": los seres humanos no tienen una naturaleza predeterminada, sino que se definen a través de sus elecciones y acciones. Temas centrales incluyen la angustia, la absurdidad de la vida, la autenticidad frente a la mala fe, y la libertad como condición fundamental. El existencialismo influyó profundamente en la literatura, el arte, la psicoterapia y la teología del siglo XX.`,
    content_en: `Existentialism is a twentieth-century philosophical movement that emphasizes individual freedom, personal responsibility, and the creation of meaning in a universe without inherent purpose. Its main figures include Jean-Paul Sartre, Simone de Beauvoir, Albert Camus, and Karl Jaspers.\n\nExistentialists hold that "existence precedes essence": human beings have no predetermined nature but define themselves through their choices and actions. Central themes include anxiety, the absurdity of life, authenticity versus bad faith, and freedom as a fundamental condition. Existentialism profoundly influenced twentieth-century literature, art, psychotherapy, and theology.`,
    excerpt_es: 'Movimiento filosófico del siglo XX que enfatiza la libertad individual y la creación de significado propio.',
    excerpt_en: 'Twentieth-century philosophical movement emphasizing individual freedom and the creation of one\'s own meaning.',
    categoryId: 'cat-philosophical-schools',
    realityStatus: 'philosophical',
    imageUrl: '',
    createdAt: '2026-07-26T00:00:00Z',
    updatedAt: '2026-07-26T00:00:00Z',
  },
  {
    id: 'entry-200-87',
    title_es: 'Teoría de las Formas de Platón',
    title_en: 'Plato\'s Theory of Forms',
    slug: 'teoria-de-las-formas-de-platon',
    content_es: `La Teoría de las Formas o Ideas de Platón es el núcleo de su filosofía y sostiene que el mundo sensible que percibimos no es la realidad verdadera, sino una copia imperfecta de un mundo inteligible y eterno habitado por las Formas o Ideas perfectas. Estas Formas son las esencias inmutables de todas las cosas.\n\nPlatón ilustró esta teoría con la alegoría de la caverna, donde los prisioneros encadenados solo ven sombras proyectadas en la pared, confundiendo las apariencias con la realidad. El filósofo es quien escapa de la caverna, contempla el mundo real iluminado por el Sol (el Bien) y regresa para liberar a los demás. Esta teoría ha influido en toda la metafísica occidental.`,
    content_en: `Plato's Theory of Forms or Ideas is the core of his philosophy, holding that the sensible world we perceive is not true reality but an imperfect copy of an intelligible and eternal world inhabited by perfect Forms or Ideas. These Forms are the immutable essences of all things.\n\nPlato illustrated this theory with the allegory of the cave, where chained prisoners see only shadows projected on the wall, mistaking appearances for reality. The philosopher is one who escapes the cave, contemplates the real world illuminated by the Sun (the Good), and returns to free others. This theory has influenced all of Western metaphysics.`,
    excerpt_es: 'Doctrina platónica que distingue entre el mundo sensible de apariencias y el mundo inteligible de las Ideas perfectas.',
    excerpt_en: 'Platonic doctrine distinguishing the sensible world of appearances from the intelligible world of perfect Ideas.',
    categoryId: 'cat-philosophical-concepts',
    realityStatus: 'philosophical',
    imageUrl: '',
    createdAt: '2026-07-27T00:00:00Z',
    updatedAt: '2026-07-27T00:00:00Z',
  },
  {
    id: 'entry-200-88',
    title_es: 'El Barco de Teseo',
    title_en: 'The Ship of Theseus',
    slug: 'el-barco-de-teseo',
    content_es: `El Barco de Teseo es un famoso problema de identidad planteado por Plutarco: si una nave es reemplazada pieza por pieza a lo largo del tiempo, ¿sigue siendo el mismo barco? Y si las piezas originales se reensamblan, ¿cuál de las dos naves es la verdadera?\n\nEsta paradoja explora cuestiones filosóficas fundamentales sobre la persistencia de la identidad a través del cambio. Se aplica a debates sobre la identidad personal (¿somos la misma persona a lo largo de la vida?), la identidad de los objetos y la continuidad de las entidades biológicas. En la actualidad, el problema se discute en relación con el reemplazo de células en el cuerpo humano y la identidad de las personas.`,
    content_en: `The Ship of Theseus is a famous identity problem posed by Plutarch: if a ship has all its parts replaced one by one over time, is it still the same ship? And if the original parts are reassembled, which of the two ships is the true one?\n\nThis paradox explores fundamental philosophical questions about the persistence of identity through change. It applies to debates on personal identity (are we the same person throughout life?), the identity of objects, and the continuity of biological entities. Today, the problem is discussed in relation to cell replacement in the human body and personal identity.`,
    excerpt_es: 'Paradoja filosófica sobre la identidad que pregunta si un objeto sigue siendo el mismo tras reemplazar todas sus partes.',
    excerpt_en: 'Philosophical paradox about identity asking whether an object remains the same after all its parts are replaced.',
    categoryId: 'cat-philosophical-concepts',
    realityStatus: 'philosophical',
    imageUrl: '',
    createdAt: '2026-07-28T00:00:00Z',
    updatedAt: '2026-07-28T00:00:00Z',
  },
  {
    id: 'entry-200-89',
    title_es: 'Navaja de Occam',
    title_en: 'Occam\'s Razor',
    slug: 'navaja-de-occam',
    content_es: `La Navaja de Occam es un principio metodológico atribuido al filósofo medieval Guillermo de Occam que sostiene que "no deben multiplicarse los entes sin necesidad". En otras palabras, ante dos explicaciones competidoras, la más simple suele ser la correcta.\n\nEste principio no es una ley lógica ni una verdad demostrable, sino una heurística que guía la elección entre teorías rivales. Se utiliza ampliamente en ciencia, medicina y filosofía para favorecer hipótesis que requieren menos supuestos. Sin embargo, la simplicidad no garantiza la verdad, y la historia de la ciencia muestra casos donde la explicación más compleja resultó ser la correcta.`,
    content_en: `Occam\'s Razor is a methodological principle attributed to the medieval philosopher William of Ockham, holding that "entities must not be multiplied beyond necessity." In other words, when faced with competing explanations, the simplest one is usually correct.\n\nThis principle is not a logical law or demonstrable truth, but a heuristic guiding choice between rival theories. It is widely used in science, medicine, and philosophy to favor hypotheses requiring fewer assumptions. However, simplicity does not guarantee truth, and the history of science shows cases where the more complex explanation turned out to be correct.`,
    excerpt_es: 'Principio metodológico que favorece la explicación más simple entre hipótesis competidoras.',
    excerpt_en: 'Methodological principle favoring the simplest explanation among competing hypotheses.',
    categoryId: 'cat-philosophical-concepts',
    realityStatus: 'philosophical',
    imageUrl: '',
    createdAt: '2026-07-29T00:00:00Z',
    updatedAt: '2026-07-29T00:00:00Z',
  },
  {
    id: 'entry-200-90',
    title_es: 'Isaac Newton',
    title_en: 'Isaac Newton',
    slug: 'isaac-newton',
    content_es: `Isaac Newton fue un físico, matemático, astrónomo y alquimista inglés, considerado uno de los científicos más influyentes de la historia. Su obra "Philosophiæ Naturalis Principia Mathematica" estableció las leyes del movimiento y la ley de la gravitación universal, sentando las bases de la física clásica.\n\nNewton desarrolló simultáneamente el cálculo infinitesimal con Leibniz, realizó descubrimientos fundamentales en óptica sobre la composición de la luz blanca y construyó el primer telescopio reflector. Su síntesis de la física terrestre y celeste en un sistema unificado de leyes naturales dominó la ciencia durante más de dos siglos hasta la llegada de la relatividad y la mecánica cuántica.`,
    content_en: `Isaac Newton was an English physicist, mathematician, astronomer, and alchemist, considered one of the most influential scientists in history. His work "Philosophiæ Naturalis Principia Mathematica" established the laws of motion and the law of universal gravitation, laying the foundations of classical physics.\n\nNewton simultaneously developed calculus with Leibniz, made fundamental discoveries in optics about the composition of white light, and built the first reflecting telescope. His synthesis of terrestrial and celestial physics into a unified system of natural laws dominated science for over two centuries until the arrival of relativity and quantum mechanics.`,
    excerpt_es: 'Físico y matemático inglés que formuló las leyes del movimiento y la gravitación universal.',
    excerpt_en: 'English physicist and mathematician who formulated the laws of motion and universal gravitation.',
    categoryId: 'cat-scientists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-30T00:00:00Z',
    updatedAt: '2026-07-30T00:00:00Z',
  },
  {
    id: 'entry-200-91',
    title_es: 'Marie Curie',
    title_en: 'Marie Curie',
    slug: 'marie-curie',
    content_es: `Marie Curie fue una física y química polaco-francesa pionera en el estudio de la radioactividad. Descubrió los elementos polonio y radio, y fue la primera persona en recibir dos premios Nobel en distintas disciplinas científicas: Física en 1903 y Química en 1911.\n\nCurie desarrolló la teoría de la radioactividad, acuñó el término y estableció métodos para el aislamiento de isótopos radiactivos. Durante la Primera Guerra Mundial, organizó unidades móviles de rayos X para la atención de soldados heridos. Su trabajo sentó las bases para la física nuclear y la radioterapia, aunque la exposición prolongada a la radiación le causó una anemia aplásica que finalmente le costó la vida.`,
    content_en: `Marie Curie was a Polish-French physicist and chemist pioneer in the study of radioactivity. She discovered the elements polonium and radium, and was the first person to receive two Nobel Prizes in different scientific disciplines: Physics in 1903 and Chemistry in 1911.\n\nCurie developed the theory of radioactivity, coined the term, and established methods for isolating radioactive isotopes. During World War I, she organized mobile X-ray units for treating wounded soldiers. Her work laid the foundations for nuclear physics and radiotherapy, though prolonged exposure to radiation caused aplastic anemia that ultimately cost her life.`,
    excerpt_es: 'Pionera de la radioactividad, descubridora del polonio y el radio, y doble premio Nobel.',
    excerpt_en: 'Pioneer of radioactivity, discoverer of polonium and radium, and double Nobel laureate.',
    categoryId: 'cat-scientists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-31T00:00:00Z',
    updatedAt: '2026-07-31T00:00:00Z',
  },
  {
    id: 'entry-200-92',
    title_es: 'Nikola Tesla',
    title_en: 'Nikola Tesla',
    slug: 'nikola-tesla',
    content_es: `Nikola Tesla fue un inventor, ingeniero eléctrico y mecánico serbio-estadounidense, conocido por sus contribuciones revolucionarias al diseño del sistema de corriente alterna. Sus invenciones transformaron la generación, transmisión y uso de la electricidad a nivel mundial.\n\nTesla desarrolló la bobina de Tesla, el motor de inducción y sistemas de transmisión inalámbrica de energía. Visionario incomprendido, propuso la transmisión global de energía sin cables y la comunicación interestelar. Su rivalidad con Thomas Edison, la "Guerra de las Corrientes", y su estilo excéntrico lo convirtieron en una figura legendaria. Muchas de sus ideas más ambiciosas, como la energía gratuita para todos, nunca se realizaron plenamente.`,
    content_en: `Nikola Tesla was a Serbian-American inventor, electrical and mechanical engineer, known for his revolutionary contributions to the design of the alternating current system. His inventions transformed the generation, transmission, and use of electricity worldwide.\n\nTesla developed the Tesla coil, the induction motor, and wireless energy transmission systems. A misunderstood visionary, he proposed global wireless energy transmission and interstellar communication. His rivalry with Thomas Edison, the "War of Currents," and his eccentric style made him a legendary figure. Many of his most ambitious ideas, such as free energy for all, were never fully realized.`,
    excerpt_es: 'Inventor visionario que revolucionó la electricidad con el sistema de corriente alterna.',
    excerpt_en: 'Visionary inventor who revolutionized electricity with the alternating current system.',
    categoryId: 'cat-scientists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'entry-200-93',
    title_es: 'Charles Darwin',
    title_en: 'Charles Darwin',
    slug: 'charles-darwin',
    content_es: `Charles Darwin fue un naturalista inglés cuyas observaciones durante el viaje del HMS Beagle lo llevaron a formular la teoría de la evolución por selección natural. Su obra "El origen de las especies" revolucionó la biología y transformó nuestra comprensión de la vida en la Tierra.\n\nDarwin dedicó más de veinte años a recopilar evidencia antes de publicar su teoría, consciente de la controversia que generaría. Su meticuloso trabajo incluyó estudios sobre pinzones en las Galápagos, fósiles sudamericanos y la cría selectiva de palomas. Hombre reservado y metódico, Darwin pasó sus últimos años en Down House, donde continuó investigando temas como las lombrices de tierra y la expresión de las emociones en animales y humanos.`,
    content_en: `Charles Darwin was an English naturalist whose observations during the voyage of the HMS Beagle led him to formulate the theory of evolution by natural selection. His work "On the Origin of Species" revolutionized biology and transformed our understanding of life on Earth.\n\nDarwin spent over twenty years gathering evidence before publishing his theory, aware of the controversy it would generate. His meticulous work included studies of finches in the Galapagos, South American fossils, and the selective breeding of pigeons. A reserved and methodical man, Darwin spent his later years at Down House, where he continued researching topics such as earthworms and the expression of emotions in animals and humans.`,
    excerpt_es: 'Naturalista inglés que formuló la teoría de la evolución por selección natural tras años de investigación.',
    excerpt_en: 'English naturalist who formulated the theory of evolution by natural selection after years of research.',
    categoryId: 'cat-scientists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-08-02T00:00:00Z',
    updatedAt: '2026-08-02T00:00:00Z',
  },
  {
    id: 'entry-200-94',
    title_es: 'Albert Einstein',
    title_en: 'Albert Einstein',
    slug: 'albert-einstein',
    content_es: `Albert Einstein fue un físico teórico alemán, considerado el científico más emblemático del siglo XX. Su teoría de la relatividad especial y general transformó nuestra comprensión del espacio, el tiempo, la materia y la energía, reemplazando la física newtoniana como marco fundamental del universo.\n\nEinstein propuso la ecuación más famosa de la historia, E=mc², que establece la equivalencia entre masa y energía. Su explicación del efecto fotoeléctrico le valió el Premio Nobel de Física en 1921 y contribuyó al desarrollo de la mecánica cuántica, aunque nunca aceptó la interpretación probabilística de esta. Pacifista comprometido, se exilió a Estados Unidos tras la llegada de Hitler al poder y advirtió del peligro de la bomba atómica, firmando la famosa carta a Roosevelt.`,
    content_en: `Albert Einstein was a German theoretical physicist, considered the most iconic scientist of the twentieth century. His special and general theories of relativity transformed our understanding of space, time, matter, and energy, replacing Newtonian physics as the fundamental framework of the universe.\n\nEinstein proposed the most famous equation in history, E=mc², establishing the equivalence between mass and energy. His explanation of the photoelectric effect earned him the Nobel Prize in Physics in 1921 and contributed to the development of quantum mechanics, though he never accepted its probabilistic interpretation. A committed pacifist, he exiled to the United States after Hitler's rise to power and warned of the atomic bomb's danger, signing the famous letter to Roosevelt.`,
    excerpt_es: 'Físico teórico que revolucionó la ciencia con sus teorías de la relatividad y la ecuación E=mc².',
    excerpt_en: 'Theoretical physicist who revolutionized science with his theories of relativity and the equation E=mc².',
    categoryId: 'cat-scientists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-08-03T00:00:00Z',
    updatedAt: '2026-08-03T00:00:00Z',
  },
  {
    id: 'entry-200-95',
    title_es: 'Galileo Galilei',
    title_en: 'Galileo Galilei',
    slug: 'galileo-galilei',
    content_es: `Galileo Galilei fue un astrónomo, físico e ingeniero italiano, considerado el padre de la ciencia moderna. Sus observaciones astronómicas con el telescopio, incluyendo las lunas de Júpiter, las fases de Venus y las manchas solares, proporcionaron evidencia crucial a favor del modelo heliocéntrico de Copérnico.\n\nGalileo estableció el método científico basado en la experimentación y la matematización de la naturaleza. Su conflicto con la Iglesia Católica, que lo obligó a retractarse de sus afirmaciones heliocéntricas, se ha convertido en un símbolo de la tensión entre ciencia y autoridad religiosa. Su obra "Diálogo sobre los dos máximos sistemas del mundo" es una obra maestra de la literatura científica y la defensa de la libertad de pensamiento.`,
    content_en: `Galileo Galilei was an Italian astronomer, physicist, and engineer, considered the father of modern science. His astronomical observations with the telescope, including Jupiter's moons, Venus's phases, and sunspots, provided crucial evidence for Copernicus's heliocentric model.\n\nGalileo established the scientific method based on experimentation and the mathematization of nature. His conflict with the Catholic Church, which forced him to recant his heliocentric claims, has become a symbol of the tension between science and religious authority. His work "Dialogue Concerning the Two Chief World Systems" is a masterpiece of scientific literature and a defense of freedom of thought.`,
    excerpt_es: 'Astrónomo y físico italiano, padre de la ciencia moderna, que defendió el modelo heliocéntrico.',
    excerpt_en: 'Italian astronomer and physicist, father of modern science, who defended the heliocentric model.',
    categoryId: 'cat-scientists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-08-04T00:00:00Z',
    updatedAt: '2026-08-04T00:00:00Z',
  },
]
