import { SeedEntry } from '../seed'

export const domain10Entries: SeedEntry[] = [
  // --- Rulers ---
  {
    id: 'entry-alexander-great',
    title_es: 'Alejandro Magno',
    title_en: 'Alexander the Great',
    slug: 'alejandro-magno',
    content_es: `Alejandro III de Macedonia, conocido como Alejandro Magno (356-323 a.C.), fue uno de los conquistadores más extraordinarios de la historia. En solo trece años creó un imperio desde Grecia hasta la India, uniendo Oriente y Occidente como nunca antes. Su legado cultural, el Helenismo, transformó el mundo antiguo.\n\nHijo del rey Filipo II y Olimpia de Epiro, fue educado por Aristóteles, quien le inculcó el amor por la literatura homérica, la filosofía y las ciencias. Desde joven demostró audacia y ambición desmedida, domando al caballo Bucéfalo cuando nadie más podía.\n\nA los veinte años, tras el asesinato de su padre, heredó un reino fortalecido y un ejército veterano. Inició su campaña contra el Imperio Persa en el 334 a.C., derrotando a Darío III en Issos (333 a.C.) y Gaugamela (331 a.C.), conquistando Egipto, donde fundó Alejandría, y todo el Imperio Persa.\n\nContinuó hasta el Indo y el Punjab. En el 326 a.C., sus tropas exhaustas se negaron a seguir. Alejandro accedió a regresar, muriendo en Babilonia en el 323 a.C. a los 32 años. Su imperio se fragmentó entre sus generales (los diádocos).\n\nAlejandro fundó más de veinte ciudades con su nombre y promovió la fusión cultural greco-persa. Su figura mitificada como genio militar y ambición sin límites ha inspirado a líderes desde César hasta Napoleón.`,
    content_en: `Alexander III of Macedon, known as Alexander the Great (356-323 BC), was one of the most extraordinary conquerors in history. In just thirteen years he created an empire from Greece to India, uniting East and West as never before. His cultural legacy, Hellenism, transformed the ancient world.\n\nSon of King Philip II and Olympias of Epirus, he was educated by Aristotle, who instilled in him a love for Homeric literature, philosophy, and sciences. From a young age he demonstrated audacity and immense ambition, taming the horse Bucephalus when no one else could.\n\nAt twenty, after his father's assassination, he inherited a strengthened kingdom and veteran army. He began his campaign against Persia in 334 BC, defeating Darius III at Issus (333 BC) and Gaugamela (331 BC), conquering Egypt, where he founded Alexandria, and the entire Persian Empire.\n\nHe continued to the Indus and Punjab. In 326 BC, his exhausted troops refused to advance further. Alexander agreed to return, dying in Babylon in 323 BC at age 32. His empire fragmented among his generals (the Diadochi).\n\nAlexander founded over twenty cities bearing his name and promoted Greco-Persian cultural fusion. His mythologized figure as military genius and boundless ambition has inspired leaders from Caesar to Napoleon.`,
    excerpt_es: 'El mayor conquistador de la antigüedad, que creó un imperio desde Grecia hasta la India.',
    excerpt_en: 'The greatest conqueror of antiquity, who created an empire from Greece to India.',
    categoryId: 'cat-figures-rulers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-17T00:00:00Z',
    updatedAt: '2026-04-17T00:00:00Z',
  },
  {
    id: 'entry-julius-caesar',
    title_es: 'Julio César',
    title_en: 'Julius Caesar',
    slug: 'julio-cesar',
    content_es: `Cayo Julio César (100-44 a.C.) fue un líder militar, político y escritor romano cuya vida marcó un punto de inflexión en la historia de Roma, acelerando la transición de la República al Imperio. Su genio militar, ambición política y trágico asesinato lo han convertido en una de las figuras más famosas de la historia occidental.\n\nNació en la gens Julia, una familia patricia. Desde joven se distinguió por su inteligencia y ambición, formando parte del Primer Triunvirato con Pompeyo y Craso en el 60 a.C. Sus campañas en la Guerra de las Galias (58-50 a.C.) lo consolidaron como gran estratega, conquistando toda la Galia y realizando expediciones a Britania.\n\nEl cruce del Rubicón en el 49 a.C. —"Alea iacta est"— desencadenó una guerra civil contra Pompeyo. Tras derrotarlo en Farsalia (48 a.C.), se convirtió en dictador vitalicio, implementando reformas como el calendario juliano y la extensión de la ciudadanía romana.\n\nFue asesinado el 15 de marzo (Idus de Marzo) del 44 a.C. por senadores liderados por Bruto y Casio, que temían su creciente poder. Su muerte desencadenó otra guerra civil que culminó con el ascenso de Augusto como primer emperador.\n\nCésar no solo fue un genio militar sino también un escritor excepcional. Sus "Comentarios" son obras maestras de la literatura latina y la propaganda política. Su nombre se convirtió en título imperial: "César" (Káiser, Zar).`,
    content_en: `Gaius Julius Caesar (100-44 BC) was a Roman military leader, politician, and writer whose life marked a turning point in Roman history, accelerating the transition from Republic to Empire. His military genius, political ambition, and tragic assassination have made him one of the most famous figures in Western history.\n\nBorn into the gens Julia, a patrician family, he distinguished himself early through intelligence and ambition, forming the First Triumvirate with Pompey and Crassus in 60 BC. His campaigns in the Gallic Wars (58-50 BC) established him as a great strategist, conquering all of Gaul and making expeditions to Britain.\n\nThe crossing of the Rubicon in 49 BC — "Alea iacta est" — triggered a civil war against Pompey. After defeating him at Pharsalus (48 BC), he became dictator for life, implementing reforms such as the Julian calendar and extension of Roman citizenship.\n\nHe was assassinated on March 15 (Ides of March), 44 BC, by senators led by Brutus and Cassius who feared his growing power. His death triggered another civil war culminating in Augustus's rise as first emperor.\n\nCaesar was not only a military genius but also an exceptional writer. His "Commentaries" are masterpieces of Latin literature and political propaganda. His name became an imperial title: "Caesar" (Kaiser, Tsar).`,
    excerpt_es: 'Líder romano cuyo cruce del Rubicón cambió la historia, asesinado en los Idus de Marzo.',
    excerpt_en: 'Roman leader whose crossing of the Rubicon changed history, assassinated on the Ides of March.',
    categoryId: 'cat-figures-rulers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-18T00:00:00Z',
    updatedAt: '2026-04-18T00:00:00Z',
  },
  {
    id: 'entry-genghis-khan',
    title_es: 'Gengis Kan',
    title_en: 'Genghis Khan',
    slug: 'gengis-kan',
    content_es: `Gengis Kan (c. 1162-1227), nacido como Temuyín, fue el fundador y primer Gran Kan del Imperio Mongol, el imperio contiguo más extenso de la historia. Desde las estepas de Asia Central, unificó a las tribus mongolas y creó un imperio desde el Pacífico hasta el Caspio.\n\nSu infancia fue extraordinariamente dura. Tras el envenenamiento de su padre, su familia fue abandonada y vivió en pobreza extrema. Temuyín mató a su medio hermano por disputas de liderazgo y fue esclavizado, pero escapó. Estas experiencias forjaron su carácter implacable.\n\nMediante destreza militar, diplomacia y alianzas, unificó a las tribus en 1206, adoptando el título de Gengis Kan ("Gobernante Universal"). Implementó el Yassa (código legal), abolió distinciones tribales y creó un ejército disciplinado en unidades decimales.\n\nSus campañas conquistaron el norte de China, Asia Central, Persia y partes de Rusia. Los mongoles, jinetes excepcionales, recorrían 100 km diarios, combinando arqueros montados, terror psicológico y adaptabilidad táctica.\n\nMurió en 1227 durante una campaña. Su imperio se dividió entre sus hijos, continuando la expansión. Su legado es controvertido: responsable de millones de muertes pero también facilitador del comercio y el intercambio cultural en la Ruta de la Seda.`,
    content_en: `Genghis Khan (c. 1162-1227), born Temüjin, was the founder and first Great Khan of the Mongol Empire, the largest contiguous empire in history. From the Central Asian steppes, he united the Mongol tribes and created an empire from the Pacific to the Caspian.\n\nHis childhood was extraordinarily harsh. After his father's poisoning, his family was abandoned and lived in extreme poverty. Temüjin killed his half-brother over leadership disputes and was enslaved but escaped. These experiences forged his relentless character.\n\nThrough military skill, diplomacy, and alliances, he united the tribes in 1206, adopting the title Genghis Khan ("Universal Ruler"). He implemented the Yassa (legal code), abolished tribal distinctions, and created a disciplined army in decimal units.\n\nHis campaigns conquered northern China, Central Asia, Persia, and parts of Russia. The Mongols, exceptional horsemen, covered 100 km daily, combining mounted archers, psychological terror, and tactical adaptability.\n\nHe died in 1227 during a campaign. His empire was divided among his sons, continuing expansion. His legacy is controversial: responsible for millions of deaths but also facilitating trade and cultural exchange along the Silk Road.`,
    excerpt_es: 'Fundador del Imperio Mongol, el imperio contiguo más extenso de la historia.',
    excerpt_en: 'Founder of the Mongol Empire, the largest contiguous empire in history.',
    categoryId: 'cat-figures-rulers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-19T00:00:00Z',
    updatedAt: '2026-04-19T00:00:00Z',
  },
  {
    id: 'entry-cleopatra',
    title_es: 'Cleopatra',
    title_en: 'Cleopatra',
    slug: 'cleopatra',
    content_es: `Cleopatra VII Filopator (69-30 a.C.) fue la última gobernante activa de la dinastía ptolemaica de Egipto. Famosa por su inteligencia, carisma y habilidad diplomática, fue una de las mujeres más poderosas de la antigüedad. Su vida, entrelazada con César y Marco Antonio, marcó el fin del Egipto helenístico.\n\nDe ascendencia griega macedonia, fue la primera de su dinastía en aprender egipcio y adoptar costumbres locales, presentándose como reencarnación de la diosa Isis. Hablaba nueve idiomas y era hábil diplomática y administradora.\n\nAscendió al trono a los 18 años con su hermano Ptolomeo XIII, pero fue exiliada. Buscó el apoyo de Julio César, quien quedó cautivado por su encanto. Fue su amante y madre de Cesarión. Tras el asesinato de César, se alió con Marco Antonio.\n\nSu relación con Antonio fue política y personal. Antonio le concedió territorios romanos, provocando la guerra con Octavio. Tras la derrota en Actium (31 a.C.), Antonio se suicidó y Cleopatra, al no poder negociar con Octavio, se suicidó poco después.\n\nSu muerte, atribuida al veneno de un áspid, selló el fin del Egipto independiente. Cleopatra ha sido reinterpretada como símbolo de belleza, astucia política y trágica heroína romántica. Su imagen popular, aunque a menudo inexacta, perdura en el arte y el cine.`,
    content_en: `Cleopatra VII Philopator (69-30 BC) was the last active ruler of the Ptolemaic dynasty of Egypt. Famous for her intelligence, charisma, and diplomatic skill, she was one of the most powerful women of antiquity. Her life, intertwined with Caesar and Mark Antony, marked the end of Hellenistic Egypt.\n\nOf Macedonian Greek descent, she was the first of her dynasty to learn Egyptian and adopt local customs, presenting herself as reincarnation of the goddess Isis. She spoke nine languages and was a skilled diplomat and administrator.\n\nShe ascended the throne at 18 with her brother Ptolemy XIII, but was exiled. She sought support from Julius Caesar, who was captivated by her charm. She became his lover and mother of Caesarion. After Caesar's assassination, she allied with Mark Antony.\n\nHer relationship with Antony was both political and personal. Antony granted her Roman territories, provoking war with Octavian. After defeat at Actium (31 BC), Antony committed suicide, and Cleopatra, unable to negotiate with Octavian, died shortly after.\n\nHer death, attributed to an asp's venom, sealed the end of independent Egypt. Cleopatra has been reinterpreted as a symbol of beauty, political cunning, and tragic romantic heroine. Her popular image, though often inaccurate, endures in art and film.`,
    excerpt_es: 'La última reina de Egipto, famosa por sus alianzas con César y Marco Antonio.',
    excerpt_en: "The last queen of Egypt, famous for her alliances with Caesar and Mark Antony.",
    categoryId: 'cat-figures-rulers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-20T00:00:00Z',
    updatedAt: '2026-04-20T00:00:00Z',
  },

  // --- Scientists ---
  {
    id: 'entry-tesla',
    title_es: 'Nikola Tesla',
    title_en: 'Nikola Tesla',
    slug: 'nikola-tesla',
    content_es: `Nikola Tesla (1856-1943) fue un inventor serbo-estadounidense cuyas contribuciones a la corriente alterna (CA) transformaron el mundo moderno. Su genio visionario, personalidad excéntrica y trágica relación con Edison lo han convertido en figura mítica de la ciencia.\n\nEmigró a EE.UU. en 1884 y trabajó brevemente para Edison, pero surgió una rivalidad: Edison defendía la corriente continua (CC), Tesla la alterna (CA). La "Guerra de las Corrientes" culminó con la victoria de Tesla, cuya CA permitía transmitir electricidad a largas distancias eficientemente.\n\nPatentó el motor de inducción de CA, la bobina de Tesla y el sistema polifásico. Sus patentes fueron vendidas a Westinghouse, quien las usó para iluminar la Exposición de Chicago de 1893 y la central hidroeléctrica del Niágara.\n\nEntre sus inventos visionarios: la radio (aunque Marconi recibió el crédito), el control remoto, las lámparas fluorescentes y la transmisión inalámbrica de energía. También afirmó haber desarrollado un "rayo de la muerte".\n\nMurió solo en una habitación de hotel en Nueva York en 1943. Su legado ha resurgido como icono del genio incomprendido. Teorías conspirativas afirman que sus inventos revolucionarios fueron suprimidos por intereses corporativos.`,
    content_en: `Nikola Tesla (1856-1943) was a Serbian-American inventor whose contributions to alternating current (AC) transformed the modern world. His visionary genius, eccentric personality, and tragic relationship with Edison have made him a mythical figure in science.\n\nHe emigrated to the US in 1884 and briefly worked for Edison, but a rivalry emerged: Edison championed direct current (DC), Tesla alternating current (AC). The "War of the Currents" culminated in Tesla's victory, as AC allowed efficient long-distance electricity transmission.\n\nHe patented the AC induction motor, the Tesla coil, and the polyphase system. He sold patents to Westinghouse, who used them to light the 1893 Chicago Exposition and the Niagara Falls hydroelectric plant.\n\nAmong his visionary inventions: radio (though Marconi received credit), remote control, fluorescent lamps, and wireless energy transmission. He also claimed to have developed a "death ray."\n\nHe died alone in a New York hotel room in 1943. His legacy has resurged as an icon of the misunderstood genius. Conspiracy theories claim his revolutionary inventions were suppressed by corporate interests.`,
    excerpt_es: 'Inventor de la corriente alterna, cuya rivalidad con Edison alimenta leyendas conspirativas.',
    excerpt_en: 'Inventor of alternating current, whose rivalry with Edison fuels conspiratorial legends.',
    categoryId: 'cat-figures-scientists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-21T00:00:00Z',
    updatedAt: '2026-04-21T00:00:00Z',
  },
  {
    id: 'entry-curie',
    title_es: 'Marie Curie',
    title_en: 'Marie Curie',
    slug: 'marie-curie',
    content_es: `Marie Curie (1867-1934) fue una física y química polaco-francesa, pionera de la radiactividad. Primera mujer en ganar un Nobel, primera persona en ganar dos Nobel en distintas disciplinas (Física 1903, Química 1911). Su trabajo sentó las bases de la física nuclear y la radioterapia.\n\nNacida Maria Skłodowska en Varsovia, no pudo acceder a la educación superior en Polonia por su género. Trabajó como institutriz para financiar sus estudios y en 1891 se trasladó a París para estudiar en la Sorbona.\n\nConoció a Pierre Curie, con quien se casó en 1895. Trabajando en condiciones precarias, descubrieron el polonio y el radio, acuñando el término "radiactividad". En 1903 ganaron el Nobel de Física con Becquerel.\n\nTras la muerte de Pierre en 1906, Marie asumió su cátedra en la Sorbona, primera mujer profesora allí. Durante la Primera Guerra Mundial, desarrolló unidades móviles de rayos X ("petites Curies") para cirujanos en el frente.\n\nMurió en 1934 de anemia aplásica por exposición prolongada a la radiación. Sus cuadernos siguen siendo radiactivos y se conservan en cajas forradas de plomo en la Biblioteca Nacional de Francia.`,
    content_en: `Marie Curie (1867-1934) was a Polish-French physicist and chemist, pioneer of radioactivity. First woman to win a Nobel, first person to win two Nobels in different disciplines (Physics 1903, Chemistry 1911). Her work laid foundations of nuclear physics and radiotherapy.\n\nBorn Maria Skłodowska in Warsaw, she could not access higher education in Poland due to her gender. She worked as a governess to fund her studies and in 1891 moved to Paris to study at the Sorbonne.\n\nShe met Pierre Curie, marrying him in 1895. Working in precarious conditions, they discovered polonium and radium, coining the term "radioactivity." In 1903 they won the Nobel Prize in Physics with Becquerel.\n\nAfter Pierre's death in 1906, Marie took his professorship at the Sorbonne, first woman professor there. During WWI, she developed mobile X-ray units ("petites Curies") for battlefield surgeons.\n\nShe died in 1934 of aplastic anemia from prolonged radiation exposure. Her notebooks remain radioactive, kept in lead-lined boxes at the National Library of France.`,
    excerpt_es: 'Pionera de la radiactividad, primera persona en ganar dos Premios Nobel en distintas ciencias.',
    excerpt_en: 'Pioneer of radioactivity, first person to win two Nobel Prizes in different sciences.',
    categoryId: 'cat-figures-scientists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-22T00:00:00Z',
    updatedAt: '2026-04-22T00:00:00Z',
  },
  {
    id: 'entry-newton',
    title_es: 'Isaac Newton',
    title_en: 'Isaac Newton',
    slug: 'isaac-newton',
    content_es: `Sir Isaac Newton (1642-1727) fue un matemático, físico, astrónomo y alquimista inglés, considerado uno de los científicos más influyentes de todos los tiempos. Sus "Principia Mathematica" (1687) establecieron las bases de la mecánica clásica.\n\nNacido en Woolsthorpe, fue un niño prematuro y enfermizo. Su madre lo retiró de la escuela para trabajar, pero un tío reconoció su talento y lo envió a Cambridge. Durante la peste de 1665-66, realizó sus descubrimientos más revolucionarios.\n\nSu "annus mirabilis" (1666) incluyó el desarrollo del cálculo infinitesimal, la ley de gravitación universal, experimentos sobre la luz demostrando que la luz blanca se compone de colores del espectro, y las tres leyes del movimiento.\n\nNewton dedicó enorme tiempo a la alquimia y la teología, escribiendo más sobre interpretación bíblica que sobre física. Calculaba la fecha de la crucifixión y buscaba significados ocultos en las escrituras, actividades integrales de su cosmovisión.\n\nSu método científico —observación, matematización y verificación experimental— definió el paradigma de la ciencia moderna. Falleció en 1727 y fue enterrado en la Abadía de Westminster. Sus leyes gobernaron la física hasta la relatividad y la mecánica cuántica.`,
    content_en: `Sir Isaac Newton (1642-1727) was an English mathematician, physicist, astronomer, and alchemist, considered one of the most influential scientists of all time. His "Principia Mathematica" (1687) established the foundations of classical mechanics.\n\nBorn in Woolsthorpe, he was a premature and sickly child. His mother withdrew him from school to work, but an uncle recognized his talent and sent him to Cambridge. During the 1665-66 plague, he made his most revolutionary discoveries.\n\nHis "annus mirabilis" (1666) included developing calculus, the law of universal gravitation, experiments on light showing white light comprises spectral colors, and the three laws of motion.\n\nNewton devoted enormous time to alchemy and theology, writing more on biblical interpretation than physics. He calculated the crucifixion date and sought hidden meanings in scripture, activities integral to his worldview.\n\nHis scientific method — observation, mathematization, experimental verification — defined the paradigm of modern science. He died in 1727 and was buried in Westminster Abbey. His laws governed physics until relativity and quantum mechanics.`,
    excerpt_es: 'Genio de la física y las matemáticas, formuló la gravitación universal y sentó las bases de la ciencia moderna.',
    excerpt_en: 'Genius of physics and mathematics, formulated universal gravitation and laid foundations of modern science.',
    categoryId: 'cat-figures-scientists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-23T00:00:00Z',
    updatedAt: '2026-04-23T00:00:00Z',
  },
  {
    id: 'entry-turing',
    title_es: 'Alan Turing',
    title_en: 'Alan Turing',
    slug: 'alan-turing',
    content_es: `Alan Mathison Turing (1912-1954) fue un matemático, lógico, criptógrafo y pionero de la informática británico, padre de la inteligencia artificial y la computación teórica. Su vida, marcada por un genio extraordinario y un trágico final, es símbolo de la lucha contra la homofobia.\n\nEstudió en Cambridge y Princeton. En 1936, a los 24 años, publicó "On Computable Numbers", introduciendo la "Máquina de Turing", modelo abstracto que define los límites fundamentales de la computación.\n\nDurante la Segunda Guerra Mundial trabajó en Bletchley Park descifrando la máquina Enigma alemana. Lideró el desarrollo de la Bombe, máquina electromecánica que acortó la guerra en al menos dos años y salvó millones de vidas.\n\nTras la guerra, contribuyó al desarrollo de las primeras computadoras electrónicas. En 1950 publicó "Computing Machinery and Intelligence", proponiendo el "Test de Turing" para determinar si una máquina puede pensar.\n\nEn 1952 fue procesado por homosexualidad, ilegal en el Reino Unido. Condenado a castración química, murió en 1954 por envenenamiento con cianuro. En 2009 recibió disculpa oficial del gobierno británico y en 2013 un indulto real póstumo.`,
    content_en: `Alan Mathison Turing (1912-1954) was a British mathematician, logician, cryptographer, and computer science pioneer, father of artificial intelligence and theoretical computing. His life, marked by extraordinary genius and a tragic end, is a symbol of the fight against homophobia.\n\nHe studied at Cambridge and Princeton. In 1936, at 24, he published "On Computable Numbers," introducing the "Turing Machine," an abstract model defining the fundamental limits of computation.\n\nDuring WWII he worked at Bletchley Park cracking the German Enigma machine. He led development of the Bombe, an electromechanical machine that shortened the war by at least two years and saved millions of lives.\n\nAfter the war, he contributed to early electronic computers. In 1950 he published "Computing Machinery and Intelligence," proposing the "Turing Test" to determine whether a machine can think.\n\nIn 1952 he was prosecuted for homosexuality, illegal in the UK. Sentenced to chemical castration, he died in 1954 from cyanide poisoning. In 2009 the British government issued an official apology, and in 2013 he received a posthumous royal pardon.`,
    excerpt_es: 'Padre de la computación teórica, descifró la máquina Enigma y fue condenado por su homosexualidad.',
    excerpt_en: 'Father of theoretical computing, cracked the Enigma machine, and was condemned for his homosexuality.',
    categoryId: 'cat-figures-scientists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-24T00:00:00Z',
    updatedAt: '2026-04-24T00:00:00Z',
  },

  // --- Explorers ---
  {
    id: 'entry-columbus',
    title_es: 'Cristóbal Colón',
    title_en: 'Christopher Columbus',
    slug: 'cristobal-colon',
    content_es: `Cristóbal Colón (1451-1506) fue un navegante genovés al servicio de los Reyes Católicos cuyo viaje de 1492 inició el contacto permanente entre Europa y América, transformando la historia mundial. Su figura es profundamente controvertida.\n\nConvencido de que era posible llegar a Asia navegando al oeste, presentó su proyecto a varias cortes. Logró el apoyo de los Reyes Católicos tras la conquista de Granada. Las Capitulaciones de Santa Fe le otorgaron títulos sobre las tierras descubiertas.\n\nEl 3 de agosto de 1492 partió de Palos con la Santa María, la Pinta y la Niña. El 12 de octubre avistó tierra: Guanahani (San Salvador) en las Bahamas. Convencido de haber llegado a las Indias, llamó "indios" a los nativos.\n\nRealizó cuatro viajes al Caribe (1492-1504), explorando las Antillas, Venezuela y Centroamérica. Su administración fue problemática: sus políticas hacia los taínos incluyeron esclavitud y trabajo forzado, llevando a su arresto como gobernador.\n\nMurió en Valladolid en 1506, creyendo haber llegado a Asia. Su viaje transformó la demografía y ecología del planeta (Intercambio Colombino), pero también inició siglos de explotación colonial y sufrimiento indígena.`,
    content_en: `Christopher Columbus (1451-1506) was a Genoese navigator in the service of the Catholic Monarchs whose 1492 voyage initiated permanent contact between Europe and the Americas, transforming world history. His figure is deeply controversial.\n\nConvinced it was possible to reach Asia by sailing west, he presented his project to various courts. He gained support from the Catholic Monarchs after the conquest of Granada. The Capitulations of Santa Fe granted him titles over discovered lands.\n\nOn August 3, 1492, he departed from Palos with the Santa María, Pinta, and Niña. On October 12 he sighted land: Guanahani (San Salvador) in the Bahamas. Convinced he had reached the Indies, he called natives "Indians."\n\nHe made four voyages to the Caribbean (1492-1504), exploring the Antilles, Venezuela, and Central America. His administration was problematic: his policies toward the Taíno included slavery and forced labor, leading to his arrest as governor.\n\nHe died in Valladolid in 1506, believing he had reached Asia. His voyage transformed planetary demography and ecology (Columbian Exchange), but also initiated centuries of colonial exploitation and indigenous suffering.`,
    excerpt_es: 'Navegante genovés cuyo viaje de 1492 inició el contacto entre Europa y América.',
    excerpt_en: 'Genoese navigator whose 1492 voyage initiated contact between Europe and the Americas.',
    categoryId: 'cat-figures-explorers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-25T00:00:00Z',
    updatedAt: '2026-04-25T00:00:00Z',
  },
  {
    id: 'entry-magellan',
    title_es: 'Fernando de Magallanes',
    title_en: 'Ferdinand Magellan',
    slug: 'fernando-magallanes',
    content_es: `Fernando de Magallanes (1480-1521) fue un navegante portugués al servicio de España que lideró la primera circunnavegación del globo, demostrando que la Tierra era redonda. Aunque murió antes de completar el viaje, su hazaña revolucionó la comprensión del planeta.\n\nTras caer en desgracia ante el rey de Portugal, ofreció sus servicios a Carlos I de España, proponiendo una ruta occidental a las Islas de las Especias (Molucas).\n\nLa expedición partió de Sanlúcar de Barrameda el 20 de septiembre de 1519 con cinco naves y 270 hombres. Descubrieron el estrecho de Magallanes en octubre de 1520, una peligrosa ruta de 500 km en el extremo sur de la Patagonia.\n\nLa travesía del Pacífico duró 98 días sin avistar tierra. La tripulación sufrió hambre y escorbuto. Magallanes murió en la batalla de Mactán, Filipinas, el 27 de abril de 1521.\n\nJuan Sebastián Elcano completó la circunnavegación, regresando a España el 6 de septiembre de 1522 con solo 18 supervivientes a bordo de la Victoria. Fue la primera vuelta al mundo de la historia.`,
    content_en: `Ferdinand Magellan (1480-1521) was a Portuguese navigator in Spanish service who led the first circumnavigation of the globe, proving the Earth was round. Although he died before completing the voyage, his feat revolutionized understanding of the planet.\n\nAfter falling out of favor with Portugal's king, he offered his services to Charles I of Spain, proposing a western route to the Spice Islands (Moluccas).\n\nThe expedition departed Sanlúcar de Barrameda on September 20, 1519, with five ships and 270 men. They discovered the Strait of Magellan in October 1520, a dangerous 500 km route at the southern tip of Patagonia.\n\nThe Pacific crossing lasted 98 days without sighting land. The crew suffered hunger and scurvy. Magellan died at the Battle of Mactan, Philippines, on April 27, 1521.\n\nJuan Sebastián Elcano completed the circumnavigation, returning to Spain on September 6, 1522, with only 18 survivors aboard the Victoria. It was the first voyage around the world in history.`,
    excerpt_es: 'Primera circunnavegación del globo, demostrando que la Tierra es redonda.',
    excerpt_en: 'First circumnavigation of the globe, proving the Earth is round.',
    categoryId: 'cat-figures-explorers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-26T00:00:00Z',
    updatedAt: '2026-04-26T00:00:00Z',
  },
  {
    id: 'entry-marco-polo',
    title_es: 'Marco Polo',
    title_en: 'Marco Polo',
    slug: 'marco-polo',
    content_es: `Marco Polo (1254-1324) fue un mercader veneciano cuyos viajes por Asia quedaron registrados en "Il Milione", uno de los libros de viajes más influyentes de la historia. Su descripción del Lejano Oriente transformó la imaginación europea.\n\nEn 1271, con diecisiete años, partió con su padre y su tío hacia la corte de Kublai Kan por la Ruta de la Seda. El viaje duró tres años y medio a través de Tierra Santa, Persia, Asia Central y el desierto de Gobi.\n\nPasaron diecisiete años en China, donde Marco sirvió como emisario del kan. Observó maravillas desconocidas en Europa: papel moneda, porcelana, pólvora, imprenta, seda y carbón.\n\nRegresaron en 1295 por el océano Índico y Persia. En 1298, Marco fue capturado en una batalla naval entre Venecia y Génova. En prisión, dictó sus viajes a su compañero Rustichello da Pisa.\n\nEl libro fascinó a Europa aunque muchos dudaron de su veracidad. Colón llevó un ejemplar anotado en su viaje de 1492. Hoy los historiadores confirman la precisión de la mayoría de sus descripciones.`,
    content_en: `Marco Polo (1254-1324) was a Venetian merchant whose travels through Asia were recorded in "Il Milione," one of the most influential travel books in history. His description of the Far East transformed the European imagination.\n\nIn 1271, at seventeen, he departed with his father and uncle for Kublai Khan's court along the Silk Road. The journey took three and a half years through the Holy Land, Persia, Central Asia, and the Gobi Desert.\n\nThey spent seventeen years in China, where Marco served as the Khan's envoy. He observed wonders unknown in Europe: paper money, porcelain, gunpowder, printing, silk, and coal.\n\nThey returned in 1295 via the Indian Ocean and Persia. In 1298, Marco was captured in a naval battle between Venice and Genoa. In prison, he dictated his travels to his cellmate Rustichello da Pisa.\n\nThe book fascinated Europe though many doubted its veracity. Columbus carried an annotated copy on his 1492 voyage. Today historians confirm the accuracy of most of his descriptions.`,
    excerpt_es: 'Mercader veneciano que reveló las maravillas de China a la Europa medieval.',
    excerpt_en: 'Venetian merchant who revealed the wonders of China to medieval Europe.',
    categoryId: 'cat-figures-explorers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-27T00:00:00Z',
    updatedAt: '2026-04-27T00:00:00Z',
  },
  {
    id: 'entry-ibn-battuta',
    title_es: 'Ibn Battuta',
    title_en: 'Ibn Battuta',
    slug: 'ibn-battuta',
    content_es: `Ibn Battuta (1304-1369) fue un erudito, jurista y explorador marroquí cuyo viaje de 30 años lo llevó a recorrer más de 120,000 km, visitando la mayor parte del mundo islámico. Es considerado uno de los mayores viajeros de la historia.\n\nNacido en Tánger, partió en 1325 a los 21 años para la peregrinación a La Meca. Su viaje se extendió tres décadas. Su libro, la Rihla, es fuente invaluable sobre el mundo medieval.\n\nSu ruta incluyó norte de África, Egipto, Siria, Arabia, Irak, Persia, Anatolia y el Cuerno de África. Visitó la costa swahili hasta Kilwa (Tanzania). Luego viajó a la India, sirviendo como juez en Delhi durante ocho años.\n\nDesde la India viajó a Maldivas, Ceilán, Bengala, Sumatra, Java y China (Cantón y Pekín). En el regreso visitó Al-Ándalus y en 1352 emprendió su último viaje al imperio de Malí.\n\nLa Rihla describe costumbres, política y geografía de las regiones visitadas. Ibn Battuta se casó múltiples veces, tuvo hijos y enfrentó naufragios, bandidos y enfermedades. Su legado es el de un incansable buscador de conocimiento sin fronteras.`,
    content_en: `Ibn Battuta (1304-1369) was a Moroccan scholar, jurist, and explorer whose 30-year journey covered over 120,000 km, visiting most of the Islamic world. He is considered one of the greatest travelers in history.\n\nBorn in Tangier, he departed in 1325 at 21 for the pilgrimage to Mecca. His journey extended three decades. His book, the Rihla, is an invaluable source on the medieval world.\n\nHis route included North Africa, Egypt, Syria, Arabia, Iraq, Persia, Anatolia, and the Horn of Africa. He visited the Swahili coast to Kilwa (Tanzania). Then he traveled to India, serving as a judge in Delhi for eight years.\n\nFrom India he traveled to the Maldives, Ceylon, Bengal, Sumatra, Java, and China (Canton and Beijing). On return he visited Al-Andalus and in 1352 undertook his last journey to the Mali Empire.\n\nThe Rihla describes customs, politics, and geography of visited regions. Ibn Battuta married multiple times, had children, and faced shipwrecks, bandits, and disease. His legacy is that of a tireless knowledge seeker without boundaries.`,
    excerpt_es: 'Erudito marroquí que recorrió 120,000 km por África, Asia y Europa en 30 años.',
    excerpt_en: 'Moroccan scholar who traveled 120,000 km across Africa, Asia, and Europe in 30 years.',
    categoryId: 'cat-figures-explorers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-28T00:00:00Z',
    updatedAt: '2026-04-28T00:00:00Z',
  },

  // --- Artists ---
  {
    id: 'entry-leonardo',
    title_es: 'Leonardo da Vinci',
    title_en: 'Leonardo da Vinci',
    slug: 'leonardo-da-vinci',
    content_es: `Leonardo da Vinci (1452-1519) fue un polímata renacentista italiano cuyos intereses abarcaron pintura, escultura, arquitectura, ciencia, música, matemáticas, ingeniería, anatomía, geología y botánica. Es el arquetipo del "hombre del Renacimiento".\n\nNacido en Vinci, hijo ilegítimo de un notario y una campesina, recibió educación en el taller de Verrocchio en Florencia. Allí desarrolló habilidades artísticas y científicas. Su obra maestra temprana fue "La Adoración de los Magos".\n\nEntre sus obras más famosas: la Mona Lisa, La Última Cena, La Virgen de las Rocas y el Hombre de Vitruvio. Solo se conservan unas 15 pinturas suyas, todas consideradas obras maestras.\n\nFue prolífico inventor. Sus cuadernos contienen diseños de máquinas voladoras, tanques, submarinos y dispositivos hidráulicos. Realizó estudios anatómicos mediante disección, dibujando el corazón, los músculos y el feto con precisión extraordinaria.\n\nPasó sus últimos años en Francia invitado por Francisco I. Murió en 1519 en Clos-Lucé. Su legado combina observación empírica, pensamiento sistémico y curiosidad ilimitada, modelo de aprendizaje interdisciplinario.`,
    content_en: `Leonardo da Vinci (1452-1519) was an Italian Renaissance polymath whose interests spanned painting, sculpture, architecture, science, music, mathematics, engineering, anatomy, geology, and botany. He is the archetype of the "Renaissance man."\n\nBorn in Vinci, illegitimate son of a notary and peasant woman, he received education in Verrocchio's workshop in Florence. There he developed artistic and scientific skills. His early masterpiece was "The Adoration of the Magi."\n\nAmong his most famous works: the Mona Lisa, The Last Supper, The Virgin of the Rocks, and the Vitruvian Man. Only about 15 of his paintings survive, all considered masterpieces.\n\nHe was a prolific inventor. His notebooks contain designs for flying machines, tanks, submarines, and hydraulic devices. He conducted anatomical studies through dissection, drawing the heart, muscles, and fetus with extraordinary precision.\n\nHe spent his final years in France invited by Francis I. He died in 1519 at Clos-Lucé. His legacy combines empirical observation, systemic thinking, and boundless curiosity, a model of interdisciplinary learning.`,
    excerpt_es: 'El arquetipo del genio renacentista: pintor, inventor y científico universal.',
    excerpt_en: 'The archetype of the Renaissance genius: painter, inventor, and universal scientist.',
    categoryId: 'cat-figures-artists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-29T00:00:00Z',
    updatedAt: '2026-04-29T00:00:00Z',
  },
  {
    id: 'entry-frida',
    title_es: 'Frida Kahlo',
    title_en: 'Frida Kahlo',
    slug: 'frida-kahlo',
    content_es: `Magdalena Carmen Frida Kahlo (1907-1954) fue una pintora mexicana mundialmente conocida por sus autorretratos, que exploran el dolor, la identidad, el cuerpo femenino y la cultura mexicana. Su estilo único combina realismo mágico, simbolismo y arte popular.\n\nA los seis años contrajo polio, atrofiando su pierna derecha. A los dieciocho sufrió un grave accidente de autobús con fracturas múltiples. Durante su convalecencia comenzó a pintar, usando un espejo en el dosel de su cama.\n\nSus obras más características: "Las dos Fridas", "La columna rota", "Autorretrato con collar de espinas" y "Viva la vida". Se representa con su ceja unida y trajes tradicionales mexicanos, rodeada de símbolos de su mundo interior.\n\nSe casó con Diego Rivera en 1929, una relación tumultuosa de pasión e infidelidades mutuas. La casa azul de Coyoacán, donde vivieron, es hoy el Museo Frida Kahlo.\n\nMurió en 1954 a los 47 años. Su obra, menos valorada que la de Rivera en vida, alcanzó fama internacional décadas después. Hoy es celebrada como icono feminista y símbolo de la resiliencia y la identidad mexicana.`,
    content_en: `Magdalena Carmen Frida Kahlo (1907-1954) was a Mexican painter known worldwide for her self-portraits, exploring pain, identity, the female body, and Mexican culture. Her unique style combines magical realism, symbolism, and folk art.\n\nAt six she contracted polio, atrophying her right leg. At eighteen she suffered a serious bus accident with multiple fractures. During convalescence she began painting, using a mirror on her bed canopy.\n\nHer most characteristic works: "The Two Fridas," "The Broken Column," "Self-Portrait with Thorn Necklace," and "Viva la Vida." She depicts herself with her unibrow and traditional Mexican costumes, surrounded by symbols of her inner world.\n\nShe married Diego Rivera in 1929, a tumultuous relationship of passion and mutual infidelities. The blue house in Coyoacán, where they lived, is now the Frida Kahlo Museum.\n\nShe died in 1954 at 47. Her work, less valued than Rivera's in life, achieved international fame decades later. Today she is celebrated as a feminist icon and symbol of resilience and Mexican identity.`,
    excerpt_es: 'Pintora mexicana cuyos autorretratos exploran el dolor, la identidad y la cultura mexicana.',
    excerpt_en: 'Mexican painter whose self-portraits explore pain, identity, and Mexican culture.',
    categoryId: 'cat-figures-artists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-04-30T00:00:00Z',
    updatedAt: '2026-04-30T00:00:00Z',
  },
  {
    id: 'entry-van-gogh',
    title_es: 'Vincent van Gogh',
    title_en: 'Vincent van Gogh',
    slug: 'vincent-van-gogh',
    content_es: `Vincent van Gogh (1853-1890) fue un pintor neerlandés postimpresionista, uno de los artistas más influyentes de la historia del arte occidental. En vida vendió apenas un cuadro y fue considerado un fracaso; hoy es un mito del genio incomprendido.\n\nNacido en Zundert, trabajó como marchante de arte y predicador antes de dedicarse a la pintura a los 27 años. Su hermano Theo lo apoyó financiera y emocionalmente, manteniendo una correspondencia que revela su alma atormentada.\n\nSus primeras obras ("Los comedores de patatas") reflejan su paleta sombría. En París descubrió el impresionismo, transformando su estilo hacia colores brillantes. En Arlés pintó sus obras más famosas.\n\nLa relación con Gauguin terminó trágicamente en 1888 cuando Van Gogh se cortó parte de la oreja. Ingresó voluntariamente en el asilo de Saint-Rémy, donde pintó "La noche estrellada" y "Los lirios".\n\nSe suicidó en 1890 disparándose en el pecho. En poco más de una década produjo 860 pinturas y más de 1,000 dibujos. La fama llegó póstumamente; hoy sus obras se cuentan entre las más caras del mundo.`,
    content_en: `Vincent van Gogh (1853-1890) was a Dutch post-impressionist painter, one of the most influential artists in Western art history. In his lifetime he sold barely one painting and was considered a failure; today he is a myth of the misunderstood genius.\n\nBorn in Zundert, he worked as an art dealer and preacher before pursuing painting at 27. His brother Theo supported him financially and emotionally, maintaining a correspondence revealing his tormented soul.\n\nHis early works ("The Potato Eaters") reflect his somber palette. In Paris he discovered Impressionism, transforming his style toward bright colors. In Arles he painted his most famous works.\n\nThe relationship with Gauguin ended tragically in 1888 when van Gogh cut off part of his ear. He voluntarily entered the Saint-Rémy asylum, where he painted "The Starry Night" and "Irises."\n\nHe shot himself in 1890. In just over a decade he produced 860 paintings and over 1,000 drawings. Fame came posthumously; today his works rank among the most expensive in the world.`,
    excerpt_es: 'Pintor postimpresionista neerlandés, genio incomprendido que hoy es uno de los más famosos.',
    excerpt_en: 'Dutch post-impressionist painter, misunderstood genius now among the most famous.',
    categoryId: 'cat-figures-artists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
  },
  {
    id: 'entry-shakespeare',
    title_es: 'William Shakespeare',
    title_en: 'William Shakespeare',
    slug: 'william-shakespeare',
    content_es: `William Shakespeare (1564-1616) fue un dramaturgo, poeta y actor inglés, el escritor más importante en lengua inglesa y uno de los más grandes de la literatura universal. Su obra incluye 39 obras teatrales, 154 sonetos y varios poemas narrativos.\n\nNacido en Stratford-upon-Avon, se casó a los 18 con Anne Hathaway. Hacia 1592 ya era actor y dramaturgo en Londres, miembro de la compañía Lord Chamberlain's Men (luego King's Men).\n\nSus obras se clasifican en tragedias ("Hamlet", "Macbeth", "Romeo y Julieta", "Otelo", "El rey Lear"), comedias ("Sueño de una noche de verano", "La tempestad") y dramas históricos ("Ricardo III", "Enrique V").\n\nRevolucionó el teatro con su dominio del verso blanco, personajes psicológicamente complejos y temas universales: amor, celos, ambición, traición, locura y muerte. Expresiones como "ser o no ser" son parte del lenguaje cotidiano.\n\nMurió en 1616. La "cuestión shakesperiana" —dudas sobre la autoría de sus obras— ha generado especulación, aunque la mayoría de los académicos aceptan a Shakespeare como el autor genuino. Su influencia en la literatura, el arte y el lenguaje es inconmensurable.`,
    content_en: `William Shakespeare (1564-1616) was an English playwright, poet, and actor, the most important writer in the English language and one of the greatest in world literature. His work includes 39 plays, 154 sonnets, and several narrative poems.\n\nBorn in Stratford-upon-Avon, he married Anne Hathaway at 18. By 1592 he was an actor and playwright in London, member of the Lord Chamberlain's Men (later the King's Men).\n\nHis works are classified into tragedies ("Hamlet," "Macbeth," "Romeo and Juliet," "Othello," "King Lear"), comedies ("A Midsummer Night's Dream," "The Tempest"), and histories ("Richard III," "Henry V").\n\nHe revolutionized theater with his mastery of blank verse, psychologically complex characters, and universal themes: love, jealousy, ambition, betrayal, madness, and death. Expressions like "to be or not to be" are part of everyday language.\n\nHe died in 1616. The "Shakespeare authorship question" — doubts about the authorship of his works — has generated speculation, though most scholars accept Shakespeare as the genuine author. His influence on literature, art, and language is immeasurable.`,
    excerpt_es: 'El dramaturgo más importante de la literatura universal, autor de Hamlet, Romeo y Julieta y Macbeth.',
    excerpt_en: 'The most important playwright in world literature, author of Hamlet, Romeo and Juliet, and Macbeth.',
    categoryId: 'cat-figures-artists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-05-02T00:00:00Z',
    updatedAt: '2026-05-02T00:00:00Z',
  },

  // --- Legendary Figures ---
  {
    id: 'entry-king-arthur',
    title_es: 'Rey Arturo',
    title_en: 'King Arthur',
    slug: 'rey-arturo',
    content_es: `El Rey Arturo es una figura legendaria británica que, según la tradición, lideró la defensa de Britania contra los sajones a finales del siglo V. Es el personaje central del ciclo artúrico, uno de los cuerpos de leyenda más influyentes de la literatura occidental.\n\nSu existencia histórica es incierta. Las primeras referencias aparecen en fuentes galesas del siglo IX. La "Historia Brittonum" menciona a un líder llamado Arturo que derrotó a los sajones en doce batallas.\n\nLa leyenda fue forjada por Geoffrey de Monmouth en su "Historia Regum Britanniae" (c. 1136). Autores franceses como Chrétien de Troyes introdujeron a Lancelot, el Santo Grial y el amor cortés.\n\nSir Thomas Malory compiló las tradiciones en "La muerte de Arturo" (1485): Arturo extrae Excalibur de la piedra, funda la Mesa Redonda, busca el Grial y cae en Camlann contra su hijo Mordred.\n\nArturo es llevado a Ávalon para sanar, donde espera regresar. El mito ha sido reinterpretado desde Tennyson hasta el cine. La "tabla redonda" simboliza igualdad y justicia.`,
    content_en: `King Arthur is a legendary British figure who, according to tradition, led the defense of Britain against the Saxons at the end of the 5th century. He is the central character of the Arthurian cycle, one of the most influential bodies of legend in Western literature.\n\nHis historical existence is uncertain. The earliest references appear in Welsh sources from the 9th century. The "Historia Brittonum" mentions a leader named Arthur who defeated the Saxons in twelve battles.\n\nThe legend was forged by Geoffrey of Monmouth in his "Historia Regum Britanniae" (c. 1136). French authors like Chrétien de Troyes introduced Lancelot, the Holy Grail, and courtly love.\n\nSir Thomas Malory compiled the traditions in "Le Morte d'Arthur" (1485): Arthur pulls Excalibur from the stone, founds the Round Table, seeks the Grail, and falls at Camlann against his son Mordred.\n\nArthur is taken to Avalon to heal, where he awaits to return. The myth has been reinterpreted from Tennyson to cinema. The "round table" symbolizes equality and justice.`,
    excerpt_es: 'Legendario rey británico de la Mesa Redonda, la espada Excalibur y el Santo Grial.',
    excerpt_en: 'Legendary British king of the Round Table, the sword Excalibur, and the Holy Grail.',
    categoryId: 'cat-figures-legendary',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-05-03T00:00:00Z',
    updatedAt: '2026-05-03T00:00:00Z',
  },
  {
    id: 'entry-robin-hood',
    title_es: 'Robin Hood',
    title_en: 'Robin Hood',
    slug: 'robin-hood',
    content_es: `Robin Hood es un legendario héroe popular inglés que, según la tradición, robaba a los ricos para dar a los pobres. Es el arquero más famoso de la literatura, asociado con el bosque de Sherwood y la lucha contra la injusticia del sheriff de Nottingham.\n\nLas primeras baladas sobre Robin Hood datan del siglo XIV, pero la leyenda probablemente es anterior. A diferencia de otras figuras legendarias, Robin Hood no es un rey o caballero noble sino un proscrito, un bandido que desafía la autoridad injusta.\n\nLa historia tradicional lo presenta como un noble empobrecido que pierde sus tierras y se refugia en el bosque con su banda de "hombres alegres": Little John, Friar Tuck, Will Scarlet y Maid Marian.\n\nEs un maestro del arco largo inglés, astuto y generoso. Su enemigo principal es el sheriff de Nottingham, que representa la opresión y la corrupción del poder. Robin Hood es también generoso con la Iglesia (el fraile Tuck) y leal al rey Ricardo Corazón de León.\n\nNo hay evidencia histórica de Robin Hood como persona real, aunque varias figuras históricas han sido propuestas como inspiración. La leyenda ha sido adaptada en innumerables películas, series y libros, convirtiéndose en un arquetipo universal del héroe justiciero.`,
    content_en: `Robin Hood is a legendary English folk hero who, according to tradition, robbed from the rich to give to the poor. He is the most famous archer in literature, associated with Sherwood Forest and the fight against the injustice of the Sheriff of Nottingham.\n\nThe earliest ballads about Robin Hood date from the 14th century, but the legend is likely older. Unlike other legendary figures, Robin Hood is not a king or noble knight but an outlaw, a bandit who defies unjust authority.\n\nThe traditional story presents him as an impoverished nobleman who loses his lands and takes refuge in the forest with his band of "merry men": Little John, Friar Tuck, Will Scarlet, and Maid Marian.\n\nHe is a master of the English longbow, cunning and generous. His main enemy is the Sheriff of Nottingham, representing oppression and corrupt power. Robin Hood is also generous with the Church (Friar Tuck) and loyal to King Richard the Lionheart.\n\nThere is no historical evidence of Robin Hood as a real person, though several historical figures have been proposed as inspiration. The legend has been adapted in countless films, series, and books, becoming a universal archetype of the avenging hero.`,
    excerpt_es: 'Legendario héroe inglés que robaba a los ricos para dar a los pobres en el bosque de Sherwood.',
    excerpt_en: 'Legendary English hero who robbed from the rich to give to the poor in Sherwood Forest.',
    categoryId: 'cat-figures-legendary',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-05-04T00:00:00Z',
    updatedAt: '2026-05-04T00:00:00Z',
  },
  {
    id: 'entry-gilgamesh',
    title_es: 'Gilgamesh',
    title_en: 'Gilgamesh',
    slug: 'gilgamesh',
    content_es: `Gilgamesh es el héroe de la "Epopeya de Gilgamesh", la obra literaria más antigua conocida de la humanidad, escrita en tablillas de arcilla en escritura cuneiforme en la antigua Mesopotamia hacia el 2100 a.C.\n\nSegún la leyenda, Gilgamesh fue el quinto rey de Uruk (actual Irak), que reinó alrededor del 2700 a.C. La Lista Real Sumeria lo menciona como un rey semidivino, hijo de la diosa Ninsun y un rey mortal. Se le atribuye la construcción de las murallas de Uruk.\n\nLa epopeya narra su amistad con Enkidu, un hombre salvaje creado por los dioses para desafiar a Gilgamesh. Tras luchar y hacerse amigos, emprenden aventuras juntos, derrotando al monstruo Humbaba y al Toro del Cielo.\n\nLa muerte de Enkidu sume a Gilgamesh en un profundo dolor y despierta en él el miedo a la muerte. Emprende un viaje en busca de la inmortalidad, encontrando a Utnapishtim, el superviviente del diluvio universal, quien le revela que la inmortalidad física está reservada a los dioses.\n\nGilgamesh regresa a Uruk comprendiendo que la inmortalidad verdadera se alcanza a través de las obras que deja el ser humano. La epopeya explora temas universales: la amistad, la mortalidad, el poder y la sabiduría. Su influencia en la literatura posterior, incluyendo la Biblia, es significativa.`,
    content_en: `Gilgamesh is the hero of the "Epic of Gilgamesh," the oldest known literary work of humanity, written on clay tablets in cuneiform script in ancient Mesopotamia around 2100 BC.\n\nAccording to legend, Gilgamesh was the fifth king of Uruk (present-day Iraq), who reigned around 2700 BC. The Sumerian King List mentions him as a semidivine king, son of the goddess Ninsun and a mortal king. He is credited with building the walls of Uruk.\n\nThe epic narrates his friendship with Enkidu, a wild man created by the gods to challenge Gilgamesh. After fighting and becoming friends, they embark on adventures together, defeating the monster Humbaba and the Bull of Heaven.\n\nEnkidu's death plunges Gilgamesh into deep grief and awakens his fear of death. He embarks on a quest for immortality, finding Utnapishtim, the survivor of the great flood, who reveals that physical immortality is reserved for the gods.\n\nGilgamesh returns to Uruk understanding that true immortality is achieved through the works one leaves behind. The epic explores universal themes: friendship, mortality, power, and wisdom. Its influence on later literature, including the Bible, is significant.`,
    excerpt_es: 'Héroe de la epopeya más antigua de la humanidad, rey de Uruk en la antigua Mesopotamia.',
    excerpt_en: 'Hero of the oldest known epic, king of Uruk in ancient Mesopotamia.',
    categoryId: 'cat-figures-legendary',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-05-05T00:00:00Z',
    updatedAt: '2026-05-05T00:00:00Z',
  },
  {
    id: 'entry-mulan',
    title_es: 'Mulan',
    title_en: 'Mulan',
    slug: 'mulan',
    content_es: `Mulan es una figura legendaria de la antigua China, conocida por la "Balada de Mulan", un poema folk compuesto durante la dinastía Wei del Norte (siglos IV-VI d.C.). La historia de la joven que se disfraza de hombre para ocupar el lugar de su padre en el ejército es una de las más queridas de la cultura china.\n\nLa balada original, de unos 300 caracteres, narra cómo Mulan, al ver que su padre anciano es llamado a filas, decide cortarse el cabello, vestirse con armadura y unirse al ejército en su lugar. Sirve durante doce años sin que nadie descubra su verdadera identidad.\n\nA diferencia de las versiones occidentales modernas, la balada original no enfatiza el romance ni las habilidades marciales sobrenaturales. Mulan es simplemente una hija devota (xiaoshun) que actúa por piedad filial, el valor central del confucianismo.\n\nTras doce años de servicio, Mulan rechaza los honores y cargos que le ofrece el emperador, pidiendo solo un caballo para regresar a su hogar. Al llegar, se viste con ropa femenina, sorprendiendo a sus compañeros que nunca habían sospechado su secreto.\n\nLa historia de Mulan ha sido adaptada en incontables obras: óperas, novelas, películas (incluyendo las versiones animada y live-action de Disney) y series de televisión. Representa la valentía, la lealtad familiar y la superación de las barreras de género.`,
    content_en: `Mulan is a legendary figure from ancient China, known through the "Ballad of Mulan," a folk poem composed during the Northern Wei dynasty (4th-6th centuries AD). The story of a young woman who disguises herself as a man to take her father's place in the army is one of the most beloved in Chinese culture.\n\nThe original ballad, about 300 characters long, tells how Mulan, seeing her elderly father called to duty, decides to cut her hair, don armor, and join the army in his place. She serves for twelve years without anyone discovering her true identity.\n\nUnlike modern Western adaptations, the original ballad does not emphasize romance or supernatural martial skills. Mulan is simply a devoted daughter (xiaoshun) acting out of filial piety, the central value of Confucianism.\n\nAfter twelve years of service, Mulan rejects the honors and positions offered by the emperor, asking only for a horse to return home. Upon arriving, she dresses in women's clothing, astonishing her comrades who had never suspected her secret.\n\nMulan's story has been adapted in countless works: operas, novels, films (including Disney's animated and live-action versions), and television series. She represents courage, family loyalty, and overcoming gender barriers.`,
    excerpt_es: 'Heroína legendaria china que se disfrazó de hombre para ocupar el lugar de su padre en el ejército.',
    excerpt_en: 'Legendary Chinese heroine who disguised herself as a man to take her father\'s place in the army.',
    categoryId: 'cat-figures-legendary',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-05-06T00:00:00Z',
    updatedAt: '2026-05-06T00:00:00Z',
  },
]
