import { SeedEntry } from '../seed'

export const entries200Pt4: SeedEntry[] = [
  {
    id: 'entry-200-151',
    title_es: 'Fondo Cósmico de Microondas',
    title_en: 'Cosmic Microwave Background',
    slug: 'fondo-cosmico-de-microondas',
    content_es: `El Fondo Cósmico de Microondas (CMB) es la radiación remanente del Big Bang que llena todo el universo. Fue descubierto accidentalmente en 1965 por Arno Penzias y Robert Wilson, quienes detectaron un ruido persistente en su antena de microondas que no podía explicarse.\n\nEste descubrimiento confirmó la teoría del Big Bang y les valió el Premio Nobel de Física en 1978. Las misiones COBE, WMAP y Planck han cartografiado el CMB con precisión creciente, revelando las fluctuaciones de temperatura que dieron origen a las estructuras cósmicas como galaxias y cúmulos.`,
    content_en: `The Cosmic Microwave Background (CMB) is the remnant radiation from the Big Bang that fills the entire universe. It was accidentally discovered in 1965 by Arno Penzias and Robert Wilson, who detected a persistent noise in their microwave antenna that could not be explained.\n\nThis discovery confirmed the Big Bang theory and earned them the Nobel Prize in Physics in 1978. The COBE, WMAP, and Planck missions have mapped the CMB with increasing precision, revealing the temperature fluctuations that gave rise to cosmic structures such as galaxies and clusters.`,
    excerpt_es: 'Radiación remanente del Big Bang descubierta por Penzias y Wilson que confirmó el origen del universo.',
    excerpt_en: 'Remnant radiation from the Big Bang discovered by Penzias and Wilson that confirmed the origin of the universe.',
    categoryId: 'cat-cosmology-universe',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-07-16T00:00:00Z',
    updatedAt: '2026-07-16T00:00:00Z',
  },
  {
    id: 'entry-200-152',
    title_es: 'Materia Oscura',
    title_en: 'Dark Matter',
    slug: 'materia-oscura',
    content_es: `La materia oscura es una forma hipotética de materia que no emite, absorbe ni refleja luz, pero cuya existencia se infiere por sus efectos gravitacionales. Las curvas de rotación de las galaxias muestran que las estrellas en los bordes se mueven demasiado rápido para la cantidad de materia visible.\n\nSe estima que la materia oscura constituye aproximadamente el 27% del contenido del universo. Las partículas más prometedoras para explicarla son los WIMPs, y experimentos como LUX, Xenon1T y el LHC buscan detectarlas directamente.`,
    content_en: `Dark matter is a hypothetical form of matter that does not emit, absorb, or reflect light, but whose existence is inferred through its gravitational effects. Galactic rotation curves show that stars at the edges move too fast for the amount of visible matter.\n\nDark matter is estimated to constitute approximately 27% of the universe's content. The most promising candidate particles are WIMPs, and experiments like LUX, Xenon1T, and the LHC are actively searching for direct detection.`,
    excerpt_es: 'Materia invisible que constituye el 27% del universo y solo se detecta por sus efectos gravitacionales.',
    excerpt_en: 'Invisible matter constituting 27% of the universe that is only detected through its gravitational effects.',
    categoryId: 'cat-cosmology-universe',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-07-17T00:00:00Z',
    updatedAt: '2026-07-17T00:00:00Z',
  },
  {
    id: 'entry-200-153',
    title_es: 'Energía Oscura',
    title_en: 'Dark Energy',
    slug: 'energia-oscura',
    content_es: `La energía oscura es una forma hipotética de energía que impregna todo el espacio y está acelerando la expansión del universo. Fue descubierta en 1998 al observar supernovas tipo Ia, que parecían más débiles de lo esperado, indicando que la expansión cósmica se acelera.\n\nRepresenta aproximadamente el 68% del contenido del universo. La constante cosmológica de Einstein es la explicación más simple, aunque otras teorías proponen campos dinámicos como la quintaesencia. Comprender la energía oscura es uno de los mayores desafíos de la cosmología actual.`,
    content_en: `Dark energy is a hypothetical form of energy that permeates all of space and is accelerating the expansion of the universe. It was discovered in 1998 through observations of Type Ia supernovae, which appeared dimmer than expected, indicating that cosmic expansion is speeding up.\n\nIt represents approximately 68% of the universe's content. Einstein's cosmological constant is the simplest explanation, though other theories propose dynamic fields such as quintessence. Understanding dark energy is one of the greatest challenges in cosmology today.`,
    excerpt_es: 'Fuerza misteriosa que acelera la expansión del universo y constituye el 68% de su contenido.',
    excerpt_en: 'Mysterious force accelerating the expansion of the universe and constituting 68% of its content.',
    categoryId: 'cat-cosmology-universe',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-07-18T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
  },
  {
    id: 'entry-200-154',
    title_es: 'Agujeros Negros',
    title_en: 'Black Holes',
    slug: 'agujeros-negros',
    content_es: `Los agujeros negros son regiones del espacio-tiempo donde la gravedad es tan intensa que nada, ni siquiera la luz, puede escapar. Están delimitados por el horizonte de sucesos y contienen una singularidad en su centro donde la densidad se vuelve infinita.\n\nStephen Hawking propuso que los agujeros negros emiten radiación debido a efectos cuánticos, conocida como radiación de Hawking. En 2019, el Telescopio del Horizonte de Sucesos capturó la primera imagen directa de un agujero negro supermasivo en el centro de la galaxia M87.`,
    content_en: `Black holes are regions of spacetime where gravity is so intense that nothing, not even light, can escape. They are bounded by an event horizon and contain a singularity at their center where density becomes infinite.\n\nStephen Hawking proposed that black holes emit radiation due to quantum effects, known as Hawking radiation. In 2019, the Event Horizon Telescope captured the first direct image of a supermassive black hole at the center of galaxy M87.`,
    excerpt_es: 'Regiones del espacio donde la gravedad impide que escape la luz, con singularidades y horizonte de sucesos.',
    excerpt_en: 'Regions of space where gravity prevents even light from escaping, featuring singularities and event horizons.',
    categoryId: 'cat-cosmology-universe',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-07-19T00:00:00Z',
    updatedAt: '2026-07-19T00:00:00Z',
  },
  {
    id: 'entry-200-155',
    title_es: 'Teoría del Multiverso',
    title_en: 'Multiverse Theory',
    slug: 'teoria-del-multiverso',
    content_es: `La teoría del multiverso propone que nuestro universo es solo uno entre una infinidad de universos paralelos. Existen varias versiones: los muchos mundos de la mecánica cuántica, los universos burbuja de la inflación cósmica y el paisaje de la teoría de cuerdas.\n\nAunque no existe evidencia directa, el multiverso surge naturalmente de ciertas interpretaciones de la física teórica. La idea ha sido explorada en la filosofía, la ciencia ficción y el debate cosmológico como una posible solución a problemas como el ajuste fino del universo.`,
    content_en: `Multiverse theory proposes that our universe is just one among an infinite number of parallel universes. Several versions exist: the many worlds of quantum mechanics, the bubble universes of cosmic inflation, and the landscape of string theory.\n\nAlthough no direct evidence exists, the multiverse arises naturally from certain interpretations of theoretical physics. The idea has been explored in philosophy, science fiction, and cosmological debate as a possible solution to problems such as the fine-tuning of the universe.`,
    excerpt_es: 'Hipótesis cosmológica que propone la existencia de infinitos universos paralelos al nuestro.',
    excerpt_en: 'Cosmological hypothesis proposing the existence of infinite parallel universes beyond our own.',
    categoryId: 'cat-cosmology-universe',
    realityStatus: 'theoretical',
    imageUrl: '',
    createdAt: '2026-07-20T00:00:00Z',
    updatedAt: '2026-07-20T00:00:00Z',
  },
  {
    id: 'entry-200-156',
    title_es: 'Experimento de Miller-Urey',
    title_en: 'Miller-Urey Experiment',
    slug: 'experimento-de-miller-urey',
    content_es: `El experimento de Miller-Urey, realizado en 1953 por Stanley Miller y Harold Urey, simuló las condiciones de la Tierra primitiva para probar el origen abiótico de la vida. Utilizaron una mezcla de metano, amoníaco, hidrógeno y vapor de agua sometida a descargas eléctricas.\n\nEl experimento produjo aminoácidos y otros compuestos orgánicos esenciales para la vida, demostrando que los bloques de construcción biológicos pueden formarse espontáneamente en condiciones prebióticas. Este fue un hito fundamental para la teoría de la sopa primordial.`,
    content_en: `The Miller-Urey experiment, conducted in 1953 by Stanley Miller and Harold Urey, simulated early Earth conditions to test the abiotic origin of life. They used a mixture of methane, ammonia, hydrogen, and water vapor subjected to electrical sparks.\n\nThe experiment produced amino acids and other organic compounds essential for life, demonstrating that biological building blocks can form spontaneously under prebiotic conditions. This was a fundamental milestone for the primordial soup theory.`,
    excerpt_es: 'Experimento histórico que demostró que los aminoácidos pueden formarse espontáneamente en condiciones prebióticas.',
    excerpt_en: 'Historic experiment demonstrating that amino acids can form spontaneously under prebiotic conditions.',
    categoryId: 'cat-cosmology-life',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-07-21T00:00:00Z',
    updatedAt: '2026-07-21T00:00:00Z',
  },
  {
    id: 'entry-200-157',
    title_es: 'Hipótesis del Mundo de ARN',
    title_en: 'RNA World Hypothesis',
    slug: 'hipotesis-del-mundo-de-arn',
    content_es: `La hipótesis del mundo de ARN propone que la vida en la Tierra se originó a partir de moléculas de ARN capaces de auto-replicarse, antes de la aparición del ADN y las proteínas. El ARN puede almacenar información genética y catalizar reacciones químicas, funcionando como molécula versátil.\n\nLos ribozimas, moléculas de ARN con actividad catalítica, respaldan esta hipótesis. Este escenario explica cómo sistemas químicos simples pudieron dar origen a la complejidad biológica, aunque aún se debate cómo surgieron las primeras moléculas de ARN en la Tierra primitiva.`,
    content_en: `The RNA world hypothesis proposes that life on Earth originated from self-replicating RNA molecules, before the emergence of DNA and proteins. RNA can both store genetic information and catalyze chemical reactions, functioning as a versatile molecule.\n\nRibozymes, RNA molecules with catalytic activity, support this hypothesis. This scenario explains how simple chemical systems could give rise to biological complexity, though how the first RNA molecules emerged on early Earth is still debated.`,
    excerpt_es: 'Hipótesis sobre un mundo primitivo donde el ARN era la molécula central de la vida antes del ADN.',
    excerpt_en: 'Hypothesis about a primordial world where RNA was the central molecule of life before DNA emerged.',
    categoryId: 'cat-cosmology-life',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-07-22T00:00:00Z',
    updatedAt: '2026-07-22T00:00:00Z',
  },
  {
    id: 'entry-200-158',
    title_es: 'Panspermia',
    title_en: 'Panspermia',
    slug: 'panspermia',
    content_es: `La panspermia es la hipótesis de que la vida existe en todo el universo y puede viajar entre planetas y sistemas estelares a través de meteoritos, cometas y polvo interestelar. Sugiere que la vida en la Tierra pudo haberse originado a partir de microorganismos llegados del espacio.\n\nSe han encontrado moléculas orgánicas complejas en meteoritos y cometas, lo que apoya la viabilidad química de la panspermia. Los extremófilos demuestran que algunos organismos pueden sobrevivir en el espacio, haciendo plausible el transporte interplanetario de vida microbiana.`,
    content_en: `Panspermia is the hypothesis that life exists throughout the universe and can travel between planets and star systems via meteorites, comets, and interstellar dust. It suggests that life on Earth may have originated from microorganisms arriving from space.\n\nComplex organic molecules have been found in meteorites and comets, supporting the chemical feasibility of panspermia. Extremophiles demonstrate that some organisms can survive in space, making the interplanetary transport of microbial life plausible.`,
    excerpt_es: 'Hipótesis que sugiere que la vida viaja por el espacio y pudo llegar a la Tierra desde otros mundos.',
    excerpt_en: 'Hypothesis suggesting that life travels through space and may have reached Earth from other worlds.',
    categoryId: 'cat-cosmology-life',
    realityStatus: 'theoretical',
    imageUrl: '',
    createdAt: '2026-07-23T00:00:00Z',
    updatedAt: '2026-07-23T00:00:00Z',
  },
  {
    id: 'entry-200-159',
    title_es: 'LUCA (Último Ancestro Común Universal)',
    title_en: 'LUCA (Last Universal Common Ancestor)',
    slug: 'luca-ultimo-ancestro-comun-universal',
    content_es: `LUCA es el antepasado común más reciente de todos los organismos vivos actuales en la Tierra. No fue el primer ser vivo, sino el punto de divergencia a partir del cual evolucionaron las tres grandes ramas de la vida: bacterias, arqueas y eucariotas.\n\nEstimaciones genómicas sitúan a LUCA hace aproximadamente 3.5 a 3.8 mil millones de años. Los estudios comparativos de genes sugieren que era un organismo termófilo anaeróbico que habitaba en respiraderos hidrotermales, con un metabolismo basado en hidrógeno y dióxido de carbono.`,
    content_en: `LUCA is the most recent common ancestor of all current living organisms on Earth. It was not the first life form, but the divergence point from which the three great branches of life evolved: bacteria, archaea, and eukaryotes.\n\nGenomic estimates place LUCA approximately 3.5 to 3.8 billion years ago. Comparative gene studies suggest it was an anaerobic thermophile that inhabited hydrothermal vents, with a metabolism based on hydrogen and carbon dioxide.`,
    excerpt_es: 'Antepasado común más reciente de toda la vida actual en la Tierra, hace unos 3.800 millones de años.',
    excerpt_en: 'Most recent common ancestor of all current life on Earth, dating back about 3.8 billion years.',
    categoryId: 'cat-cosmology-life',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-07-24T00:00:00Z',
    updatedAt: '2026-07-24T00:00:00Z',
  },
  {
    id: 'entry-200-160',
    title_es: 'Teoría del Éxodo Africano',
    title_en: 'Out of Africa Theory',
    slug: 'teoria-del-exodo-africano',
    content_es: `La teoría del éxodo africano sostiene que todos los humanos modernos descienden de una población que vivió en África hace unos 200,000 años. Desde allí, Homo sapiens migró a otros continentes, reemplazando a las poblaciones arcaicas de homínidos como los neandertales.\n\nLa evidencia genética, especialmente el ADN mitocondrial y el cromosoma Y, respalda un origen africano reciente. Los fósiles más antiguos de Homo sapiens se han encontrado en Marruecos (300,000 años) y Etiopía (200,000 años), confirmando la cuna africana de la humanidad.`,
    content_en: `The Out of Africa theory holds that all modern humans descend from a population that lived in Africa about 200,000 years ago. From there, Homo sapiens migrated to other continents, replacing archaic hominin populations such as Neanderthals.\n\nGenetic evidence, especially mitochondrial DNA and the Y chromosome, supports a recent African origin. The oldest Homo sapiens fossils have been found in Morocco (300,000 years) and Ethiopia (200,000 years), confirming the African cradle of humanity.`,
    excerpt_es: 'Teoría que sitúa el origen de todos los humanos modernos en África hace unos 200,000 años.',
    excerpt_en: 'Theory placing the origin of all modern humans in Africa approximately 200,000 years ago.',
    categoryId: 'cat-cosmology-human',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-07-25T00:00:00Z',
    updatedAt: '2026-07-25T00:00:00Z',
  },
  {
    id: 'entry-200-161',
    title_es: 'Neandertales',
    title_en: 'Neanderthals',
    slug: 'neandertales',
    content_es: `Los neandertales (Homo neanderthalensis) fueron una especie de homínidos que vivió en Europa y Asia occidental hasta hace unos 40,000 años. Poseían cerebros grandes, cuerpos robustos adaptados al frío y una cultura compleja con herramientas, fuego y entierros.\n\nEstudios genéticos revelan que los humanos modernos no africanos tienen entre un 1% y un 2% de ADN neandertal, evidencia de cruzamiento. Las causas de su extinción incluyen la competencia con Homo sapiens, cambios climáticos y posiblemente enfermedades.`,
    content_en: `Neanderthals (Homo neanderthalensis) were a hominin species that lived in Europe and western Asia until about 40,000 years ago. They had large brains, robust bodies adapted to cold, and a complex culture with tools, fire, and burials.\n\nGenetic studies reveal that non-African modern humans have between 1% and 2% Neanderthal DNA, evidence of interbreeding. Causes of their extinction include competition with Homo sapiens, climate change, and possibly disease.`,
    excerpt_es: 'Especie de homínidos que vivió en Europa y Asia, con evidencia de cruzamiento con humanos modernos.',
    excerpt_en: 'Hominin species that lived in Europe and Asia, with evidence of interbreeding with modern humans.',
    categoryId: 'cat-cosmology-human',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-07-26T00:00:00Z',
    updatedAt: '2026-07-26T00:00:00Z',
  },
  {
    id: 'entry-200-162',
    title_es: 'Revolución Agrícola',
    title_en: 'Agricultural Revolution',
    slug: 'revolucion-agricola',
    content_es: `La Revolución Agrícola fue la transición de sociedades de cazadores-recolectores a comunidades sedentarias basadas en la agricultura y la domesticación de animales. Ocurrió de forma independiente en varias regiones del mundo hace unos 10,000 a 12,000 años.\n\nEste cambio transformó radicalmente la organización social: permitió el crecimiento demográfico, la especialización laboral, el comercio y el surgimiento de las primeras civilizaciones. Cultivos como el trigo, el arroz y el maíz, junto con animales como la oveja y la vaca, se convirtieron en la base de la alimentación humana.`,
    content_en: `The Agricultural Revolution was the transition from hunter-gatherer societies to sedentary communities based on farming and animal domestication. It occurred independently in several regions of the world about 10,000 to 12,000 years ago.\n\nThis change radically transformed social organization, enabling population growth, labor specialization, trade, and the emergence of the first civilizations. Crops like wheat, rice, and maize, along with animals such as sheep and cattle, became the foundation of human sustenance.`,
    excerpt_es: 'Transición de cazadores-recolectores a sociedades agrícolas que dio origen a las primeras civilizaciones.',
    excerpt_en: 'Transition from hunter-gatherers to agricultural societies that gave rise to the first civilizations.',
    categoryId: 'cat-cosmology-human',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-07-27T00:00:00Z',
    updatedAt: '2026-07-27T00:00:00Z',
  },
  {
    id: 'entry-200-163',
    title_es: 'Mecánica Cuántica',
    title_en: 'Quantum Mechanics',
    slug: 'mecanica-cuantica',
    content_es: `La mecánica cuántica es la rama de la física que estudia el comportamiento de la materia y la energía a escalas atómicas y subatómicas. Introdujo conceptos revolucionarios como la dualidad onda-partícula, la superposición cuántica y el principio de incertidumbre de Heisenberg.\n\nEl famoso experimento mental del gato de Schrödinger ilustra la paradoja de la superposición. La interpretación de Copenhague, formulada por Bohr y Heisenberg, es la más aceptada, aunque existen alternativas como los muchos mundos y la interpretación de Bohm. La mecánica cuántica es la base de tecnologías como los transistores y los láseres.`,
    content_en: `Quantum mechanics is the branch of physics that studies the behavior of matter and energy at atomic and subatomic scales. It introduced revolutionary concepts such as wave-particle duality, quantum superposition, and Heisenberg's uncertainty principle.\n\nThe famous thought experiment of Schrödinger's cat illustrates the superposition paradox. The Copenhagen interpretation, formulated by Bohr and Heisenberg, is the most accepted, though alternatives like many worlds and Bohm's interpretation exist. Quantum mechanics is the foundation of technologies such as transistors and lasers.`,
    excerpt_es: 'Rama de la física que describe el comportamiento de partículas subatómicas mediante probabilidades y superposición.',
    excerpt_en: 'Branch of physics describing the behavior of subatomic particles through probabilities and superposition.',
    categoryId: 'cat-physics',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-07-28T00:00:00Z',
    updatedAt: '2026-07-28T00:00:00Z',
  },
  {
    id: 'entry-200-164',
    title_es: 'Termodinámica',
    title_en: 'Thermodynamics',
    slug: 'termodinamica',
    content_es: `La termodinámica es la rama de la física que estudia el calor, el trabajo, la temperatura y la energía. Sus cuatro leyes fundamentales gobiernan cómo la energía se transforma y transfiere en los sistemas físicos, desde motores hasta organismos vivos.\n\nLa segunda ley establece que la entropía del universo siempre aumenta, lo que implica una flecha del tiempo irreversible. El concepto de muerte térmica del universo describe un estado final de equilibrio donde toda la energía se distribuye uniformemente y no es posible realizar trabajo útil.`,
    content_en: `Thermodynamics is the branch of physics that studies heat, work, temperature, and energy. Its four fundamental laws govern how energy transforms and transfers in physical systems, from engines to living organisms.\n\nThe second law states that the entropy of the universe always increases, implying an irreversible arrow of time. The concept of heat death of the universe describes a final equilibrium state where all energy is uniformly distributed and no useful work can be performed.`,
    excerpt_es: 'Rama de la física que estudia el calor, la energía y la entropía, con implicaciones para el destino del universo.',
    excerpt_en: 'Branch of physics studying heat, energy, and entropy, with implications for the fate of the universe.',
    categoryId: 'cat-physics',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-07-29T00:00:00Z',
    updatedAt: '2026-07-29T00:00:00Z',
  },
  {
    id: 'entry-200-165',
    title_es: 'Electromagnetismo',
    title_en: 'Electromagnetism',
    slug: 'electromagnetismo',
    content_es: `El electromagnetismo es la rama de la física que estudia los fenómenos eléctricos y magnéticos como una sola fuerza unificada. Las ecuaciones de Maxwell describen cómo los campos eléctricos y magnéticos se generan y propagan, prediciendo la existencia de ondas electromagnéticas.\n\nLa luz visible es una forma de radiación electromagnética. Este descubrimiento unificó la óptica con la electricidad y el magnetismo, y condujo a tecnologías fundamentales como la radio, el teléfono, el radar y las comunicaciones inalámbricas modernas.`,
    content_en: `Electromagnetism is the branch of physics that studies electrical and magnetic phenomena as a single unified force. Maxwell's equations describe how electric and magnetic fields are generated and propagate, predicting the existence of electromagnetic waves.\n\nVisible light is a form of electromagnetic radiation. This discovery unified optics with electricity and magnetism, leading to fundamental technologies such as radio, telephone, radar, and modern wireless communications.`,
    excerpt_es: 'Teoría unificada de la electricidad y el magnetismo descrita por las ecuaciones de Maxwell y la luz como onda.',
    excerpt_en: 'Unified theory of electricity and magnetism described by Maxwell\'s equations and light as a wave.',
    categoryId: 'cat-physics',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-07-30T00:00:00Z',
    updatedAt: '2026-07-30T00:00:00Z',
  },
  {
    id: 'entry-200-166',
    title_es: 'Física Nuclear',
    title_en: 'Nuclear Physics',
    slug: 'fisica-nuclear',
    content_es: `La física nuclear estudia el núcleo atómico, sus componentes y las interacciones que lo mantienen unido. Descubrió la radiactividad, la fisión y la fusión nuclear, procesos que liberan enormes cantidades de energía al modificar la estructura del núcleo.\n\nLa fisión nuclear, utilizada en reactores y bombas atómicas, divide núcleos pesados como el uranio. La fusión, que alimenta al Sol, une núcleos ligeros como el hidrógeno. La energía nuclear genera electricidad sin emisiones de carbono, pero plantea desafíos de seguridad y residuos radiactivos.`,
    content_en: `Nuclear physics studies the atomic nucleus, its components, and the interactions that hold it together. It discovered radioactivity, nuclear fission, and nuclear fusion, processes that release enormous amounts of energy by altering the nucleus structure.\n\nNuclear fission, used in reactors and atomic bombs, splits heavy nuclei like uranium. Fusion, which powers the Sun, joins light nuclei like hydrogen. Nuclear energy generates electricity without carbon emissions but poses safety and radioactive waste challenges.`,
    excerpt_es: 'Estudio del núcleo atómico, la radiactividad y las reacciones que liberan energía nuclear.',
    excerpt_en: 'Study of the atomic nucleus, radioactivity, and reactions that release nuclear energy.',
    categoryId: 'cat-physics',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-07-31T00:00:00Z',
    updatedAt: '2026-07-31T00:00:00Z',
  },
  {
    id: 'entry-200-167',
    title_es: 'Enlace Químico',
    title_en: 'Chemical Bonding',
    slug: 'enlace-quimico',
    content_es: `Los enlaces químicos son las fuerzas que mantienen unidos a los átomos en las moléculas y compuestos. Los principales tipos son el enlace iónico (transferencia de electrones), covalente (compartición de electrones) y metálico (nube de electrones deslocalizados).\n\nLa teoría de valencia y la mecánica cuántica explican cómo y por qué se forman estos enlaces. La estructura molecular resultante determina las propiedades físicas y químicas de las sustancias, desde el agua hasta el diamante y los polímeros sintéticos.`,
    content_en: `Chemical bonds are the forces that hold atoms together in molecules and compounds. The main types are ionic bonds (electron transfer), covalent bonds (electron sharing), and metallic bonds (delocalized electron cloud).\n\nValence theory and quantum mechanics explain how and why these bonds form. The resulting molecular structure determines the physical and chemical properties of substances, from water to diamond and synthetic polymers.`,
    excerpt_es: 'Fuerzas que mantienen unidos a los átomos: iónico, covalente y metálico, determinando las propiedades de la materia.',
    excerpt_en: 'Forces holding atoms together: ionic, covalent, and metallic, determining the properties of matter.',
    categoryId: 'cat-chemistry',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'entry-200-168',
    title_es: 'Ácidos, Bases y pH',
    title_en: 'Acids, Bases, and pH',
    slug: 'acidos-bases-y-ph',
    content_es: `Los ácidos y las bases son sustancias con propiedades opuestas: los ácidos donan protones y tienen sabor agrio, mientras que las bases aceptan protones y tienen sabor amargo. La escala de pH mide la acidez o alcalinidad de una solución en un rango de 0 a 14.\n\nLas reacciones de neutralización entre ácidos y bases producen sales y agua. Ácidos como el cítrico y el clorhídrico, y bases como el hidróxido de sodio y el amoniaco, tienen aplicaciones fundamentales en la industria, la medicina y la vida cotidiana.`,
    content_en: `Acids and bases are substances with opposite properties: acids donate protons and taste sour, while bases accept protons and taste bitter. The pH scale measures the acidity or alkalinity of a solution on a range from 0 to 14.\n\nNeutralization reactions between acids and bases produce salts and water. Acids like citric and hydrochloric, and bases like sodium hydroxide and ammonia, have fundamental applications in industry, medicine, and daily life.`,
    excerpt_es: 'Sustancias con propiedades opuestas medidas en la escala de pH, esenciales en química y vida cotidiana.',
    excerpt_en: 'Substances with opposite properties measured on the pH scale, essential in chemistry and daily life.',
    categoryId: 'cat-chemistry',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-02T00:00:00Z',
    updatedAt: '2026-08-02T00:00:00Z',
  },
  {
    id: 'entry-200-169',
    title_es: 'Química Orgánica',
    title_en: 'Organic Chemistry',
    slug: 'quimica-organica',
    content_es: `La química orgánica estudia los compuestos del carbono, que forman la base de la vida conocida. El carbono puede formar cadenas largas y estructuras complejas, dando lugar a una inmensa variedad de moléculas con diferentes grupos funcionales.\n\nLos grupos funcionales como alcoholes, ácidos carboxílicos, aminas y ésteres determinan las propiedades y reactividad de los compuestos orgánicos. Esta rama es fundamental para la bioquímica, la farmacología, los polímeros, los plásticos y la industria petroquímica.`,
    content_en: `Organic chemistry studies carbon compounds, which form the basis of known life. Carbon can form long chains and complex structures, giving rise to an immense variety of molecules with different functional groups.\n\nFunctional groups such as alcohols, carboxylic acids, amines, and esters determine the properties and reactivity of organic compounds. This branch is fundamental for biochemistry, pharmacology, polymers, plastics, and the petrochemical industry.`,
    excerpt_es: 'Estudio de los compuestos del carbono, base de la vida y de innumerables productos industriales.',
    excerpt_en: 'Study of carbon compounds, the basis of life and countless industrial products.',
    categoryId: 'cat-chemistry',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-03T00:00:00Z',
    updatedAt: '2026-08-03T00:00:00Z',
  },
  {
    id: 'entry-200-170',
    title_es: 'Catálisis y Enzimas',
    title_en: 'Catalysis and Enzymes',
    slug: 'catalisis-y-enzimas',
    content_es: `La catálisis es el proceso mediante el cual un catalizador acelera una reacción química sin consumirse en el proceso. Los catalizadores reducen la energía de activación necesaria, permitiendo que las reacciones ocurran más rápida y eficientemente.\n\nLas enzimas son catalizadores biológicos que hacen posibles las reacciones metabólicas en los organismos vivos. Son altamente específicas y eficientes, y tienen innumerables aplicaciones industriales en la producción de alimentos, medicamentos, biocombustibles y detergentes.`,
    content_en: `Catalysis is the process by which a catalyst accelerates a chemical reaction without being consumed in the process. Catalysts reduce the activation energy needed, allowing reactions to occur more quickly and efficiently.\n\nEnzymes are biological catalysts that make metabolic reactions possible in living organisms. They are highly specific and efficient, with countless industrial applications in food production, pharmaceuticals, biofuels, and detergents.`,
    excerpt_es: 'Proceso que acelera reacciones químicas mediante catalizadores, incluyendo las enzimas biológicas.',
    excerpt_en: 'Process that accelerates chemical reactions through catalysts, including biological enzymes.',
    categoryId: 'cat-chemistry',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-04T00:00:00Z',
    updatedAt: '2026-08-04T00:00:00Z',
  },
  {
    id: 'entry-200-171',
    title_es: 'Genética',
    title_en: 'Genetics',
    slug: 'genetica',
    content_es: `La genética es la rama de la biología que estudia los genes, la herencia y la variación en los organismos vivos. Los genes son segmentos de ADN que contienen las instrucciones para desarrollar y mantener un organismo, y se organizan en estructuras llamadas cromosomas.\n\nGregor Mendel sentó las bases de la genética con sus experimentos con guisantes en el siglo XIX, descubriendo las leyes de la segregación y la distribución independiente. Hoy sabemos que el ADN tiene una estructura de doble hélice y que las mutaciones genéticas son la fuente de la variación evolutiva.`,
    content_en: `Genetics is the branch of biology that studies genes, heredity, and variation in living organisms. Genes are segments of DNA containing instructions for developing and maintaining an organism, organized into structures called chromosomes.\n\nGregor Mendel laid the foundations of genetics with his pea experiments in the 19th century, discovering the laws of segregation and independent assortment. Today we know that DNA has a double helix structure and that genetic mutations are the source of evolutionary variation.`,
    excerpt_es: 'Rama de la biología que estudia la herencia genética, los genes y el ADN como portador de la información biológica.',
    excerpt_en: 'Branch of biology studying genetic inheritance, genes, and DNA as the carrier of biological information.',
    categoryId: 'cat-biology',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-05T00:00:00Z',
    updatedAt: '2026-08-05T00:00:00Z',
  },
  {
    id: 'entry-200-172',
    title_es: 'Respiración Celular',
    title_en: 'Cellular Respiration',
    slug: 'respiracion-celular',
    content_es: `La respiración celular es el proceso metabólico por el cual las células convierten la energía química de los nutrientes en ATP, la moneda energética de la vida. Ocurre principalmente en las mitocondrias, los orgánulos conocidos como las centrales energéticas de la célula.\n\nLa respiración aeróbica utiliza oxígeno y produce grandes cantidades de ATP, mientras que la anaeróbica ocurre sin oxígeno y es menos eficiente. Este proceso es fundamental para la supervivencia de casi todos los organismos, desde bacterias hasta seres humanos.`,
    content_en: `Cellular respiration is the metabolic process by which cells convert chemical energy from nutrients into ATP, the energy currency of life. It occurs mainly in the mitochondria, the organelles known as the powerhouses of the cell.\n\nAerobic respiration uses oxygen and produces large amounts of ATP, while anaerobic respiration occurs without oxygen and is less efficient. This process is essential for the survival of nearly all organisms, from bacteria to humans.`,
    excerpt_es: 'Proceso metabólico que produce ATP en las mitocondrias, fundamental para la vida celular.',
    excerpt_en: 'Metabolic process producing ATP in the mitochondria, fundamental for cellular life.',
    categoryId: 'cat-biology',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-06T00:00:00Z',
    updatedAt: '2026-08-06T00:00:00Z',
  },
  {
    id: 'entry-200-173',
    title_es: 'Proyecto Genoma Humano',
    title_en: 'Human Genome Project',
    slug: 'proyecto-genoma-humano',
    content_es: `El Proyecto Genoma Humano fue una colaboración científica internacional que logró secuenciar los aproximadamente 3,000 millones de pares de bases del ADN humano. Comenzó en 1990 y se completó en 2003, dos años antes de lo previsto.\n\nEste proyecto revolucionó la medicina al proporcionar un mapa completo del genoma humano. Ha permitido avances en el diagnóstico de enfermedades genéticas, la medicina personalizada, la farmacogenómica y la comprensión de las bases genéticas de enfermedades complejas como el cáncer y la diabetes.`,
    content_en: `The Human Genome Project was an international scientific collaboration that successfully sequenced the approximately 3 billion base pairs of human DNA. It began in 1990 and was completed in 2003, two years ahead of schedule.\n\nThis project revolutionized medicine by providing a complete map of the human genome. It has enabled advances in genetic disease diagnosis, personalized medicine, pharmacogenomics, and understanding the genetic basis of complex diseases such as cancer and diabetes.`,
    excerpt_es: 'Proyecto internacional que secuenció los 3,000 millones de pares de bases del genoma humano.',
    excerpt_en: 'International project that sequenced the 3 billion base pairs of the human genome.',
    categoryId: 'cat-biology',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-07T00:00:00Z',
    updatedAt: '2026-08-07T00:00:00Z',
  },
  {
    id: 'entry-200-174',
    title_es: 'Sistema Inmunológico',
    title_en: 'Immune System',
    slug: 'sistema-inmunologico',
    content_es: `El sistema inmunológico es la red compleja de células, tejidos y órganos que defiende al cuerpo contra infecciones y enfermedades. Los glóbulos blancos, incluyendo linfocitos y fagocitos, son los soldados que patrullan el organismo en busca de patógenos.\n\nLos anticuerpos son proteínas producidas por los linfocitos B que neutralizan invasores específicos. La vacunación entrena al sistema inmunitario para reconocer patógenos sin causar enfermedad. Las enfermedades autoinmunes ocurren cuando el sistema ataca por error a las células del propio cuerpo.`,
    content_en: `The immune system is the complex network of cells, tissues, and organs that defends the body against infections and diseases. White blood cells, including lymphocytes and phagocytes, are the soldiers that patrol the body looking for pathogens.\n\nAntibodies are proteins produced by B lymphocytes that neutralize specific invaders. Vaccination trains the immune system to recognize pathogens without causing disease. Autoimmune diseases occur when the system mistakenly attacks the body's own cells.`,
    excerpt_es: 'Red de defensa del cuerpo contra infecciones, compuesta por glóbulos blancos, anticuerpos y órganos linfáticos.',
    excerpt_en: 'Body\'s defense network against infections, composed of white blood cells, antibodies, and lymphatic organs.',
    categoryId: 'cat-biology',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-08T00:00:00Z',
    updatedAt: '2026-08-08T00:00:00Z',
  },
  {
    id: 'entry-200-175',
    title_es: 'Infinito',
    title_en: 'Infinity',
    slug: 'infinito',
    content_es: `El infinito es un concepto que describe algo sin límite o sin fin. En matemáticas, Georg Cantor revolucionó la comprensión del infinito al demostrar que existen infinitos de diferentes tamaños, definiendo los números transfinitos y la cardinalidad de los conjuntos.\n\nLas paradojas del infinito, como el hotel de Hilbert que puede albergar infinitos huéspedes incluso cuando está lleno, ilustran las propiedades contraintuitivas de los conjuntos infinitos. Este concepto es fundamental en el análisis matemático, la teoría de conjuntos y la cosmología.`,
    content_en: `Infinity is a concept describing something without limit or end. In mathematics, Georg Cantor revolutionized the understanding of infinity by demonstrating that there are infinities of different sizes, defining transfinite numbers and the cardinality of sets.\n\nParadoxes of infinity, such as Hilbert's hotel which can accommodate infinite guests even when full, illustrate the counterintuitive properties of infinite sets. This concept is fundamental in mathematical analysis, set theory, and cosmology.`,
    excerpt_es: 'Concepto matemático de lo ilimitado, con infinitos de diferentes tamaños descubiertos por Cantor.',
    excerpt_en: 'Mathematical concept of the limitless, with infinities of different sizes discovered by Cantor.',
    categoryId: 'cat-mathematics',
    realityStatus: 'theoretical',
    imageUrl: '',
    createdAt: '2026-08-09T00:00:00Z',
    updatedAt: '2026-08-09T00:00:00Z',
  },
  {
    id: 'entry-200-176',
    title_es: 'Números Primos',
    title_en: 'Prime Numbers',
    slug: 'numeros-primos',
    content_es: `Los números primos son números naturales mayores que 1 que solo son divisibles por sí mismos y por 1. Son los bloques fundamentales de la aritmética, ya que todo número entero puede expresarse como producto único de primos según el teorema fundamental de la aritmética.\n\nSu distribución es uno de los misterios más profundos de las matemáticas, estudiado por la hipótesis de Riemann no resuelta. Los primos son esenciales en criptografía moderna, pues la dificultad de factorizar grandes números primos protege las comunicaciones digitales y las transacciones bancarias.`,
    content_en: `Prime numbers are natural numbers greater than 1 that are only divisible by themselves and 1. They are the fundamental building blocks of arithmetic, since every integer can be expressed as a unique product of primes according to the fundamental theorem of arithmetic.\n\nTheir distribution is one of the deepest mysteries in mathematics, studied through the unsolved Riemann hypothesis. Primes are essential in modern cryptography, as the difficulty of factoring large prime numbers protects digital communications and banking transactions.`,
    excerpt_es: 'Números divisibles solo por sí mismos y la unidad, fundamentales en aritmética y criptografía.',
    excerpt_en: 'Numbers divisible only by themselves and one, fundamental in arithmetic and cryptography.',
    categoryId: 'cat-mathematics',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-10T00:00:00Z',
    updatedAt: '2026-08-10T00:00:00Z',
  },
  {
    id: 'entry-200-177',
    title_es: 'Teoría del Caos',
    title_en: 'Chaos Theory',
    slug: 'teoria-del-caos',
    content_es: `La teoría del caos estudia sistemas dinámicos que son extremadamente sensibles a las condiciones iniciales, dando lugar al famoso efecto mariposa: el aleteo de una mariposa en Brasil puede provocar un tornado en Texas. A pesar de su nombre, el caos tiene un orden subyacente.\n\nLos atractores extraños, como el atractor de Lorenz, representan el comportamiento de sistemas caóticos en el espacio de fases. Esta teoría tiene aplicaciones en meteorología, economía, biología y física, explicando fenómenos que parecen aleatorios pero siguen patrones deterministas complejos.`,
    content_en: `Chaos theory studies dynamical systems that are extremely sensitive to initial conditions, giving rise to the famous butterfly effect: a butterfly flapping in Brazil can cause a tornado in Texas. Despite its name, chaos has an underlying order.\n\nStrange attractors, such as the Lorenz attractor, represent the behavior of chaotic systems in phase space. This theory has applications in meteorology, economics, biology, and physics, explaining phenomena that appear random but follow complex deterministic patterns.`,
    excerpt_es: 'Estudio de sistemas sensibles a condiciones iniciales donde el caos aparente oculta un orden determinista.',
    excerpt_en: 'Study of systems sensitive to initial conditions where apparent chaos hides a deterministic order.',
    categoryId: 'cat-mathematics',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-11T00:00:00Z',
    updatedAt: '2026-08-11T00:00:00Z',
  },
  {
    id: 'entry-200-178',
    title_es: 'Pi (π)',
    title_en: 'Pi (π)',
    slug: 'pi',
    content_es: `Pi (π) es una constante matemática que representa la relación entre la circunferencia de un círculo y su diámetro. Es un número irracional y trascendente, con infinitos decimales que nunca se repiten: 3.1415926535... Su cálculo ha fascinado a matemáticos durante milenios.\n\nArquímedes fue uno de los primeros en aproximar π usando polígonos inscritos y circunscritos. Hoy conocemos billones de decimales gracias a la computación moderna. π aparece en innumerables fórmulas en matemáticas, física e ingeniería, desde la geometría hasta la mecánica cuántica.`,
    content_en: `Pi (π) is a mathematical constant representing the ratio of a circle's circumference to its diameter. It is an irrational and transcendental number with infinite non-repeating decimals: 3.1415926535... Its calculation has fascinated mathematicians for millennia.\n\nArchimedes was among the first to approximate π using inscribed and circumscribed polygons. Today we know trillions of digits thanks to modern computing. π appears in countless formulas in mathematics, physics, and engineering, from geometry to quantum mechanics.`,
    excerpt_es: 'Constante matemática irracional que relaciona la circunferencia con el diámetro, con infinitos decimales.',
    excerpt_en: 'Irrational mathematical constant relating circumference to diameter, with infinite decimal digits.',
    categoryId: 'cat-mathematics',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-12T00:00:00Z',
    updatedAt: '2026-08-12T00:00:00Z',
  },
  {
    id: 'entry-200-179',
    title_es: 'Sistema Solar',
    title_en: 'Solar System',
    slug: 'sistema-solar',
    content_es: `El Sistema Solar es el sistema planetario que contiene a la Tierra, formado por el Sol y todos los cuerpos celestes que orbitan a su alrededor. Incluye ocho planetas, sus lunas, planetas enanos, asteroides, cometas y el medio interplanetario.\n\nSe formó hace unos 4,600 millones de años a partir del colapso de una nube molecular gigante. Más allá de Neptuno se extienden el Cinturón de Kuiper y la Nube de Oort, que contienen cuerpos helados y cometas de período largo. El límite del Sistema Solar está definido por la heliopausa.`,
    content_en: `The Solar System is the planetary system containing Earth, consisting of the Sun and all celestial bodies orbiting around it. It includes eight planets, their moons, dwarf planets, asteroids, comets, and interplanetary medium.\n\nIt formed about 4.6 billion years ago from the collapse of a giant molecular cloud. Beyond Neptune lie the Kuiper Belt and the Oort Cloud, containing icy bodies and long-period comets. The Solar System's boundary is defined by the heliopause.`,
    excerpt_es: 'Sistema planetario que alberga la Tierra, con ocho planetas orbitando alrededor del Sol.',
    excerpt_en: 'Planetary system housing Earth, with eight planets orbiting around the Sun.',
    categoryId: 'cat-astronomy',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-13T00:00:00Z',
    updatedAt: '2026-08-13T00:00:00Z',
  },
  {
    id: 'entry-200-180',
    title_es: 'Exoplanetas',
    title_en: 'Exoplanets',
    slug: 'exoplanetas',
    content_es: `Los exoplanetas son planetas que orbitan estrellas distintas al Sol. El primer exoplaneta confirmado alrededor de una estrella similar al Sol fue descubierto en 1995 por Michel Mayor y Didier Queloz, quienes recibieron el Premio Nobel de Física en 2019.\n\nLos métodos de detección incluyen el tránsito (observar el oscurecimiento periódico de una estrella) y la velocidad radial (detectar el bamboleo gravitacional de la estrella). La misión Kepler ha descubierto miles de exoplanetas, muchos en la zona habitable de sus estrellas, donde podría existir agua líquida.`,
    content_en: `Exoplanets are planets that orbit stars other than the Sun. The first confirmed exoplanet around a Sun-like star was discovered in 1995 by Michel Mayor and Didier Queloz, who received the Nobel Prize in Physics in 2019.\n\nDetection methods include transit (observing periodic dimming of a star) and radial velocity (detecting gravitational wobble of the star). The Kepler mission has discovered thousands of exoplanets, many in the habitable zone of their stars where liquid water could exist.`,
    excerpt_es: 'Planetas que orbitan otras estrellas, descubiertos por métodos de tránsito y velocidad radial.',
    excerpt_en: 'Planets orbiting other stars, discovered through transit and radial velocity methods.',
    categoryId: 'cat-astronomy',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-14T00:00:00Z',
    updatedAt: '2026-08-14T00:00:00Z',
  },
  {
    id: 'entry-200-181',
    title_es: 'Nebulosas',
    title_en: 'Nebulae',
    slug: 'nebulosas',
    content_es: `Las nebulosas son nubes gigantescas de gas y polvo en el espacio interestelar. Funcionan como viveros estelares donde nacen nuevas estrellas a partir del colapso gravitacional de regiones densas. La Nebulosa de Orión es una de las más visibles y estudiadas.\n\nExisten varios tipos: nebulosas de emisión, que brillan con luz propia; nebulosas de reflexión, que reflejan la luz de estrellas cercanas; nebulosas planetarias, formadas por estrellas moribundas; y remanentes de supernova, como la Nebulosa del Cangrejo, restos de explosiones estelares catastróficas.`,
    content_en: `Nebulae are gigantic clouds of gas and dust in interstellar space. They function as stellar nurseries where new stars are born from the gravitational collapse of dense regions. The Orion Nebula is one of the most visible and studied.\n\nSeveral types exist: emission nebulae, which glow with their own light; reflection nebulae, which reflect light from nearby stars; planetary nebulae, formed by dying stars; and supernova remnants, like the Crab Nebula, remains of catastrophic stellar explosions.`,
    excerpt_es: 'Nubes interestelares de gas y polvo donde nacen las estrellas, con diversos tipos según su composición.',
    excerpt_en: 'Interstellar clouds of gas and dust where stars are born, with various types depending on composition.',
    categoryId: 'cat-astronomy',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-15T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z',
  },
  {
    id: 'entry-200-182',
    title_es: 'Cerebro Humano',
    title_en: 'Human Brain',
    slug: 'cerebro-humano',
    content_es: `El cerebro humano es el órgano central del sistema nervioso, responsable del pensamiento, la memoria, las emociones y el control del cuerpo. Contiene aproximadamente 86 mil millones de neuronas interconectadas por sinapsis, formando la red más compleja conocida.\n\nSe divide en lóbulos: frontal (razonamiento y planificación), parietal (sensación táctil), temporal (audición y memoria) y occipital (visión). La plasticidad cerebral permite que el cerebro se reorganice en respuesta a la experiencia, y la conciencia sigue siendo uno de los mayores misterios de la ciencia.`,
    content_en: `The human brain is the central organ of the nervous system, responsible for thought, memory, emotions, and body control. It contains approximately 86 billion neurons interconnected by synapses, forming the most complex known network.\n\nIt is divided into lobes: frontal (reasoning and planning), parietal (tactile sensation), temporal (hearing and memory), and occipital (vision). Brain plasticity allows the brain to reorganize in response to experience, and consciousness remains one of science's greatest mysteries.`,
    excerpt_es: 'Órgano más complejo del cuerpo humano, con 86 mil millones de neuronas y gran plasticidad.',
    excerpt_en: 'Most complex organ in the human body, with 86 billion neurons and great plasticity.',
    categoryId: 'cat-medicine',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-16T00:00:00Z',
    updatedAt: '2026-08-16T00:00:00Z',
  },
  {
    id: 'entry-200-183',
    title_es: 'Secuenciación de ADN',
    title_en: 'DNA Sequencing',
    slug: 'secuenciacion-de-adn',
    content_es: `La secuenciación de ADN es el proceso de determinar el orden exacto de los nucleótidos en una molécula de ADN. La PCR (reacción en cadena de la polimerasa) permite amplificar pequeñas cantidades de ADN para su análisis, y la electroforesis separa fragmentos por tamaño.\n\nEl método Sanger, desarrollado en 1977, fue el estándar durante décadas. Las tecnologías de secuenciación de próxima generación (NGS) han revolucionado el campo, permitiendo secuenciar genomas completos en horas. Esto ha impulsado la genómica, la medicina personalizada y el diagnóstico de enfermedades genéticas.`,
    content_en: `DNA sequencing is the process of determining the exact order of nucleotides in a DNA molecule. PCR (polymerase chain reaction) allows amplifying small amounts of DNA for analysis, and electrophoresis separates fragments by size.\n\nThe Sanger method, developed in 1977, was the standard for decades. Next-generation sequencing (NGS) technologies have revolutionized the field, allowing complete genomes to be sequenced in hours. This has advanced genomics, personalized medicine, and genetic disease diagnosis.`,
    excerpt_es: 'Técnica para determinar el orden de nucleótidos en el ADN, fundamental para la genómica moderna.',
    excerpt_en: 'Technique for determining the order of nucleotides in DNA, fundamental for modern genomics.',
    categoryId: 'cat-medicine',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-17T00:00:00Z',
    updatedAt: '2026-08-17T00:00:00Z',
  },
  {
    id: 'entry-200-184',
    title_es: 'Vacunación',
    title_en: 'Vaccination',
    slug: 'vacunacion',
    content_es: `La vacunación es uno de los mayores logros de la medicina, que consiste en administrar un antígeno para estimular la producción de anticuerpos y generar memoria inmunológica. Edward Jenner realizó la primera vacuna contra la viruela en 1796 usando el virus de la vaccinia.\n\nLas vacunas han erradicado la viruela y controlado enfermedades como la polio, el sarampión y la difteria. La inmunidad de rebaño protege a quienes no pueden vacunarse. Las vacunas de ARNm, como las desarrolladas contra la COVID-19, representan una nueva era en la tecnología de vacunación.`,
    content_en: `Vaccination is one of medicine's greatest achievements, consisting of administering an antigen to stimulate antibody production and generate immunological memory. Edward Jenner performed the first vaccine against smallpox in 1796 using the vaccinia virus.\n\nVaccines have eradicated smallpox and controlled diseases such as polio, measles, and diphtheria. Herd immunity protects those who cannot be vaccinated. mRNA vaccines, such as those developed against COVID-19, represent a new era in vaccine technology.`,
    excerpt_es: 'Método que entrena el sistema inmunitario contra enfermedades, uno de los mayores logros médicos.',
    excerpt_en: 'Method that trains the immune system against diseases, one of medicine\'s greatest achievements.',
    categoryId: 'cat-medicine',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-18T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'entry-200-185',
    title_es: 'Corazón Humano',
    title_en: 'Human Heart',
    slug: 'corazon-humano',
    content_es: `El corazón humano es un órgano muscular del tamaño de un puño que bombea sangre a través del sistema circulatorio. Late aproximadamente 100,000 veces al día, impulsando la sangre oxigenada a todos los tejidos del cuerpo y devolviendo la sangre desoxigenada a los pulmones.\n\nLas enfermedades cardiovasculares son la principal causa de muerte en el mundo. Los trasplantes de corazón, realizados por primera vez por Christiaan Barnard en 1967, han salvado innumerables vidas. La prevención mediante dieta, ejercicio y control de factores de riesgo es fundamental para la salud cardíaca.`,
    content_en: `The human heart is a muscular organ the size of a fist that pumps blood through the circulatory system. It beats approximately 100,000 times a day, pushing oxygenated blood to all body tissues and returning deoxygenated blood to the lungs.\n\nCardiovascular diseases are the leading cause of death worldwide. Heart transplants, first performed by Christiaan Barnard in 1967, have saved countless lives. Prevention through diet, exercise, and risk factor control is essential for heart health.`,
    excerpt_es: 'Órgano muscular que bombea sangre por todo el cuerpo, vital para la vida y foco de las principales enfermedades.',
    excerpt_en: 'Muscular organ pumping blood throughout the body, vital for life and focus of major diseases.',
    categoryId: 'cat-medicine',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-19T00:00:00Z',
    updatedAt: '2026-08-19T00:00:00Z',
  },
  {
    id: 'entry-200-186',
    title_es: 'Arrecifes de Coral',
    title_en: 'Coral Reefs',
    slug: 'arrecifes-de-coral',
    content_es: `Los arrecifes de coral son ecosistemas marinos de enorme biodiversidad, a menudo llamados las selvas tropicales del océano. Están formados por colonias de diminutos pólipos de coral que secretan carbonato de calcio, creando estructuras que albergan aproximadamente el 25% de las especies marinas.\n\nLa Gran Barrera de Coral en Australia es el sistema de arrecifes más grande del mundo. El blanqueamiento del coral, causado por el aumento de la temperatura oceánica, amenaza gravemente estos ecosistemas. La conservación de los arrecifes es crucial para la biodiversidad marina y las comunidades costeras que dependen de ellos.`,
    content_en: `Coral reefs are marine ecosystems of enormous biodiversity, often called the rainforests of the ocean. They are formed by colonies of tiny coral polyps that secrete calcium carbonate, creating structures that harbor approximately 25% of marine species.\n\nThe Great Barrier Reef in Australia is the largest reef system in the world. Coral bleaching, caused by rising ocean temperatures, seriously threatens these ecosystems. Reef conservation is crucial for marine biodiversity and the coastal communities that depend on them.`,
    excerpt_es: 'Ecosistemas marinos con enorme biodiversidad, amenazados por el blanqueamiento debido al cambio climático.',
    excerpt_en: 'Marine ecosystems with enormous biodiversity, threatened by bleaching due to climate change.',
    categoryId: 'cat-nature',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-20T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'entry-200-187',
    title_es: 'Selvas Tropicales',
    title_en: 'Rainforests',
    slug: 'selvas-tropicales',
    content_es: `Las selvas tropicales son bosques densos con alta pluviosidad que albergan más de la mitad de las especies terrestres del planeta. Se caracterizan por su estructura en capas: el dosel superior, el sotobosque y el suelo forestal, cada uno con su propio ecosistema.\n\nEstos ecosistemas regulan el clima global al absorber dióxido de carbono y producir oxígeno. La deforestación, impulsada por la agricultura, la ganadería y la tala ilegal, destruye millones de hectáreas cada año. La pérdida de selvas tropicales representa una crisis para la biodiversidad y el clima mundial.`,
    content_en: `Rainforests are dense forests with high rainfall that harbor more than half of the planet's terrestrial species. They are characterized by their layered structure: the canopy, understory, and forest floor, each with its own ecosystem.\n\nThese ecosystems regulate the global climate by absorbing carbon dioxide and producing oxygen. Deforestation, driven by agriculture, cattle ranching, and illegal logging, destroys millions of hectares each year. The loss of rainforests represents a crisis for biodiversity and the global climate.`,
    excerpt_es: 'Bosques densos con inmensa biodiversidad que regulan el clima y enfrentan una crisis de deforestación.',
    excerpt_en: 'Dense forests with immense biodiversity that regulate the climate and face a deforestation crisis.',
    categoryId: 'cat-nature',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-21T00:00:00Z',
    updatedAt: '2026-08-21T00:00:00Z',
  },
  {
    id: 'entry-200-188',
    title_es: 'Desiertos',
    title_en: 'Deserts',
    slug: 'desiertos',
    content_es: `Los desiertos son regiones áridas que reciben menos de 250 mm de precipitación anual. A pesar de las condiciones extremas, albergan una sorprendente diversidad de vida adaptada a la sequía, como cactus, reptiles, roedores y camellos con adaptaciones únicas.\n\nEl Sahara es el desierto cálido más grande del mundo, mientras que la Atacama en Chile es el más árido. La desertificación, causada por la actividad humana y el cambio climático, expande las áreas desérticas y amenaza los medios de vida de millones de personas en regiones vulnerables.`,
    content_en: `Deserts are arid regions receiving less than 250 mm of annual precipitation. Despite extreme conditions, they harbor surprising diversity of life adapted to drought, such as cacti, reptiles, rodents, and camels with unique adaptations.\n\nThe Sahara is the largest hot desert in the world, while the Atacama in Chile is the driest. Desertification, caused by human activity and climate change, expands desert areas and threatens the livelihoods of millions of people in vulnerable regions.`,
    excerpt_es: 'Regiones áridas con vida adaptada a la sequía extrema, amenazadas por la desertificación global.',
    excerpt_en: 'Arid regions with life adapted to extreme drought, threatened by global desertification.',
    categoryId: 'cat-nature',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-22T00:00:00Z',
    updatedAt: '2026-08-22T00:00:00Z',
  },
  {
    id: 'entry-200-189',
    title_es: 'Glaciares',
    title_en: 'Glaciers',
    slug: 'glaciares',
    content_es: `Los glaciares son masas de hielo en movimiento que se forman por la acumulación y compactación de nieve durante siglos. Son indicadores cruciales del cambio climático, ya que su retroceso refleja el aumento global de las temperaturas.\n\nLos glaciares de la Patagonia y Groenlandia están entre los más grandes del mundo. El derretimiento glaciar contribuye al aumento del nivel del mar, amenazando ciudades costeras. Además, los glaciares almacenan aproximadamente el 69% del agua dulce del planeta, y su desaparición afectaría el suministro de agua para millones de personas.`,
    content_en: `Glaciers are moving masses of ice formed by the accumulation and compaction of snow over centuries. They are crucial indicators of climate change, as their retreat reflects rising global temperatures.\n\nThe glaciers of Patagonia and Greenland are among the largest in the world. Glacial melting contributes to sea level rise, threatening coastal cities. Additionally, glaciers store approximately 69% of the planet's fresh water, and their disappearance would affect water supply for millions of people.`,
    excerpt_es: 'Masas de hielo indicadoras del cambio climático, vitales para el suministro global de agua dulce.',
    excerpt_en: 'Ice masses serving as climate change indicators, vital for the global fresh water supply.',
    categoryId: 'cat-nature',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-23T00:00:00Z',
    updatedAt: '2026-08-23T00:00:00Z',
  },
  {
    id: 'entry-200-190',
    title_es: 'Océano Profundo',
    title_en: 'Deep Ocean',
    slug: 'oceano-profundo',
    content_es: `El océano profundo comienza donde la luz solar no penetra, aproximadamente a 200 metros de profundidad. La zona hadal, que incluye la Fosa de las Marianas, es la región más profunda del océano, alcanzando casi 11,000 metros en el Abismo Challenger.\n\nLos respiraderos hidrotermales albergan ecosistemas únicos basados en quimiosíntesis, donde bacterias convierten compuestos minerales en energía. Los extremófilos que habitan estas profundidades han ampliado nuestra comprensión de los límites de la vida y las posibilidades de vida extraterrestre.`,
    content_en: `The deep ocean begins where sunlight does not penetrate, approximately 200 meters deep. The hadal zone, including the Mariana Trench, is the deepest ocean region, reaching nearly 11,000 meters at Challenger Deep.\n\nHydrothermal vents host unique ecosystems based on chemosynthesis, where bacteria convert mineral compounds into energy. The extremophiles inhabiting these depths have expanded our understanding of the limits of life and the possibilities of extraterrestrial life.`,
    excerpt_es: 'Regiones oceánicas más profundas con ecosistemas únicos basados en quimiosíntesis y extremófilos.',
    excerpt_en: 'Deepest ocean regions with unique ecosystems based on chemosynthesis and extremophiles.',
    categoryId: 'cat-nature',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-24T00:00:00Z',
    updatedAt: '2026-08-24T00:00:00Z',
  },
  {
    id: 'entry-200-191',
    title_es: 'Sigmund Freud',
    title_en: 'Sigmund Freud',
    slug: 'sigmund-freud',
    content_es: `Sigmund Freud fue el fundador del psicoanálisis, una de las corrientes más influyentes de la psicología. Desarrolló teorías revolucionarias sobre el inconsciente, la interpretación de los sueños y la estructura de la psique dividida en Ello, Yo y Superyó.\n\nFreud propuso que los conflictos psicológicos tienen raíces en experiencias infantiles reprimidas. Sus métodos terapéuticos, como la asociación libre y el análisis de los sueños, buscaban traer el material inconsciente a la conciencia. Aunque controvertido, su legado transformó la comprensión de la mente humana.`,
    content_en: `Sigmund Freud was the founder of psychoanalysis, one of the most influential schools of psychology. He developed revolutionary theories about the unconscious, dream interpretation, and the structure of the psyche divided into Id, Ego, and Superego.\n\nFreud proposed that psychological conflicts have roots in repressed childhood experiences. His therapeutic methods, such as free association and dream analysis, sought to bring unconscious material to consciousness. Although controversial, his legacy transformed the understanding of the human mind.`,
    excerpt_es: 'Fundador del psicoanálisis, revolucionó la psicología con sus teorías del inconsciente y la interpretación de sueños.',
    excerpt_en: 'Founder of psychoanalysis who revolutionized psychology with theories of the unconscious and dream interpretation.',
    categoryId: 'cat-psychology',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-08-25T00:00:00Z',
    updatedAt: '2026-08-25T00:00:00Z',
  },
  {
    id: 'entry-200-192',
    title_es: 'Carl Jung',
    title_en: 'Carl Jung',
    slug: 'carl-jung',
    content_es: `Carl Gustav Jung fue un psiquiatra suizo fundador de la psicología analítica. Desarrolló los conceptos de inconsciente colectivo y arquetipos, patrones universales de pensamiento y comportamiento que emergen de la herencia psicológica compartida de la humanidad.\n\nJung propuso el proceso de individuación como el camino hacia la realización personal, integrando los aspectos conscientes e inconscientes de la personalidad. Sus arquetipos incluyen la Sombra, el Ánima/Ánimus y el Sí-mismo. Su obra influyó en la psicología, la literatura, el arte y los estudios religiosos.`,
    content_en: `Carl Gustav Jung was a Swiss psychiatrist who founded analytical psychology. He developed the concepts of the collective unconscious and archetypes, universal patterns of thought and behavior emerging from humanity's shared psychological heritage.\n\nJung proposed the process of individuation as the path to personal fulfillment, integrating conscious and unconscious aspects of personality. His archetypes include the Shadow, the Anima/Animus, and the Self. His work influenced psychology, literature, art, and religious studies.`,
    excerpt_es: 'Fundador de la psicología analítica, desarrolló los conceptos de inconsciente colectivo y arquetipos universales.',
    excerpt_en: 'Founder of analytical psychology who developed the concepts of collective unconscious and universal archetypes.',
    categoryId: 'cat-psychology',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'entry-200-193',
    title_es: 'B.F. Skinner',
    title_en: 'B.F. Skinner',
    slug: 'bf-skinner',
    content_es: `Burrhus Frederic Skinner fue uno de los psicólogos más influyentes del siglo XX y el principal exponente del conductismo radical. Desarrolló la teoría del condicionamiento operante, donde el comportamiento es moldeado por sus consecuencias mediante refuerzos y castigos.\n\nLa caja de Skinner es un dispositivo experimental que demostró cómo los animales aprenden mediante refuerzo. Skinner creía que el comportamiento humano podía explicarse completamente por la historia de refuerzos, rechazando explicaciones basadas en estados mentales internos. Su trabajo influyó en la educación, la terapia y el diseño de sistemas de aprendizaje.`,
    content_en: `Burrhus Frederic Skinner was one of the most influential psychologists of the 20th century and the leading proponent of radical behaviorism. He developed operant conditioning theory, where behavior is shaped by its consequences through reinforcements and punishments.\n\nThe Skinner box is an experimental device that demonstrated how animals learn through reinforcement. Skinner believed that human behavior could be fully explained by reinforcement history, rejecting explanations based on internal mental states. His work influenced education, therapy, and learning system design.`,
    excerpt_es: 'Principal exponente del conductismo, desarrolló la teoría del condicionamiento operante mediante refuerzos.',
    excerpt_en: 'Leading proponent of behaviorism who developed operant conditioning theory through reinforcement.',
    categoryId: 'cat-psychology',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-08-27T00:00:00Z',
    updatedAt: '2026-08-27T00:00:00Z',
  },
  {
    id: 'entry-200-194',
    title_es: 'Terapia Cognitivo-Conductual',
    title_en: 'Cognitive Behavioral Therapy',
    slug: 'terapia-cognitivo-conductual',
    content_es: `La Terapia Cognitivo-Conductual (TCC) es una forma de psicoterapia basada en la interconexión entre pensamientos, emociones y comportamientos. Desarrollada por Aaron Beck en la década de 1960, se ha convertido en uno de los tratamientos más efectivos para la depresión, ansiedad y otros trastornos.\n\nLa TCC ayuda a identificar y modificar patrones de pensamiento distorsionados y comportamientos disfuncionales. Es una terapia breve, estructurada y orientada a objetivos, respaldada por numerosos estudios científicos. Su enfoque práctico la hace especialmente efectiva y accesible para una amplia variedad de problemas psicológicos.`,
    content_en: `Cognitive Behavioral Therapy (CBT) is a form of psychotherapy based on the interconnection between thoughts, emotions, and behaviors. Developed by Aaron Beck in the 1960s, it has become one of the most effective treatments for depression, anxiety, and other disorders.\n\nCBT helps identify and modify distorted thinking patterns and dysfunctional behaviors. It is a brief, structured, goal-oriented therapy supported by numerous scientific studies. Its practical approach makes it especially effective and accessible for a wide variety of psychological problems.`,
    excerpt_es: 'Psicoterapia efectiva basada en la relación entre pensamientos, emociones y comportamientos, desarrollada por Beck.',
    excerpt_en: 'Effective psychotherapy based on the relationship between thoughts, emotions, and behaviors, developed by Beck.',
    categoryId: 'cat-psychology',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-08-28T00:00:00Z',
    updatedAt: '2026-08-28T00:00:00Z',
  },
  {
    id: 'entry-200-195',
    title_es: 'Arte Renacentista',
    title_en: 'Renaissance Art',
    slug: 'arte-renacentista',
    content_es: `El arte renacentista floreció en Europa entre los siglos XIV y XVII, marcando un renacimiento cultural tras la Edad Media. Se caracterizó por la recuperación de la perspectiva lineal, el humanismo, el naturalismo y la idealización de la belleza clásica.\n\nLeonardo da Vinci, Rafael y Miguel Ángel son los gigantes del Renacimiento. Obras como la Mona Lisa, la Escuela de Atenas y la Capilla Sixtina representan la cumbre del logro artístico. El Renacimiento transformó el arte al colocar al ser humano en el centro de la representación.`,
    content_en: `Renaissance art flourished in Europe between the 14th and 17th centuries, marking a cultural rebirth after the Middle Ages. It was characterized by the recovery of linear perspective, humanism, naturalism, and the idealization of classical beauty.\n\nLeonardo da Vinci, Raphael, and Michelangelo are the giants of the Renaissance. Works like the Mona Lisa, the School of Athens, and the Sistine Chapel represent the pinnacle of artistic achievement. The Renaissance transformed art by placing the human being at the center of representation.`,
    excerpt_es: 'Movimiento artístico del Renacimiento con perspectiva, humanismo y maestros como Da Vinci y Miguel Ángel.',
    excerpt_en: 'Renaissance artistic movement with perspective, humanism, and masters like Da Vinci and Michelangelo.',
    categoryId: 'cat-arts',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-08-29T00:00:00Z',
    updatedAt: '2026-08-29T00:00:00Z',
  },
  {
    id: 'entry-200-196',
    title_es: 'Impresionismo',
    title_en: 'Impressionism',
    slug: 'impresionismo',
    content_es: `El impresionismo fue un movimiento artístico revolucionario que surgió en Francia a finales del siglo XIX. Los impresionistas buscaban capturar la luz y el color en el momento presente, pintando al aire libre y usando pinceladas sueltas y rápidas.\n\nClaude Monet, Pierre-Auguste Renoir y Edgar Degas fueron figuras clave. La obra Impresión, sol naciente de Monet dio nombre al movimiento. Inicialmente rechazado por la academia, el impresionismo rompió con las tradiciones artísticas establecidas y allanó el camino para el arte moderno del siglo XX.`,
    content_en: `Impressionism was a revolutionary artistic movement that emerged in France in the late 19th century. Impressionists sought to capture light and color in the present moment, painting outdoors using loose, rapid brushstrokes.\n\nClaude Monet, Pierre-Auguste Renoir, and Edgar Degas were key figures. Monet's work Impression, Sunrise gave the movement its name. Initially rejected by the academy, impressionism broke with established artistic traditions and paved the way for 20th century modern art.`,
    excerpt_es: 'Movimiento artístico que revolucionó la pintura al capturar la luz y el color con pinceladas sueltas.',
    excerpt_en: 'Artistic movement that revolutionized painting by capturing light and color with loose brushstrokes.',
    categoryId: 'cat-arts',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-08-30T00:00:00Z',
    updatedAt: '2026-08-30T00:00:00Z',
  },
  {
    id: 'entry-200-197',
    title_es: 'William Shakespeare',
    title_en: 'William Shakespeare',
    slug: 'william-shakespeare',
    content_es: `William Shakespeare (1564-1616) es ampliamente considerado el escritor más importante de la lengua inglesa y uno de los más grandes dramaturgos de la historia universal. Sus obras exploran las pasiones humanas universales: el amor, los celos, la ambición, la traición y la muerte.\n\nEscribió 37 obras de teatro, 154 sonetos y varios poemas. Obras como Hamlet, Romeo y Julieta, Macbeth y Otelo se representan continuamente en todo el mundo. Shakespeare acuñó cientos de palabras y expresiones que aún usamos hoy, y su influencia en la literatura, el teatro y el cine es incalculable.`,
    content_en: `William Shakespeare (1564-1616) is widely regarded as the most important writer in the English language and one of the greatest playwrights in universal history. His works explore universal human passions: love, jealousy, ambition, betrayal, and death.\n\nHe wrote 37 plays, 154 sonnets, and several poems. Works like Hamlet, Romeo and Juliet, Macbeth, and Othello are performed continuously around the world. Shakespeare coined hundreds of words and expressions still used today, and his influence on literature, theater, and film is incalculable.`,
    excerpt_es: 'El dramaturgo más importante de la lengua inglesa, autor de Hamlet, Romeo y Julieta y otras obras universales.',
    excerpt_en: 'The most important playwright in the English language, author of Hamlet, Romeo and Juliet, and other universal works.',
    categoryId: 'cat-literature',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-08-31T00:00:00Z',
    updatedAt: '2026-08-31T00:00:00Z',
  },
  {
    id: 'entry-200-198',
    title_es: 'Cien Años de Soledad',
    title_en: 'One Hundred Years of Solitude',
    slug: 'cien-anos-de-soledad',
    content_es: `Cien Años de Soledad es la obra maestra del escritor colombiano Gabriel García Márquez, publicada en 1967. Es la novela más representativa del realismo mágico y una de las más importantes de la literatura universal del siglo XX.\n\nNarra la historia de la familia Buendía a lo largo de siete generaciones en el pueblo ficticio de Macondo. La novela entrelaza lo real y lo fantástico, explorando temas como el amor, el poder, la memoria y la soledad. García Márquez recibió el Premio Nobel de Literatura en 1982, y su obra ha vendido más de 30 millones de ejemplares.`,
    content_en: `One Hundred Years of Solitude is the masterpiece of Colombian writer Gabriel García Márquez, published in 1967. It is the most representative novel of magical realism and one of the most important works of 20th century universal literature.\n\nIt tells the story of the Buendía family over seven generations in the fictional town of Macondo. The novel intertwines the real and the fantastic, exploring themes of love, power, memory, and solitude. García Márquez received the Nobel Prize in Literature in 1982, and his work has sold over 30 million copies.`,
    excerpt_es: 'Obra maestra de García Márquez que narra la saga de la familia Buendía en Macondo, cumbre del realismo mágico.',
    excerpt_en: 'García Márquez\'s masterpiece narrating the Buendía family saga in Macondo, peak of magical realism.',
    categoryId: 'cat-literature',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'entry-200-199',
    title_es: '1984 de George Orwell',
    title_en: '1984 by George Orwell',
    slug: '1984-de-george-orwell',
    content_es: `1984 es una novela distópica escrita por George Orwell y publicada en 1949. Presenta un mundo totalitario donde el Partido Único controla todos los aspectos de la vida bajo la vigilancia constante del Gran Hermano, y donde la historia se reescribe para mantener el poder.\n\nOrwell introdujo conceptos que se han vuelto icónicos: el doblepensar, la neolengua, la policía del pensamiento y la sala 101. La novela es una poderosa advertencia contra la vigilancia masiva, la manipulación de la verdad y la erosión de las libertades civiles, temas de extraordinaria relevancia en la era digital.`,
    content_en: `1984 is a dystopian novel written by George Orwell and published in 1949. It presents a totalitarian world where the Single Party controls all aspects of life under the constant surveillance of Big Brother, and where history is rewritten to maintain power.\n\nOrwell introduced concepts that have become iconic: doublethink, newspeak, the thought police, and room 101. The novel is a powerful warning against mass surveillance, manipulation of truth, and erosion of civil liberties, themes of extraordinary relevance in the digital age.`,
    excerpt_es: 'Novela distópica de Orwell que advierte sobre el totalitarismo, la vigilancia masiva y la manipulación de la verdad.',
    excerpt_en: 'Orwell\'s dystopian novel warning against totalitarianism, mass surveillance, and manipulation of truth.',
    categoryId: 'cat-literature',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-09-02T00:00:00Z',
    updatedAt: '2026-09-02T00:00:00Z',
  },
  {
    id: 'entry-200-200',
    title_es: 'Inteligencia Artificial',
    title_en: 'Artificial Intelligence',
    slug: 'inteligencia-artificial',
    content_es: `La inteligencia artificial (IA) es la rama de la informática que busca crear sistemas capaces de realizar tareas que requieren inteligencia humana, como el aprendizaje, el razonamiento, la percepción y la toma de decisiones. El machine learning permite que los sistemas mejoren automáticamente con la experiencia.\n\nLas redes neuronales profundas han revolucionado campos como la visión por computadora, el procesamiento del lenguaje natural y los juegos. El desarrollo hacia la inteligencia general artificial (AGI) plantea profundas preguntas éticas sobre el futuro de la humanidad, el trabajo, la privacidad y el control de tecnologías avanzadas.`,
    content_en: `Artificial intelligence (AI) is the branch of computer science that seeks to create systems capable of performing tasks requiring human intelligence, such as learning, reasoning, perception, and decision-making. Machine learning enables systems to automatically improve with experience.\n\nDeep neural networks have revolutionized fields such as computer vision, natural language processing, and gaming. The development toward artificial general intelligence (AGI) raises profound ethical questions about humanity's future, work, privacy, and the control of advanced technologies.`,
    excerpt_es: 'Rama de la informática que crea sistemas inteligentes, desde machine learning hasta el desafío de la AGI.',
    excerpt_en: 'Branch of computer science creating intelligent systems, from machine learning to the challenge of AGI.',
    categoryId: 'cat-technology',
    realityStatus: 'scientific',
    imageUrl: '',
    createdAt: '2026-09-03T00:00:00Z',
    updatedAt: '2026-09-03T00:00:00Z',
  },
]
