import { SeedEntry } from '../seed'

export const entries200Pt1: SeedEntry[] = [
  {
    id: 'entry-200-01',
    title_es: 'Sumeria',
    title_en: 'Sumeria',
    slug: 'sumeria',
    content_es: `Sumeria, ubicada en la región de Mesopotamia entre los ríos Tigris y Éufrates, es considerada la primera civilización de la historia. Surgió alrededor del 4000 a.C. y desarrolló la escritura cuneiforme, uno de los primeros sistemas de escritura conocidos.\n\nLos sumerios organizaron su sociedad en ciudades-estado independientes como Ur, Uruk y Lagash. Establecieron avanzados sistemas de irrigación, templos zigurat y un código legal. Su influencia cultural y tecnológica sentó las bases para las civilizaciones posteriores de la región.`,
    content_en: `Sumeria, located in the region of Mesopotamia between the Tigris and Euphrates rivers, is considered the first civilization in history. It emerged around 4000 BCE and developed cuneiform writing, one of the earliest known writing systems.\n\nThe Sumerians organized their society into independent city-states such as Ur, Uruk, and Lagash. They established advanced irrigation systems, ziggurat temples, and a legal code. Their cultural and technological influence laid the foundations for later civilizations in the region.`,
    excerpt_es: 'Primera civilización de la historia que desarrolló la escritura cuneiforme y las primeras ciudades-estado en Mesopotamia.',
    excerpt_en: 'First civilization in history that developed cuneiform writing and the first city-states in Mesopotamia.',
    categoryId: 'cat-ancient-civs',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'entry-200-02',
    title_es: 'Civilización del Valle del Indo',
    title_en: 'Indus Valley Civilization',
    slug: 'civilizacion-valle-del-indo',
    content_es: `La Civilización del Valle del Indo floreció entre el 3300 y 1300 a.C. en lo que hoy es Pakistán y el noroeste de la India. Sus principales ciudades, Harappa y Mohenjo-Daro, muestran un avanzado urbanismo con calles planificadas en cuadrícula y sistemas de drenaje sofisticados.\n\nEsta civilización desarrolló un sistema de escritura aún no descifrado y mantuvo extensas redes comerciales con Mesopotamia. Su declive sigue siendo un misterio, posiblemente debido a cambios climáticos o desviaciones de ríos. Su legado perdura en la cultura del sur de Asia.`,
    content_en: `The Indus Valley Civilization flourished between 3300 and 1300 BCE in what is now Pakistan and northwestern India. Its main cities, Harappa and Mohenjo-Daro, display advanced urban planning with grid-patterned streets and sophisticated drainage systems.\n\nThis civilization developed a writing system still undeciphered and maintained extensive trade networks with Mesopotamia. Its decline remains a mystery, possibly due to climate change or river shifts. Its legacy endures in South Asian culture.`,
    excerpt_es: 'Civilización avanzada del sur de Asia conocida por su urbanismo planificado y las ciudades de Harappa y Mohenjo-Daro.',
    excerpt_en: 'Advanced South Asian civilization known for its planned urbanism and the cities of Harappa and Mohenjo-Daro.',
    categoryId: 'cat-ancient-civs',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-02T00:00:00Z',
    updatedAt: '2026-06-02T00:00:00Z',
  },
  {
    id: 'entry-200-03',
    title_es: 'Imperio Babilónico',
    title_en: 'Babylonian Empire',
    slug: 'imperio-babilonico',
    content_es: `El Imperio Babilónico alcanzó su apogeo bajo el reinado de Hammurabi, quien unificó Mesopotamia y promulgó el famoso Código de Hammurabi, uno de los primeros conjuntos de leyes escritas de la humanidad. Babilonia se convirtió en un centro cultural y religioso sin precedentes.\n\nNabucodonosor II engrandeció la ciudad con los Jardines Colgantes, una de las Siete Maravillas del Mundo Antiguo. Babilonia fue un símbolo de poderío y civilización hasta su caída ante los persas en el 539 a.C.`,
    content_en: `The Babylonian Empire reached its height under King Hammurabi, who unified Mesopotamia and enacted the famous Code of Hammurabi, one of the earliest written legal codes in history. Babylon became an unparalleled cultural and religious center.\n\nNebuchadnezzar II expanded the city with the Hanging Gardens, one of the Seven Wonders of the Ancient World. Babylon stood as a symbol of power and civilization until its fall to the Persians in 539 BCE.`,
    excerpt_es: 'Imperio mesopotámico conocido por el Código de Hammurabi, los Jardines Colgantes y el reinado de Nabucodonosor.',
    excerpt_en: 'Mesopotamian empire known for the Code of Hammurabi, the Hanging Gardens, and the reign of Nebuchadnezzar.',
    categoryId: 'cat-ancient-civs',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-03T00:00:00Z',
    updatedAt: '2026-06-03T00:00:00Z',
  },
  {
    id: 'entry-200-04',
    title_es: 'Imperio Asirio',
    title_en: 'Assyrian Empire',
    slug: 'imperio-asirio',
    content_es: `El Imperio Asirio fue una potencia militar dominante en el Cercano Oriente entre los siglos XIV y VII a.C. Conocidos por su poderoso ejército y tácticas brutales, los asirios construyeron un vasto imperio desde su capital en Nínive.\n\nEl rey Ashurbanipal fundó la famosa Biblioteca de Nínive, que preservó miles de tablillas cuneiformes de toda Mesopotamia. El Imperio Asirio cayó en el 612 a.C. tras la alianza de babilonios y medos que destruyó Nínive.`,
    content_en: `The Assyrian Empire was a dominant military power in the Near East between the 14th and 7th centuries BCE. Known for their powerful army and brutal tactics, the Assyrians built a vast empire from their capital at Nineveh.\n\nKing Ashurbanipal founded the famous Library of Nineveh, which preserved thousands of cuneiform tablets from across Mesopotamia. The Assyrian Empire fell in 612 BCE after an alliance of Babylonians and Medes destroyed Nineveh.`,
    excerpt_es: 'Potencia militar de la antigua Mesopotamia conocida por su ejército y la biblioteca de Asurbanipal en Nínive.',
    excerpt_en: 'Ancient Mesopotamian military power known for its army and the Library of Ashurbanipal in Nineveh.',
    categoryId: 'cat-ancient-civs',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-04T00:00:00Z',
    updatedAt: '2026-06-04T00:00:00Z',
  },
  {
    id: 'entry-200-05',
    title_es: 'Imperio Persa Aqueménida',
    title_en: 'Achaemenid Persian Empire',
    slug: 'imperio-persa-aquemenida',
    content_es: `El Imperio Persa Aqueménida fue fundado por Ciro el Grande en el siglo VI a.C. y se convirtió en el imperio más extenso de la antigüedad, abarcando desde la India hasta los Balcanes. Ciro es recordado por su política de tolerancia religiosa y la liberación de los judíos en Babilonia.\n\nDarío I organizó el imperio en satrapías, construyó el Camino Real Persa e inició las Guerras Médicas contra Grecia. El imperio cayó ante Alejandro Magno en el 330 a.C., pero su legado administrativo y cultural perduró por siglos.`,
    content_en: `The Achaemenid Persian Empire was founded by Cyrus the Great in the 6th century BCE and became the largest empire of antiquity, spanning from India to the Balkans. Cyrus is remembered for his policy of religious tolerance and the liberation of the Jews in Babylon.\n\nDarius I organized the empire into satrapies, built the Royal Road, and initiated the Greco-Persian Wars. The empire fell to Alexander the Great in 330 BCE, but its administrative and cultural legacy endured for centuries.`,
    excerpt_es: 'El imperio más extenso de la antigüedad fundado por Ciro el Grande, conocido por su administración y tolerancia cultural.',
    excerpt_en: 'The largest empire of antiquity founded by Cyrus the Great, known for its administration and cultural tolerance.',
    categoryId: 'cat-ancient-civs',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-05T00:00:00Z',
    updatedAt: '2026-06-05T00:00:00Z',
  },
  {
    id: 'entry-200-06',
    title_es: 'China Antigua: Shang y Zhou',
    title_en: 'Ancient China: Shang and Zhou',
    slug: 'china-antigua-shang-zhou',
    content_es: `La dinastía Shang gobernó China desde aproximadamente el 1600 a.C. y dejó los primeros registros escritos del país mediante inscripciones en huesos oraculares. Estos huesos revelan prácticas de adivinación y la estructura de una sociedad jerárquica centrada en el culto a los ancestros.\n\nLa dinastía Zhou sucedió a los Shang e introdujo el concepto del Mandato del Cielo, que justificaba el gobierno del emperador. Esta época también vio el desarrollo de la metalurgia del bronce y los cimientos de la filosofía china que florecería en siglos posteriores.`,
    content_en: `The Shang dynasty ruled China from approximately 1600 BCE and left the country's earliest written records through inscriptions on oracle bones. These bones reveal divination practices and a hierarchical society centered on ancestor worship.\n\nThe Zhou dynasty succeeded the Shang and introduced the concept of the Mandate of Heaven, which justified the emperor's rule. This period also saw the development of bronze metallurgy and the foundations of Chinese philosophy that would flourish in later centuries.`,
    excerpt_es: 'Primeras dinastías chinas que establecieron la escritura, el Mandato del Cielo y la metalurgia del bronce.',
    excerpt_en: 'Early Chinese dynasties that established writing, the Mandate of Heaven, and bronze metallurgy.',
    categoryId: 'cat-ancient-civs',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-06T00:00:00Z',
    updatedAt: '2026-06-06T00:00:00Z',
  },
  {
    id: 'entry-200-07',
    title_es: 'Antigua Grecia',
    title_en: 'Ancient Greece',
    slug: 'antigua-grecia',
    content_es: `La Antigua Grecia fue una civilización que floreció desde el siglo VIII a.C. y sentó las bases de la cultura occidental. Sus ciudades-estado, como Atenas y Esparta, experimentaron con formas de gobierno como la democracia, la oligarquía y la monarquía.\n\nEl período helénico produjo avances en filosofía con Sócrates, Platón y Aristóteles, en arte con la escultura clásica, y en literatura con Homero. La cultura griega se expandió por el Mediterráneo y su legado sigue vigente en la política, la ciencia y las artes.`,
    content_en: `Ancient Greece was a civilization that flourished from the 8th century BCE and laid the foundations of Western culture. Its city-states, such as Athens and Sparta, experimented with forms of government including democracy, oligarchy, and monarchy.\n\nThe Hellenic period produced advances in philosophy with Socrates, Plato, and Aristotle, in art with classical sculpture, and in literature with Homer. Greek culture spread throughout the Mediterranean and its legacy continues in politics, science, and the arts.`,
    excerpt_es: 'Civilización fundacional de Occidente que desarrolló la democracia, la filosofía clásica y un arte sin precedentes.',
    excerpt_en: 'Foundational Western civilization that developed democracy, classical philosophy, and unprecedented art.',
    categoryId: 'cat-classical',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-07T00:00:00Z',
    updatedAt: '2026-06-07T00:00:00Z',
  },
  {
    id: 'entry-200-08',
    title_es: 'Imperio Romano',
    title_en: 'Roman Empire',
    slug: 'imperio-romano',
    content_es: `El Imperio Romano comenzó como una república en el siglo VI a.C. y se transformó en un imperio bajo Augusto en el 27 a.C. Durante la Pax Romana, el imperio alcanzó su máxima extensión, abarcando el Mediterráneo y gran parte de Europa, el norte de África y Oriente Próximo.\n\nRoma legó al mundo el derecho romano, el latín, la ingeniería de acueductos y calzadas, y la difusión del cristianismo. El imperio cayó en Occidente en el 476 d.C., pero su influencia perdura en las instituciones políticas, legales y culturales de Occidente.`,
    content_en: `The Roman Empire began as a republic in the 6th century BCE and transformed into an empire under Augustus in 27 BCE. During the Pax Romana, the empire reached its greatest extent, encompassing the Mediterranean and much of Europe, North Africa, and the Near East.\n\nRome bequeathed to the world Roman law, Latin, aqueduct and road engineering, and the spread of Christianity. The empire fell in the West in 476 CE, but its influence endures in Western political, legal, and cultural institutions.`,
    excerpt_es: 'Imperio que dominó el Mediterráneo y legó el derecho romano, el latín y la base del mundo occidental.',
    excerpt_en: 'Empire that dominated the Mediterranean and bequeathed Roman law, Latin, and the foundation of the Western world.',
    categoryId: 'cat-classical',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-08T00:00:00Z',
    updatedAt: '2026-06-08T00:00:00Z',
  },
  {
    id: 'entry-200-09',
    title_es: 'Imperio Macedonio de Alejandro Magno',
    title_en: 'Macedonian Empire of Alexander the Great',
    slug: 'imperio-macedonio-alejandro-magno',
    content_es: `Alejandro Magno, rey de Macedonia, conquistó un vasto imperio que se extendía desde Grecia hasta la India en apenas trece años. Su imperio unificó Oriente y Occidente como nunca antes, fusionando las culturas griega y persa en el período helenístico.\n\nTras su muerte en el 323 a.C., el imperio se fragmentó entre sus generales, los diádocos. Sin embargo, la difusión de la lengua y cultura griega por todo el Mediterráneo oriental y Asia Central transformó profundamente el mundo antiguo y preparó el terreno para el Imperio Romano.`,
    content_en: `Alexander the Great, king of Macedonia, conquered a vast empire stretching from Greece to India in just thirteen years. His empire united East and West as never before, blending Greek and Persian cultures in the Hellenistic period.\n\nAfter his death in 323 BCE, the empire fragmented among his generals, the Diadochi. However, the spread of Greek language and culture throughout the eastern Mediterranean and Central Asia profoundly transformed the ancient world and prepared the ground for the Roman Empire.`,
    excerpt_es: 'Imperio creado por Alejandro Magno que fusionó las culturas griega y persa durante el período helenístico.',
    excerpt_en: 'Empire created by Alexander the Great that blended Greek and Persian cultures during the Hellenistic period.',
    categoryId: 'cat-classical',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-09T00:00:00Z',
    updatedAt: '2026-06-09T00:00:00Z',
  },
  {
    id: 'entry-200-10',
    title_es: 'Edad de Oro del Islam',
    title_en: 'Islamic Golden Age',
    slug: 'edad-de-oro-del-islam',
    content_es: `La Edad de Oro del Islam, entre los siglos VIII y XIII, fue un período de florecimiento cultural, científico y económico en el mundo islámico. Los califatos abasí y omeya patrocinaron la traducción y preservación del conocimiento clásico griego, persa e indio.\n\nLa Casa de la Sabiduría en Bagdad fue el epicentro intelectual donde se realizaron avances en matemáticas, astronomía, medicina y filosofía. Figuras como Al-Juarismi, Avicena y Averroes hicieron contribuciones fundamentales que más tarde impulsarían el Renacimiento europeo.`,
    content_en: `The Islamic Golden Age, between the 8th and 13th centuries, was a period of cultural, scientific, and economic flourishing in the Islamic world. The Abbasid and Umayyad caliphates sponsored the translation and preservation of classical Greek, Persian, and Indian knowledge.\n\nThe House of Wisdom in Baghdad was the intellectual epicenter where advances were made in mathematics, astronomy, medicine, and philosophy. Figures like Al-Khwarizmi, Avicenna, and Averroes made fundamental contributions that later fueled the European Renaissance.`,
    excerpt_es: 'Período de florecimiento científico y cultural en el mundo islámico con avances en matemáticas, medicina y filosofía.',
    excerpt_en: 'Period of scientific and cultural flourishing in the Islamic world with advances in mathematics, medicine, and philosophy.',
    categoryId: 'cat-medieval-civs',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-10T00:00:00Z',
    updatedAt: '2026-06-10T00:00:00Z',
  },
  {
    id: 'entry-200-11',
    title_es: 'Imperio Otomano',
    title_en: 'Ottoman Empire',
    slug: 'imperio-otomano',
    content_es: `El Imperio Otomano fue un estado multiétnico y multicultural que existió desde 1299 hasta 1922, abarcando tres continentes. Fundado por Osman I, el imperio alcanzó su apogeo bajo Mehmed II, quien conquistó Constantinopla en 1453, y Solimán el Magnífico.\n\nLos otomanos gobernaron desde los Balcanes hasta el norte de África y el Medio Oriente, controlando rutas comerciales vitales. Su sistema administrativo, el ejército jenízaro y la arquitectura de Sinan dejaron un legado perdurable. El imperio colapsó tras la Primera Guerra Mundial, dando paso a la Turquía moderna.`,
    content_en: `The Ottoman Empire was a multiethnic and multicultural state that existed from 1299 to 1922, spanning three continents. Founded by Osman I, the empire reached its zenith under Mehmed II, who conquered Constantinople in 1453, and Suleiman the Magnificent.\n\nThe Ottomans ruled from the Balkans to North Africa and the Middle East, controlling vital trade routes. Their administrative system, the Janissary army, and the architecture of Sinan left a lasting legacy. The empire collapsed after World War I, giving way to modern Turkey.`,
    excerpt_es: 'Vasto imperio multiétnico que dominó tres continentes desde la conquista de Constantinopla hasta el siglo XX.',
    excerpt_en: 'Vast multiethnic empire that dominated three continents from the conquest of Constantinople until the 20th century.',
    categoryId: 'cat-medieval-civs',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-11T00:00:00Z',
    updatedAt: '2026-06-11T00:00:00Z',
  },
  {
    id: 'entry-200-12',
    title_es: 'Imperio Songhai',
    title_en: 'Songhai Empire',
    slug: 'imperio-songhai',
    content_es: `El Imperio Songhai fue el estado más grande de África Occidental, floreciendo entre los siglos XV y XVI. Bajo el liderazgo de Sunni Ali y Askia Muhammad, Songhai controló las rutas comerciales transaharianas del oro y la sal desde su capital en Gao.\n\nLa ciudad de Tombuctú se convirtió en un centro intelectual islámico con la Universidad de Sankore, atrayendo a eruditos de todo el mundo islámico. El imperio declinó tras la invasión marroquí en 1591, pero su legado como potencia comercial y cultural africana perdura.`,
    content_en: `The Songhai Empire was the largest state in West Africa, flourishing between the 15th and 16th centuries. Under the leadership of Sunni Ali and Askia Muhammad, Songhai controlled the trans-Saharan gold and salt trade routes from its capital at Gao.\n\nThe city of Timbuktu became an Islamic intellectual center with the University of Sankore, attracting scholars from across the Islamic world. The empire declined after the Moroccan invasion in 1591, but its legacy as an African commercial and cultural power endures.`,
    excerpt_es: 'El mayor imperio de África Occidental, centro del comercio transahariano y la erudición islámica en Tombuctú.',
    excerpt_en: 'The largest West African empire, center of trans-Saharan trade and Islamic scholarship in Timbuktu.',
    categoryId: 'cat-medieval-civs',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-12T00:00:00Z',
    updatedAt: '2026-06-12T00:00:00Z',
  },
  {
    id: 'entry-200-13',
    title_es: 'Imperio Jemer',
    title_en: 'Khmer Empire',
    slug: 'imperio-khemer',
    content_es: `El Imperio Jemer dominó el sudeste asiático entre los siglos IX y XV, con su capital en Angkor. Bajo el reinado de Suryavarman II, el imperio construyó Angkor Wat, el templo religioso más grande del mundo, dedicado originalmente al dios hindú Vishnú.\n\nEl imperio combinó influencias hindúes y budistas en un sincretismo único, reflejado en su arquitectura y arte. Jayavarman VII, el último gran rey, adoptó el budismo Mahayana y construyó Angkor Thom. El declive del imperio se atribuye a factores ambientales y la presión militar de los vecinos.`,
    content_en: `The Khmer Empire dominated Southeast Asia between the 9th and 15th centuries, with its capital at Angkor. Under King Suryavarman II, the empire built Angkor Wat, the largest religious temple in the world, originally dedicated to the Hindu god Vishnu.\n\nThe empire blended Hindu and Buddhist influences in a unique syncretism, reflected in its architecture and art. Jayavarman VII, the last great king, adopted Mahayana Buddhism and built Angkor Thom. The empire's decline is attributed to environmental factors and military pressure from neighbors.`,
    excerpt_es: 'Imperio del sudeste asiático que construyó Angkor Wat y desarrolló una síntesis única hindú-budista.',
    excerpt_en: 'Southeast Asian empire that built Angkor Wat and developed a unique Hindu-Buddhist synthesis.',
    categoryId: 'cat-medieval-civs',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-13T00:00:00Z',
    updatedAt: '2026-06-13T00:00:00Z',
  },
  {
    id: 'entry-200-14',
    title_es: 'Imperio Inca',
    title_en: 'Inca Empire',
    slug: 'imperio-inca',
    content_es: `El Imperio Inca, también conocido como Tawantinsuyu, fue el imperio más grande de la América precolombina. Desde su capital en Cusco, los incas dominaron los Andes desde Colombia hasta Chile mediante un sistema de caminos de más de 40,000 kilómetros.\n\nLos incas desarrollaron técnicas agrícolas en terrazas, un sistema de contabilidad mediante quipus y la impresionante ciudadela de Machu Picchu. El imperio cayó ante los conquistadores españoles liderados por Francisco Pizarro en 1533, pero su legado cultural perdura entre los pueblos andinos.`,
    content_en: `The Inca Empire, also known as Tawantinsuyu, was the largest empire in pre-Columbian America. From its capital in Cusco, the Incas dominated the Andes from Colombia to Chile through a road system spanning over 40,000 kilometers.\n\nThe Incas developed terrace agriculture, a accounting system using quipus, and the stunning citadel of Machu Picchu. The empire fell to Spanish conquistadors led by Francisco Pizarro in 1533, but its cultural legacy endures among the Andean peoples.`,
    excerpt_es: 'El mayor imperio precolombino de América, conocido por su red de caminos, Machu Picchu y los quipus.',
    excerpt_en: 'The largest pre-Columbian empire in the Americas, known for its road network, Machu Picchu, and quipus.',
    categoryId: 'cat-americas',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-14T00:00:00Z',
    updatedAt: '2026-06-14T00:00:00Z',
  },
  {
    id: 'entry-200-15',
    title_es: 'Cultura Misisipiana',
    title_en: 'Mississippian Culture',
    slug: 'cultura-misisipiana',
    content_es: `La cultura Misisipiana fue una civilización nativa americana que floreció en el valle del río Misisipi entre los años 800 y 1600 d.C. Su centro principal fue la ciudad de Cahokia, cerca de la actual San Luis, que llegó a albergar hasta 40,000 habitantes.\n\nLos misisipianos construyeron enormes montículos de tierra como plataformas ceremoniales y residenciales, siendo el Monje Mound el más grande. Su sociedad era jerárquica, con un jefe-sacerdote en la cima. La cultura declinó antes de la llegada de los europeos, probablemente debido a factores ambientales y conflictos internos.`,
    content_en: `The Mississippian culture was a Native American civilization that flourished in the Mississippi River valley between 800 and 1600 CE. Its main center was the city of Cahokia, near present-day St. Louis, which housed up to 40,000 inhabitants.\n\nThe Mississippians built enormous earthen mounds as ceremonial and residential platforms, with Monks Mound being the largest. Their society was hierarchical, with a priest-chief at the top. The culture declined before European contact, likely due to environmental factors and internal conflicts.`,
    excerpt_es: 'Civilización constructora de montículos que floreció en América del Norte con su centro en la gran ciudad de Cahokia.',
    excerpt_en: 'Mound-building civilization that flourished in North America with its great city of Cahokia.',
    categoryId: 'cat-americas',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-15T00:00:00Z',
    updatedAt: '2026-06-15T00:00:00Z',
  },
  {
    id: 'entry-200-16',
    title_es: 'Descubrimiento de América',
    title_en: 'Discovery of the Americas',
    slug: 'descubrimiento-de-america',
    content_es: `El 12 de octubre de 1492, Cristóbal Colón llegó a las Américas mientras buscaba una ruta hacia Asia. Este evento, patrocinado por los Reyes Católicos de España, transformó el curso de la historia mundial al conectar dos mundos que habían evolucionado de forma independiente.\n\nEl contacto europeo trajo el intercambio colombino de plantas, animales, enfermedades y culturas entre el Viejo y el Nuevo Mundo. Sin embargo, también provocó la devastación de las poblaciones indígenas por enfermedades y conflictos. El legado de 1492 sigue siendo objeto de debate entre celebración y crítica.`,
    content_en: `On October 12, 1492, Christopher Columbus arrived in the Americas while seeking a route to Asia. This event, sponsored by the Catholic Monarchs of Spain, transformed the course of world history by connecting two worlds that had evolved independently.\n\nEuropean contact brought the Columbian Exchange of plants, animals, diseases, and cultures between the Old and New Worlds. However, it also caused the devastation of indigenous populations through disease and conflict. The legacy of 1492 remains a subject of debate between celebration and criticism.`,
    excerpt_es: 'La llegada de Colón a América en 1492 inició el intercambio colombino y transformó para siempre la historia mundial.',
    excerpt_en: 'Columbus arrival in the Americas in 1492 initiated the Columbian Exchange and forever transformed world history.',
    categoryId: 'cat-events',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-16T00:00:00Z',
    updatedAt: '2026-06-16T00:00:00Z',
  },
  {
    id: 'entry-200-17',
    title_es: 'Caída del Muro de Berlín',
    title_en: 'Fall of the Berlin Wall',
    slug: 'caida-del-muro-de-berlin',
    content_es: `El 9 de noviembre de 1989, la caída del Muro de Berlín marcó el fin simbólico de la Guerra Fría. El muro, construido en 1961 por la República Democrática Alemana, dividía Berlín en Este y Oeste como símbolo de la separación entre el bloque comunista y el mundo occidental.\n\nTras semanas de protestas pacíficas en toda Europa del Este, el anuncio de nuevas regulaciones de viaje llevó a multitudes a los puntos de control, donde los guardias fronterizos finalmente abrieron las puertas. Este evento aceleró la reunificación alemana en 1990 y el colapso de la Unión Soviética en 1991.`,
    content_en: `On November 9, 1989, the fall of the Berlin Wall marked the symbolic end of the Cold War. The wall, built in 1961 by the German Democratic Republic, divided Berlin into East and West as a symbol of the separation between the communist bloc and the Western world.\n\nAfter weeks of peaceful protests across Eastern Europe, the announcement of new travel regulations led crowds to the checkpoints, where border guards eventually opened the gates. This event accelerated German reunification in 1990 and the collapse of the Soviet Union in 1991.`,
    excerpt_es: 'Evento histórico de 1989 que simbolizó el fin de la Guerra Fría y condujo a la reunificación alemana.',
    excerpt_en: 'Historic 1989 event that symbolized the end of the Cold War and led to German reunification.',
    categoryId: 'cat-events',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-17T00:00:00Z',
    updatedAt: '2026-06-17T00:00:00Z',
  },
  {
    id: 'entry-200-18',
    title_es: 'Primer Aterrizaje Lunar',
    title_en: 'First Moon Landing',
    slug: 'primer-aterrizaje-lunar',
    content_es: `El 20 de julio de 1969, la misión Apolo 11 de la NASA logró que el ser humano pisara la Luna por primera vez. Neil Armstrong pronunció su famosa frase "Un pequeño paso para el hombre, un gran salto para la humanidad" al descender del módulo lunar Eagle.\n\nEl alunizaje fue el punto culminante de la carrera espacial entre Estados Unidos y la Unión Soviética. Las imágenes en vivo fueron vistas por más de 600 millones de personas en todo el mundo. Este logro tecnológico demostró el poder de la colaboración científica y la determinación humana para superar límites.`,
    content_en: `On July 20, 1969, NASA's Apollo 11 mission achieved the first human moon landing. Neil Armstrong spoke his famous words "That's one small step for man, one giant leap for mankind" as he descended from the lunar module Eagle.\n\nThe moon landing was the culmination of the space race between the United States and the Soviet Union. Live images were watched by over 600 million people worldwide. This technological achievement demonstrated the power of scientific collaboration and human determination to overcome limits.`,
    excerpt_es: 'La histórica misión Apolo 11 en 1969 llevó al primer ser humano a pisar la superficie lunar.',
    excerpt_en: 'The historic Apollo 11 mission in 1969 took the first human to walk on the lunar surface.',
    categoryId: 'cat-events',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-18T00:00:00Z',
    updatedAt: '2026-06-18T00:00:00Z',
  },
  {
    id: 'entry-200-19',
    title_es: 'Revolución Francesa',
    title_en: 'French Revolution',
    slug: 'revolucion-francesa',
    content_es: `La Revolución Francesa comenzó en 1789 como un levantamiento popular contra la monarquía absoluta y el sistema feudal. La toma de la Bastilla el 14 de julio se convirtió en el símbolo del inicio de la revolución, que proclamó los ideales de Libertad, Igualdad y Fraternidad.\n\nLa revolución abolió la monarquía, estableció la Primera República y ejecutó al rey Luis XVI. Sin embargo, el período del Terror bajo Robespierre trajo violencia masiva. El caos político allanó el camino para el ascenso de Napoleón Bonaparte, quien consolidó muchas reformas revolucionarias mientras establecía un imperio.`,
    content_en: `The French Revolution began in 1789 as a popular uprising against absolute monarchy and the feudal system. The storming of the Bastille on July 14 became the symbol of the revolution's start, which proclaimed the ideals of Liberty, Equality, and Fraternity.\n\nThe revolution abolished the monarchy, established the First Republic, and executed King Louis XVI. However, the Reign of Terror under Robespierre brought mass violence. The political chaos paved the way for Napoleon Bonaparte's rise, who consolidated many revolutionary reforms while establishing an empire.`,
    excerpt_es: 'Revolución de 1789 que proclamó Libertad, Igualdad y Fraternidad, transformando Francia y la política mundial.',
    excerpt_en: '1789 revolution that proclaimed Liberty, Equality, and Fraternity, transforming France and world politics.',
    categoryId: 'cat-events',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-19T00:00:00Z',
    updatedAt: '2026-06-19T00:00:00Z',
  },
  {
    id: 'entry-200-20',
    title_es: 'Revolución Industrial',
    title_en: 'Industrial Revolution',
    slug: 'revolucion-industrial',
    content_es: `La Revolución Industrial comenzó en Gran Bretaña a finales del siglo XVIII y transformó radicalmente la producción, la tecnología y la sociedad. La máquina de vapor de James Watt, el telar mecánico y el alto horno impulsaron una nueva era de manufactura mecanizada.\n\nLa industrialización provocó una migración masiva del campo a las ciudades, creando nuevas clases sociales como el proletariado industrial. Las condiciones laborales eran duras y el trabajo infantil era común. Sin embargo, también trajo innovación tecnológica, crecimiento económico y cambios sociales que moldearon el mundo moderno.`,
    content_en: `The Industrial Revolution began in Britain in the late 18th century and radically transformed production, technology, and society. James Watt's steam engine, the mechanical loom, and the blast furnace drove a new era of mechanized manufacturing.\n\nIndustrialization caused mass migration from countryside to cities, creating new social classes such as the industrial proletariat. Working conditions were harsh and child labor was common. However, it also brought technological innovation, economic growth, and social changes that shaped the modern world.`,
    excerpt_es: 'Transformación tecnológica y social iniciada en el siglo XVIII que mecanizó la producción y creó el mundo industrial.',
    excerpt_en: 'Technological and social transformation begun in the 18th century that mechanized production and created the industrial world.',
    categoryId: 'cat-events',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-20T00:00:00Z',
    updatedAt: '2026-06-20T00:00:00Z',
  },
  {
    id: 'entry-200-21',
    title_es: 'Julio César',
    title_en: 'Julius Caesar',
    slug: 'julio-cesar',
    content_es: `Julio César fue un general y estadista romano cuyo liderazgo transformó la República Romana en el Imperio Romano. Sus campañas militares en la Galia expandieron enormemente el territorio romano y le proporcionaron un poder y prestigio sin precedentes.\n\nCésar fue nombrado dictador vitalicio en el 44 a.C., lo que generó temores entre los senadores de que aboliera la república. Un grupo de senadores liderados por Bruto y Casio lo asesinaron en los Idus de marzo. Su muerte desencadenó una guerra civil que culminó con el ascenso de Augusto y el establecimiento del Imperio Romano.`,
    content_en: `Julius Caesar was a Roman general and statesman whose leadership transformed the Roman Republic into the Roman Empire. His military campaigns in Gaul vastly expanded Roman territory and brought him unprecedented power and prestige.\n\nCaesar was appointed dictator for life in 44 BCE, generating fears among senators that he would abolish the republic. A group of senators led by Brutus and Cassius assassinated him on the Ides of March. His death triggered a civil war that culminated in Augustus's rise and the establishment of the Roman Empire.`,
    excerpt_es: 'General y dictador romano cuyo asesinato transformó la República en el Imperio Romano.',
    excerpt_en: 'Roman general and dictator whose assassination transformed the Republic into the Roman Empire.',
    categoryId: 'cat-figures-rulers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-21T00:00:00Z',
    updatedAt: '2026-06-21T00:00:00Z',
  },
  {
    id: 'entry-200-22',
    title_es: 'Isabel I de Inglaterra',
    title_en: 'Elizabeth I of England',
    slug: 'isabel-i-de-inglaterra',
    content_es: `Isabel I reinó sobre Inglaterra desde 1558 hasta 1603, período conocido como la Era Isabelina, una edad de oro para la cultura y el poder inglés. Hija de Enrique VIII y Ana Bolena, Isabel restauró el protestantismo y consolidó la Iglesia de Inglaterra.\n\nDurante su reinado, Inglaterra derrotó a la Armada Invencible española en 1588, estableciéndose como potencia naval. El florecimiento del teatro isabelino, con William Shakespeare como su máxima figura, transformó la literatura inglesa. Isabel nunca se casó, siendo conocida como la "Reina Virgen", y su reinado marcó el apogeo del Renacimiento inglés.`,
    content_en: `Elizabeth I reigned over England from 1558 to 1603, a period known as the Elizabethan Era, a golden age for English culture and power. Daughter of Henry VIII and Anne Boleyn, Elizabeth restored Protestantism and consolidated the Church of England.\n\nDuring her reign, England defeated the Spanish Armada in 1588, establishing itself as a naval power. The flourishing of Elizabethan theater, with William Shakespeare as its greatest figure, transformed English literature. Elizabeth never married, known as the "Virgin Queen," and her reign marked the height of the English Renaissance.`,
    excerpt_es: 'Reina Tudor cuyo reinado dorado vio la derrota de la Armada Invencible y el florecimiento de la cultura inglesa.',
    excerpt_en: 'Tudor queen whose golden reign saw the defeat of the Spanish Armada and the flourishing of English culture.',
    categoryId: 'cat-figures-rulers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-22T00:00:00Z',
    updatedAt: '2026-06-22T00:00:00Z',
  },
  {
    id: 'entry-200-23',
    title_es: 'Carlomagno',
    title_en: 'Charlemagne',
    slug: 'carlomagno',
    content_es: `Carlomagno, también conocido como Carlos el Grande, fue rey de los francos y emperador del Sacro Imperio Romano Germánico. Coronado por el Papa León III en el año 800 d.C., unificó gran parte de Europa occidental bajo su dominio.\n\nCarlomagno promovió el Renacimiento Carolingio, un resurgimiento del arte, la cultura y la educación basado en la tradición clásica. Estableció escuelas en todo su imperio y preservó textos latinos. Su imperio sentó las bases para el desarrollo de Europa medieval y moderna, y es considerado el "Padre de Europa".`,
    content_en: `Charlemagne, also known as Charles the Great, was king of the Franks and Emperor of the Holy Roman Empire. Crowned by Pope Leo III in the year 800 CE, he unified much of Western Europe under his rule.\n\nCharlemagne promoted the Carolingian Renaissance, a revival of art, culture, and education based on classical tradition. He established schools throughout his empire and preserved Latin texts. His empire laid the foundations for medieval and modern European development, and he is considered the "Father of Europe."`,
    excerpt_es: 'Emperador medieval que unificó Europa occidental e impulsó el Renacimiento Carolingio de la cultura clásica.',
    excerpt_en: 'Medieval emperor who unified Western Europe and promoted the Carolingian Renaissance of classical culture.',
    categoryId: 'cat-figures-rulers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-23T00:00:00Z',
    updatedAt: '2026-06-23T00:00:00Z',
  },
  {
    id: 'entry-200-24',
    title_es: 'Catalina la Grande',
    title_en: 'Catherine the Great',
    slug: 'catalina-la-grande',
    content_es: `Catalina II, conocida como Catalina la Grande, fue emperatriz de Rusia desde 1762 hasta 1796. Tomó el poder tras un golpe de estado que derrocó a su esposo, Pedro III, y gobernó durante el período de mayor expansión y modernización del Imperio Ruso.\n\nCatalina fue una déspota ilustrada que se correspondió con Voltaire y Diderot, expandió el territorio ruso hacia el Mar Negro y Polonia, y promovió la educación y las artes. Su reinado es considerado la Edad de Oro de la nobleza rusa, aunque también intensificó la servidumbre. Su legado como estadista transformó a Rusia en una potencia europea.`,
    content_en: `Catherine II, known as Catherine the Great, was Empress of Russia from 1762 to 1796. She took power after a coup that overthrew her husband, Peter III, and ruled during the greatest expansion and modernization of the Russian Empire.\n\nCatherine was an enlightened despot who corresponded with Voltaire and Diderot, expanded Russian territory toward the Black Sea and Poland, and promoted education and the arts. Her reign is considered the Golden Age of the Russian nobility, though it also intensified serfdom. Her legacy as a statesman transformed Russia into a European power.`,
    excerpt_es: 'Emperatriz rusa que modernizó el imperio, expandió sus fronteras y gobernó como déspota ilustrada.',
    excerpt_en: 'Russian empress who modernized the empire, expanded its borders, and ruled as an enlightened despot.',
    categoryId: 'cat-figures-rulers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-24T00:00:00Z',
    updatedAt: '2026-06-24T00:00:00Z',
  },
  {
    id: 'entry-200-25',
    title_es: 'Saladino',
    title_en: 'Saladin',
    slug: 'saladino',
    content_es: `Saladino, conocido como Salah ad-Din, fue un líder kurdo que se convirtió en sultán de Egipto y Siria y fundó la dinastía ayubí. Es famoso en Occidente y Oriente por su papel durante las Cruzadas, especialmente por la recaptura de Jerusalén en 1187.\n\nSaladino es recordado por su caballerosidad y trato humanitario hacia los prisioneros cristianos, en contraste con la brutalidad de los cruzados. Su liderazgo unificó el mundo musulmán contra los invasores europeos y su figura se ha convertido en un símbolo de honor, justicia y habilidad militar tanto en la tradición islámica como en la occidental.`,
    content_en: `Saladin, known as Salah ad-Din, was a Kurdish leader who became Sultan of Egypt and Syria and founded the Ayyubid dynasty. He is famous in both East and West for his role during the Crusades, especially for the recapture of Jerusalem in 1187.\n\nSaladin is remembered for his chivalry and humane treatment of Christian prisoners, in contrast to the brutality of the crusaders. His leadership unified the Muslim world against the European invaders and his figure has become a symbol of honor, justice, and military skill in both Islamic and Western traditions.`,
    excerpt_es: 'Líder kurdo que recapturó Jerusalén durante las Cruzadas, famoso por su caballerosidad y habilidad militar.',
    excerpt_en: 'Kurdish leader who recaptured Jerusalem during the Crusades, famous for his chivalry and military skill.',
    categoryId: 'cat-figures-rulers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-25T00:00:00Z',
    updatedAt: '2026-06-25T00:00:00Z',
  },
  {
    id: 'entry-200-26',
    title_es: 'Fernando de Magallanes',
    title_en: 'Ferdinand Magellan',
    slug: 'fernando-de-magallanes',
    content_es: `Fernando de Magallanes fue un navegante portugués que lideró la primera expedición que circunnavegó el globo terráqueo, aunque él murió antes de completarla. Su viaje, patrocinado por España, partió en 1519 y demostró que la Tierra era redonda.\n\nMagallanes descubrió el estrecho que lleva su nombre en el extremo sur de América, cruzando del Atlántico al Pacífico. Murió en las Filipinas en 1521 en un conflicto con los nativos. Juan Sebastián Elcano completó la circunnavegación, demostrando que era posible rodear el mundo por mar y abriendo nuevas rutas comerciales.`,
    content_en: `Ferdinand Magellan was a Portuguese navigator who led the first expedition to circumnavigate the globe, although he died before completing it. His voyage, sponsored by Spain, departed in 1519 and proved that the Earth was round.\n\nMagellan discovered the strait that bears his name at the southern tip of South America, crossing from the Atlantic to the Pacific. He died in the Philippines in 1521 in a conflict with natives. Juan Sebastián Elcano completed the circumnavigation, proving it was possible to sail around the world and opening new trade routes.`,
    excerpt_es: 'Navegante que lideró la primera circunnavegación del globo, demostrando que la Tierra es redonda.',
    excerpt_en: 'Navigator who led the first circumnavigation of the globe, proving the Earth is round.',
    categoryId: 'cat-figures-explorers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-26T00:00:00Z',
    updatedAt: '2026-06-26T00:00:00Z',
  },
  {
    id: 'entry-200-27',
    title_es: 'Ibn Battuta',
    title_en: 'Ibn Battuta',
    slug: 'ibn-battuta',
    content_es: `Ibn Battuta fue un explorador y erudito marroquí que viajó más de 120,000 kilómetros durante el siglo XIV, visitando casi todo el mundo islámico y más allá. Sus viajes duraron aproximadamente 30 años y abarcaron África, Europa, Asia y el Medio Oriente.\n\nSu obra, la Rihla, es uno de los libros de viajes más importantes de la historia, describiendo las culturas, costumbres y geografía de las tierras que visitó. Ibn Battuta llegó hasta China, la India y el África subsahariana, sirviendo como juez y diplomático. Su legado es invaluable para comprender el mundo medieval.`,
    content_en: `Ibn Battuta was a Moroccan explorer and scholar who traveled over 120,000 kilometers during the 14th century, visiting nearly the entire Islamic world and beyond. His travels lasted approximately 30 years and spanned Africa, Europe, Asia, and the Middle East.\n\nHis work, the Rihla, is one of the most important travel books in history, describing the cultures, customs, and geography of the lands he visited. Ibn Battuta reached as far as China, India, and sub-Saharan Africa, serving as a judge and diplomat. His legacy is invaluable for understanding the medieval world.`,
    excerpt_es: 'Viajero marroquí del siglo XIV que recorrió más de 120,000 km por todo el mundo islámico y más allá.',
    excerpt_en: '14th-century Moroccan traveler who journeyed over 120,000 km throughout the Islamic world and beyond.',
    categoryId: 'cat-figures-explorers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-27T00:00:00Z',
    updatedAt: '2026-06-27T00:00:00Z',
  },
  {
    id: 'entry-200-28',
    title_es: 'Zheng He',
    title_en: 'Zheng He',
    slug: 'zheng-he',
    content_es: `Zheng He fue un almirante y explorador chino que lideró siete expediciones navales masivas entre 1405 y 1433 durante la dinastía Ming. Su flota, conocida como la Flota del Tesoro, era la más grande del mundo y navegó por el Océano Índico.\n\nLas expediciones de Zheng He llegaron hasta el este de África, estableciendo relaciones diplomáticas y comerciales con numerosos reinos. Sus barcos, los juncos del tesoro, podían alcanzar tamaños mucho mayores que los buques europeos de la época. Tras su muerte, China abandonó la exploración marítima, pero su legado demostró el poderío naval chino.`,
    content_en: `Zheng He was a Chinese admiral and explorer who led seven massive naval expeditions between 1405 and 1433 during the Ming dynasty. His fleet, known as the Treasure Fleet, was the largest in the world and sailed across the Indian Ocean.\n\nZheng He's expeditions reached as far as East Africa, establishing diplomatic and commercial relations with numerous kingdoms. His ships, the treasure junks, could reach sizes much larger than contemporary European vessels. After his death, China abandoned maritime exploration, but his legacy demonstrated Chinese naval power.`,
    excerpt_es: 'Almirante chino que lideró enormes flotas del tesoro en expediciones por el Océano Índico hasta África.',
    excerpt_en: 'Chinese admiral who led enormous treasure fleet expeditions across the Indian Ocean to Africa.',
    categoryId: 'cat-figures-explorers',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-28T00:00:00Z',
    updatedAt: '2026-06-28T00:00:00Z',
  },
  {
    id: 'entry-200-29',
    title_es: 'Vincent van Gogh',
    title_en: 'Vincent van Gogh',
    slug: 'vincent-van-gogh',
    content_es: `Vincent van Gogh fue un pintor postimpresionista neerlandés que creó más de 2,000 obras de arte en solo una década. A pesar de su profunda influencia en el arte moderno, vendió solo unas pocas pinturas durante su vida y luchó contra problemas de salud mental.\n\nSus obras más famosas incluyen "La noche estrellada", "Los girasoles" y "El dormitorio". Su estilo único de pinceladas vibrantes y colores expresivos revolucionó la pintura. Tras años de sufrimiento, se suicidó a los 37 años. Van Gogh se convirtió póstumamente en uno de los artistas más reconocidos e influyentes de la historia.`,
    content_en: `Vincent van Gogh was a Dutch post-impressionist painter who created over 2,000 artworks in just one decade. Despite his profound influence on modern art, he sold only a few paintings during his lifetime and struggled with mental health issues.\n\nHis most famous works include "The Starry Night," "Sunflowers," and "The Bedroom." His unique style of vibrant brushstrokes and expressive colors revolutionized painting. After years of suffering, he died by suicide at age 37. Van Gogh posthumously became one of the most recognized and influential artists in history.`,
    excerpt_es: 'Pintor postimpresionista neerlandés cuya obra vibrante revolucionó el arte, reconocido plenamente tras su muerte.',
    excerpt_en: 'Dutch post-impressionist painter whose vibrant work revolutionized art, fully recognized after his death.',
    categoryId: 'cat-figures-artists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-29T00:00:00Z',
    updatedAt: '2026-06-29T00:00:00Z',
  },
  {
    id: 'entry-200-30',
    title_es: 'Frida Kahlo',
    title_en: 'Frida Kahlo',
    slug: 'frida-kahlo',
    content_es: `Frida Kahlo fue una pintora mexicana conocida por sus autorretratos que exploran la identidad, el dolor y la experiencia femenina. Su obra combina elementos del surrealismo, el arte popular mexicano y el realismo mágico en un estilo profundamente personal.\n\nKahlo sufrió polio infantil y un grave accidente que la dejó con dolor crónico. Su matrimonio con Diego Rivera influyó en su arte y política. Creó 143 pinturas, muchas autorretratos que reflejan su sufrimiento físico y emocional. Kahlo se ha convertido en un icono feminista y cultural, celebrada por su representación auténtica de la experiencia femenina.`,
    content_en: `Frida Kahlo was a Mexican painter known for her self-portraits that explore identity, pain, and the female experience. Her work combines elements of surrealism, Mexican folk art, and magical realism in a deeply personal style.\n\nKahlo suffered from childhood polio and a serious accident that left her with chronic pain. Her marriage to Diego Rivera influenced her art and politics. She created 143 paintings, many self-portraits reflecting her physical and emotional suffering. Kahlo has become a feminist and cultural icon, celebrated for her authentic portrayal of the female experience.`,
    excerpt_es: 'Pintora mexicana famosa por sus autorretratos que exploran el dolor, la identidad y la experiencia femenina.',
    excerpt_en: 'Mexican painter famous for her self-portraits exploring pain, identity, and the female experience.',
    categoryId: 'cat-figures-artists',
    realityStatus: 'historical',
    imageUrl: '',
    createdAt: '2026-06-30T00:00:00Z',
    updatedAt: '2026-06-30T00:00:00Z',
  },
  {
    id: 'entry-200-31',
    title_es: 'Hércules',
    title_en: 'Hercules',
    slug: 'hercules',
    content_es: `Hércules, conocido en griego como Heracles, es el héroe más famoso de la mitología griega. Hijo de Zeus y la mortal Alcmena, poseía una fuerza sobrehumana que lo llevó a realizar doce trabajos imposibles como castigo por haber matado a su familia en un arrebato de locura enviado por Hera.\n\nEntre sus trabajos se incluyen matar al León de Nemea, la Hidra de Lerna y capturar al jabalí de Erimanto. Hércules también participó en el viaje de los argonautas y fue reconocido por su valor y resistencia. Tras su muerte, ascendió al Olimpo y se convirtió en un dios, simbolizando la redención mediante el esfuerzo heroico.`,
    content_en: `Hercules, known in Greek as Heracles, is the most famous hero in Greek mythology. Son of Zeus and the mortal Alcmene, he possessed superhuman strength that led him to perform twelve impossible labors as punishment for killing his family in a fit of madness sent by Hera.\n\nHis labors include killing the Nemean Lion, the Lernaean Hydra, and capturing the Erymanthian Boar. Hercules also participated in the voyage of the Argonauts and was recognized for his courage and endurance. After his death, he ascended to Olympus and became a god, symbolizing redemption through heroic effort.`,
    excerpt_es: 'El héroe más famoso de la mitología griega, conocido por su fuerza sobrehumana y los doce trabajos.',
    excerpt_en: 'The most famous hero in Greek mythology, known for his superhuman strength and the twelve labors.',
    categoryId: 'cat-figures-legendary',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-01T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
  },
  {
    id: 'entry-200-32',
    title_es: 'Mulan',
    title_en: 'Mulan',
    slug: 'mulan',
    content_es: `Mulan, conocida como Hua Mulan en la tradición china, es una guerrera legendaria que se hizo pasar por hombre para ocupar el lugar de su padre anciano en el ejército. Su historia se originó en la Balada de Mulan, un poema chino del siglo VI.\n\nMulan luchó durante doce años en el ejército sin que descubrieran su verdadera identidad. Demostró gran habilidad y valentía, rechazando cargos oficiales al final de la guerra para regresar a su familia. La leyenda de Mulan celebra la lealtad filial, el honor familiar y la capacidad de las mujeres para desafiar las expectativas de género.`,
    content_en: `Mulan, known as Hua Mulan in Chinese tradition, is a legendary warrior who disguised herself as a man to take her elderly father's place in the army. Her story originated in the Ballad of Mulan, a Chinese poem from the 6th century.\n\nMulan fought for twelve years in the army without her true identity being discovered. She demonstrated great skill and courage, refusing official positions at war's end to return to her family. The legend of Mulan celebrates filial piety, family honor, and women's ability to challenge gender expectations.`,
    excerpt_es: 'Guerrera legendaria china que se disfrazó de hombre para ocupar el lugar de su padre en el ejército.',
    excerpt_en: 'Legendary Chinese warrior who disguised herself as a man to take her father place in the army.',
    categoryId: 'cat-figures-legendary',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-02T00:00:00Z',
    updatedAt: '2026-07-02T00:00:00Z',
  },
  {
    id: 'entry-200-33',
    title_es: 'El Cid',
    title_en: 'El Cid',
    slug: 'el-cid',
    content_es: `Rodrigo Díaz de Vivar, conocido como El Cid Campeador, fue un caballero castellano que se convirtió en héroe legendario de la Reconquista española. Su vida real y las hazañas ficticias narradas en el Cantar de Mio Cid lo convirtieron en el héroe épico por excelencia de España.\n\nEl Cid luchó tanto para reyes cristianos como musulmanes, demostrando su habilidad militar y ambición. Conquistó Valencia y la gobernó hasta su muerte. El poema épico lo retrata como un vasallo leal que recupera su honor mediante la conquista militar. El Cid representa el ideal del caballero medieval: leal, valiente y hábil en la guerra.`,
    content_en: `Rodrigo Díaz de Vivar, known as El Cid Campeador, was a Castilian knight who became a legendary hero of the Spanish Reconquista. His real life and the fictional deeds narrated in the Cantar de Mio Cid made him the quintessential epic hero of Spain.\n\nEl Cid fought for both Christian and Muslim kings, demonstrating his military skill and ambition. He conquered Valencia and ruled it until his death. The epic poem portrays him as a loyal vassal who recovers his honor through military conquest. El Cid represents the ideal medieval knight: loyal, brave, and skilled in war.`,
    excerpt_es: 'Caballero castellano legendario de la Reconquista, héroe del Cantar de Mio Cid y símbolo del honor medieval.',
    excerpt_en: 'Legendary Castilian knight of the Reconquista, hero of the Cantar de Mio Cid and symbol of medieval honor.',
    categoryId: 'cat-figures-legendary',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-03T00:00:00Z',
    updatedAt: '2026-07-03T00:00:00Z',
  },
  {
    id: 'entry-200-34',
    title_es: 'Pandora',
    title_en: 'Pandora',
    slug: 'pandora',
    content_es: `Pandora fue la primera mujer creada por los dioses en la mitología griega, según el relato de Hesíodo. Hefesto la modeló en arcilla por orden de Zeus, y los dioses le otorgaron dones: belleza, inteligencia y persuasión. Su nombre significa "la que todo lo da".\n\nZeus le entregó una jarra que contenía todos los males del mundo y le prohibió abrirla. Pandora, vencida por la curiosidad, abrió la jarra y liberó enfermedades, dolores y desgracias sobre la humanidad. Solo la Esperanza quedó dentro. El mito de Pandora explica el origen del sufrimiento humano y el valor perdurable de la esperanza.`,
    content_en: `Pandora was the first woman created by the gods in Greek mythology, according to Hesiod's account. Hephaestus molded her from clay by Zeus's order, and the gods bestowed gifts upon her: beauty, intelligence, and persuasion. Her name means "all-gifted."\n\nZeus gave her a jar containing all the evils of the world and forbade her to open it. Pandora, overcome by curiosity, opened the jar and released diseases, pains, and misfortunes upon humanity. Only Hope remained inside. The myth of Pandora explains the origin of human suffering and the enduring value of hope.`,
    excerpt_es: 'Primera mujer de la mitología griega que abrió la jarra que liberó todos los males del mundo, dejando solo la esperanza.',
    excerpt_en: 'First woman in Greek mythology who opened the jar releasing all the world evils, leaving only hope inside.',
    categoryId: 'cat-greek-myth',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-04T00:00:00Z',
    updatedAt: '2026-07-04T00:00:00Z',
  },
  {
    id: 'entry-200-35',
    title_es: 'Medusa',
    title_en: 'Medusa',
    slug: 'medusa',
    content_es: `Medusa era una de las tres Gorgonas, criaturas femeninas de la mitología griega con serpientes vivas en lugar de cabello. A diferencia de sus hermanas Esteno y Euríale, Medusa era mortal. Su mirada tenía el poder de petrificar a cualquiera que la mirara directamente.\n\nOriginalmente fue una hermosa doncella, pero fue transformada en monstruo por Atenea como castigo por haber sido violada por Poseidón en el templo de la diosa. El héroe Perseo la decapitó con la ayuda de los dioses. De su sangre nacieron el caballo alado Pegaso y el gigante Crisaor. La cabeza de Medusa fue utilizada como arma por Perseo y luego colocada en el escudo de Atenea.`,
    content_en: `Medusa was one of the three Gorgons, female creatures in Greek mythology with live snakes instead of hair. Unlike her sisters Stheno and Euryale, Medusa was mortal. Her gaze had the power to petrify anyone who looked directly at her.\n\nOriginally a beautiful maiden, she was transformed into a monster by Athena as punishment for being raped by Poseidon in the goddess's temple. The hero Perseus beheaded her with the help of the gods. From her blood sprang the winged horse Pegasus and the giant Chrysaor. Medusa's head was used as a weapon by Perseus and later placed on Athena's shield.`,
    excerpt_es: 'Gorgona de la mitología griega con cabello de serpientes y mirada petrificante, decapitada por Perseo.',
    excerpt_en: 'Gorgon from Greek mythology with snake hair and petrifying gaze, beheaded by Perseus.',
    categoryId: 'cat-greek-myth',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-05T00:00:00Z',
    updatedAt: '2026-07-05T00:00:00Z',
  },
  {
    id: 'entry-200-36',
    title_es: 'Deméter y Perséfone',
    title_en: 'Demeter and Persephone',
    slug: 'demeter-y-persefone',
    content_es: `El mito de Deméter y Perséfone es una de las historias más conmovedoras de la mitología griega. Deméter, diosa de la agricultura y la cosecha, tenía una hija llamada Perséfone. Hades, dios del inframundo, se enamoró de Perséfone y la secuestró mientras recogía flores.\n\nDeméter, desconsolada, buscó a su hija por todo el mundo y, en su dolor, descuidó la tierra, causando un invierno eterno. Zeus intervino y acordó que Perséfone pasara parte del año con Hades y parte con su madre. Así nacieron las estaciones: cuando Perséfone está en el inframundo, Deméter llora y es invierno; cuando regresa, la tierra florece en primavera y verano.`,
    content_en: `The myth of Demeter and Persephone is one of the most poignant stories in Greek mythology. Demeter, goddess of agriculture and harvest, had a daughter named Persephone. Hades, god of the underworld, fell in love with Persephone and kidnapped her while she was gathering flowers.\n\nDemeter, heartbroken, searched for her daughter across the world and, in her grief, neglected the earth, causing an eternal winter. Zeus intervened and arranged for Persephone to spend part of the year with Hades and part with her mother. Thus the seasons were born: when Persephone is in the underworld, Demeter mourns and it is winter; when she returns, the earth blossoms in spring and summer.`,
    excerpt_es: 'Mito griego que explica las estaciones a través del vínculo entre Deméter y su hija Perséfone, raptada por Hades.',
    excerpt_en: 'Greek myth explaining the seasons through the bond between Demeter and her daughter Persephone, abducted by Hades.',
    categoryId: 'cat-greek-myth',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-06T00:00:00Z',
    updatedAt: '2026-07-06T00:00:00Z',
  },
  {
    id: 'entry-200-37',
    title_es: 'Thot',
    title_en: 'Thoth',
    slug: 'thot',
    content_es: `Thot es el dios egipcio de la escritura, la sabiduría, la magia y la luna. Representado con cabeza de ibis o como un babuino, era considerado el escriba de los dioses y el inventor de la escritura jeroglífica. También era el dios que registraba los resultados del juicio de los muertos.\n\nThot era mediador y consejero de los dioses, especialmente de Ra. Se le atribuye la creación de la literatura sagrada, la ciencia, la astronomía y la medicina. Los griegos lo identificaron con Hermes y le atribuyeron los textos herméticos. Thot representa el poder del conocimiento y la palabra escrita en la civilización egipcia.`,
    content_en: `Thoth is the Egyptian god of writing, wisdom, magic, and the moon. Depicted with the head of an ibis or as a baboon, he was considered the scribe of the gods and the inventor of hieroglyphic writing. He also recorded the results of the judgment of the dead.\n\nThoth served as mediator and advisor to the gods, especially Ra. He is credited with creating sacred literature, science, astronomy, and medicine. The Greeks identified him with Hermes and attributed the Hermetic texts to him. Thoth represents the power of knowledge and the written word in Egyptian civilization.`,
    excerpt_es: 'Dios egipcio de la escritura y la sabiduría, representado con cabeza de ibis, escriba de los dioses.',
    excerpt_en: 'Egyptian god of writing and wisdom, depicted with an ibis head, scribe of the gods.',
    categoryId: 'cat-egyptian-myth',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-07T00:00:00Z',
    updatedAt: '2026-07-07T00:00:00Z',
  },
  {
    id: 'entry-200-38',
    title_es: 'Bastet',
    title_en: 'Bastet',
    slug: 'bastet',
    content_es: `Bastet es la diosa egipcia de la protección, el hogar, la música, la danza y el placer. Representada como una mujer con cabeza de gato o como un gato doméstico, era una de las deidades más queridas del antiguo Egipto. Su centro de culto principal estaba en la ciudad de Bubastis.\n\nBastet protegía el hogar y la familia, y se asociaba con la fertilidad y el parto. Los gatos eran sagrados en Egipto por su asociación con Bastet, y matar uno era castigado con la muerte. La diosa también tenía un aspecto guerrero como la leona Sekhmet. Bastet simboliza la dualidad entre la dulzura doméstica y la ferocidad protectora.`,
    content_en: `Bastet is the Egyptian goddess of protection, home, music, dance, and pleasure. Depicted as a woman with a cat head or as a domestic cat, she was one of the most beloved deities of ancient Egypt. Her main cult center was in the city of Bubastis.\n\nBastet protected the home and family, and was associated with fertility and childbirth. Cats were sacred in Egypt for their association with Bastet, and killing one was punishable by death. The goddess also had a warrior aspect as the lioness Sekhmet. Bastet symbolizes the duality between domestic sweetness and protective ferocity.`,
    excerpt_es: 'Diosa egipcia del hogar y la protección representada como gato, una de las deidades más queridas del antiguo Egipto.',
    excerpt_en: 'Egyptian goddess of home and protection depicted as a cat, one of the most beloved deities of ancient Egypt.',
    categoryId: 'cat-egyptian-myth',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-08T00:00:00Z',
    updatedAt: '2026-07-08T00:00:00Z',
  },
  {
    id: 'entry-200-39',
    title_es: 'Heimdall',
    title_en: 'Heimdall',
    slug: 'heimdall',
    content_es: `Heimdall es el vigilante de los dioses en la mitología nórdica, conocido como el "dios brillante" o "el de los dientes de oro". Monta guardia en el puente Bifrost, el arco iris que conecta Asgard con Midgard, protegiendo la entrada al reino de los dioses.\n\nHeimdall posee sentidos extraordinarios: puede oír crecer la hierba y ver a cien leguas de distancia. Posee el cuerno Gjallarhorn, cuyo sonido se escuchará en todos los mundos para anunciar el comienzo del Ragnarok. En el Ragnarok, Heimdall y Loki se enfrentarán y se matarán mutuamente. Heimdall representa la vigilancia eterna y el deber sagrado de proteger el orden divino.`,
    content_en: `Heimdall is the watchman of the gods in Norse mythology, known as the "shining god" or "golden-toothed." He stands guard at the Bifrost bridge, the rainbow connecting Asgard to Midgard, protecting the entrance to the realm of the gods.\n\nHeimdall possesses extraordinary senses: he can hear grass growing and see for hundreds of miles. He owns the horn Gjallarhorn, whose sound will be heard across all worlds to announce the beginning of Ragnarok. At Ragnarok, Heimdall and Loki will fight and kill each other. Heimdall represents eternal vigilance and the sacred duty of protecting the divine order.`,
    excerpt_es: 'Vigilante de los dioses nórdicos que protege el puente Bifrost y anuncia el Ragnarok con su cuerno Gjallarhorn.',
    excerpt_en: 'Watchman of the Norse gods who guards the Bifrost bridge and announces Ragnarok with his horn Gjallarhorn.',
    categoryId: 'cat-norse-myth',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-09T00:00:00Z',
    updatedAt: '2026-07-09T00:00:00Z',
  },
  {
    id: 'entry-200-40',
    title_es: 'Fenrir',
    title_en: 'Fenrir',
    slug: 'fenrir',
    content_es: `Fenrir es un lobo gigante de la mitología nórdica, hijo de Loki y la giganta Angrboda. Los dioses, temiendo su crecimiento y profetizado poder, intentaron encadenarlo. Fenrir rompió todas las ataduras hasta que los enanos forjaron la cinta mágica Gleipnir, hecha de elementos imposibles como el sonido de pisadas de gato y la barba de una mujer.\n\nFenrir aceptó ser atado solo si un dios ponía su mano en su boca como garantía. El dios Tyr fue el único valiente suficiente y perdió su mano. En el Ragnarok, Fenrir se liberará y devorará a Odín. El hijo de Odín, Vidar, lo vengará desgarrándole las fauces. Fenrir simboliza las fuerzas indomables que amenazan el orden cósmico.`,
    content_en: `Fenrir is a giant wolf in Norse mythology, son of Loki and the giantess Angrboda. The gods, fearing his growth and prophesied power, attempted to chain him. Fenrir broke all bonds until the dwarves forged the magical ribbon Gleipnir, made from impossible elements like the sound of cat footsteps and a woman's beard.\n\nFenrir agreed to be bound only if a god placed their hand in his mouth as a pledge. The god Tyr was the only one brave enough and lost his hand. At Ragnarok, Fenrir will break free and devour Odin. Odin's son Vidar will avenge him by tearing Fenrir's jaws apart. Fenrir symbolizes the untamable forces that threaten cosmic order.`,
    excerpt_es: 'Lobo gigante de la mitología nórdica, hijo de Loki, que devorará a Odín durante el Ragnarok.',
    excerpt_en: 'Giant wolf in Norse mythology, son of Loki, who will devour Odin during Ragnarok.',
    categoryId: 'cat-norse-myth',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-10T00:00:00Z',
    updatedAt: '2026-07-10T00:00:00Z',
  },
  {
    id: 'entry-200-41',
    title_es: 'Ganesha',
    title_en: 'Ganesha',
    slug: 'ganesha',
    content_es: `Ganesha es uno de los dioses más venerados del hinduismo, reconocido por su cabeza de elefante y cuerpo humano. Es el dios de la sabiduría, la inteligencia y el removedor de obstáculos. Se le invoca al comienzo de cualquier empresa importante para asegurar su éxito.\n\nSegún la mitología, Ganesha fue creado por Parvati, quien lo formó de arcilla y le dio vida. Cuando Shiva intentó acercarse a Parvati, Ganesha le impidió el paso y Shiva le cortó la cabeza. Para aplacar a Parvati, Shiva reemplazó la cabeza perdida con la de un elefante. Ganesha monta una rata y sostiene un hacha y una cuerda, simbolizando la capacidad de cortar ataduras y guiar hacia la verdad.`,
    content_en: `Ganesha is one of the most venerated gods in Hinduism, recognized by his elephant head and human body. He is the god of wisdom, intelligence, and the remover of obstacles. He is invoked at the beginning of any important undertaking to ensure success.\n\nAccording to mythology, Ganesha was created by Parvati, who molded him from clay and brought him to life. When Shiva tried to approach Parvati, Ganesha blocked his way and Shiva cut off his head. To appease Parvati, Shiva replaced the lost head with that of an elephant. Ganesha rides a rat and holds an axe and a rope, symbolizing the ability to cut bonds and guide toward truth.`,
    excerpt_es: 'Dios hindú con cabeza de elefante, removedor de obstáculos y deidad de la sabiduría y la inteligencia.',
    excerpt_en: 'Hindu god with an elephant head, remover of obstacles and deity of wisdom and intelligence.',
    categoryId: 'cat-hindu-myth',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-11T00:00:00Z',
    updatedAt: '2026-07-11T00:00:00Z',
  },
  {
    id: 'entry-200-42',
    title_es: 'Kali',
    title_en: 'Kali',
    slug: 'kali',
    content_es: `Kali es la diosa hindú del tiempo, el cambio y la destrucción, adorada como la Madre Divina en su aspecto feroz. Se la representa con piel oscura o azul, cuatro brazos, un collar de calaveras y una guirnalda de cabezas cortadas, portando un tridente y una espada.\n\nKali emerge de la frente de Durga durante una batalla contra el demonio Raktabija, cuya sangre generaba más demonios al tocar el suelo. Kali bebió la sangre y bailó la danza de la destrucción, amenazando con destruir el mundo hasta que Shiva se acostó en su camino. Kali representa la fuerza destructora del tiempo que permite la renovación cíclica y la liberación espiritual.`,
    content_en: `Kali is the Hindu goddess of time, change, and destruction, worshipped as the Divine Mother in her fierce aspect. She is depicted with dark or blue skin, four arms, a necklace of skulls and a garland of severed heads, carrying a trident and a sword.\n\nKali emerged from Durga's forehead during a battle against the demon Raktabija, whose blood generated more demons upon touching the ground. Kali drank the blood and danced the dance of destruction, threatening to destroy the world until Shiva lay in her path. Kali represents the destructive force of time that enables cyclic renewal and spiritual liberation.`,
    excerpt_es: 'Diosa hindú del tiempo y la destrucción, Madre Divina en su aspecto feroz que permite la renovación cósmica.',
    excerpt_en: 'Hindu goddess of time and destruction, Divine Mother in her fierce aspect enabling cosmic renewal.',
    categoryId: 'cat-hindu-myth',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-12T00:00:00Z',
    updatedAt: '2026-07-12T00:00:00Z',
  },
  {
    id: 'entry-200-43',
    title_es: 'Quetzalcóatl',
    title_en: 'Quetzalcoatl',
    slug: 'quetzalcoatl',
    content_es: `Quetzalcóatl, la Serpiente Emplumada, es una de las deidades más importantes de las culturas mesoamericanas, especialmente para los toltecas y aztecas. Representa la unión entre el cielo y la tierra, simbolizada por la serpiente (lo terrenal) y las plumas (lo celestial).\n\nQuetzalcóatl era el dios del viento, el conocimiento y la creación. Se le atribuye la enseñanza de la agricultura, la escritura, el calendario y las artes a la humanidad. En la tradición azteca, su supuesto regreso fue confundido con la llegada de Hernán Cortés, un malentendido que facilitó la conquista española. Quetzalcóatl simboliza la sabiduría y la conexión entre los planos divino y humano.`,
    content_en: `Quetzalcoatl, the Feathered Serpent, is one of the most important deities of Mesoamerican cultures, especially for the Toltecs and Aztecs. He represents the union between heaven and earth, symbolized by the serpent (the earthly) and the feathers (the celestial).\n\nQuetzalcoatl was the god of wind, knowledge, and creation. He is credited with teaching agriculture, writing, the calendar, and the arts to humanity. In Aztec tradition, his supposed return was confused with the arrival of Hernán Cortés, a misunderstanding that facilitated the Spanish conquest. Quetzalcoatl symbolizes wisdom and the connection between the divine and human realms.`,
    excerpt_es: 'Serpiente Emplumada, deidad mesoamericana del viento y el conocimiento, clave en las culturas tolteca y azteca.',
    excerpt_en: 'Feathered Serpent, Mesoamerican deity of wind and knowledge, key in Toltec and Aztec cultures.',
    categoryId: 'cat-other-myth',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-13T00:00:00Z',
    updatedAt: '2026-07-13T00:00:00Z',
  },
  {
    id: 'entry-200-44',
    title_es: 'Popol Vuh',
    title_en: 'Popol Vuh',
    slug: 'popol-vuh',
    content_es: `El Popol Vuh es el libro sagrado del pueblo maya k'iche', una de las obras literarias más importantes de la América precolombina. Escrito en el siglo XVI después de la conquista española, preserva la cosmogonía, mitología e historia de los mayas de Guatemala.\n\nEl texto narra la creación del mundo por los dioses Tepeu y Gukumatz, la creación de los primeros humanos de maíz y las aventuras de los Héroes Gemelos Hunahpú e Ixbalanqué en el inframundo. El Popol Vuh es fundamental para comprender la visión del mundo maya, incluyendo su concepto del tiempo cíclico y la relación entre los dioses y los humanos.`,
    content_en: `The Popol Vuh is the sacred book of the K'iche' Maya people, one of the most important literary works of pre-Columbian America. Written in the 16th century after the Spanish conquest, it preserves the cosmogony, mythology, and history of the Maya of Guatemala.\n\nThe text narrates the creation of the world by the gods Tepeu and Gukumatz, the creation of the first humans from maize, and the adventures of the Hero Twins Hunahpú and Ixbalanqué in the underworld. The Popol Vuh is essential for understanding the Maya worldview, including their concept of cyclical time and the relationship between gods and humans.`,
    excerpt_es: 'Libro sagrado maya que narra la creación del mundo, los primeros humanos de maíz y los Héroes Gemelos.',
    excerpt_en: 'Sacred Maya book narrating the creation of the world, the first humans from maize, and the Hero Twins.',
    categoryId: 'cat-sacred-texts',
    realityStatus: 'mythological',
    imageUrl: '',
    createdAt: '2026-07-14T00:00:00Z',
    updatedAt: '2026-07-14T00:00:00Z',
  },
  {
    id: 'entry-200-45',
    title_es: 'Upanishads',
    title_en: 'Upanishads',
    slug: 'upanishads',
    content_es: `Los Upanishads son un conjunto de textos filosóficos hindúes que constituyen la base del Vedanta, la escuela de filosofía que interpreta los Vedas. Compuestos entre los siglos VIII y III a.C., estos textos exploran la naturaleza última de la realidad, el ser y la liberación espiritual.\n\nLos Upanishads introducen conceptos fundamentales como Brahman (la realidad suprema e inmutable) y Atman (el alma individual), enseñando que en última instancia son idénticos. Textos como el Chandogya Upanishad y el Brihadaranyaka Upanishad contienen diálogos filosóficos profundos sobre el conocimiento, el sacrificio y el camino hacia la liberación. Los Upanishads han influido profundamente en la filosofía y espiritualidad de la India y el mundo.`,
    content_en: `The Upanishads are a collection of Hindu philosophical texts that form the foundation of Vedanta, the school of philosophy that interprets the Vedas. Composed between the 8th and 3rd centuries BCE, these texts explore the ultimate nature of reality, the self, and spiritual liberation.\n\nThe Upanishads introduce fundamental concepts such as Brahman (the supreme, immutable reality) and Atman (the individual soul), teaching that they are ultimately identical. Texts like the Chandogya Upanishad and the Brihadaranyaka Upanishad contain profound philosophical dialogues on knowledge, sacrifice, and the path to liberation. The Upanishads have profoundly influenced philosophy and spirituality in India and the world.`,
    excerpt_es: 'Textos filosóficos hindúes que exploran Brahman, Atman y la naturaleza última de la realidad en la tradición del Vedanta.',
    excerpt_en: 'Hindu philosophical texts exploring Brahman, Atman, and the ultimate nature of reality in the Vedanta tradition.',
    categoryId: 'cat-sacred-texts',
    realityStatus: 'philosophical',
    imageUrl: '',
    createdAt: '2026-07-15T00:00:00Z',
    updatedAt: '2026-07-15T00:00:00Z',
  },
]
