import { SeedSubsection } from '../seed'

export const subsectionsPart1: SeedSubsection[] = [
  // === DOMAIN 9: CONSPIRACY - Political ===
  { id: 'sub-nwo-1', entryId: 'entry-nwo', title_es: 'Élites globales', title_en: 'Global elites',
    content_es: 'El núcleo de la teoría del NWO son las familias que supuestamente controlan el poder mundial: Rockefeller, Rothschild, Morgan, Du Pont, Bush y otras dinastías. Se afirma que estas familias se reúnen en secreto para decidir el rumbo de la humanidad, controlando bancos centrales, medios de comunicación y gobiernos mediante una red de influencias y lealtades.',
    content_en: 'The core of the NWO theory are the families allegedly controlling world power: Rockefeller, Rothschild, Morgan, Du Pont, Bush, and other dynasties. These families are said to meet in secret to decide humanity\'s direction, controlling central banks, media, and governments through a network of influences and loyalties.',
    order: 0 },
  { id: 'sub-nwo-2', entryId: 'entry-nwo', title_es: 'Eventos planificados', title_en: 'Planned events',
    content_es: 'Los teóricos del NWO interpretan guerras, crisis económicas y pandemias como eventos planificados ("problemas creados, soluciones ofrecidas"). La crisis de 2008, la Primavera Árabe, la guerra en Ucrania y la pandemia de COVID-19 son vistos como crisis orquestadas para avanzar hacia el control global. Cada crisis se aprovecha para implementar medidas que serían rechazadas en tiempos normales.',
    content_en: 'NWO theorists interpret wars, economic crises, and pandemics as planned events ("problems created, solutions offered"). The 2008 crisis, Arab Spring, Ukraine war, and COVID-19 pandemic are seen as orchestrated crises to advance toward global control. Each crisis is exploited to implement measures that would be rejected in normal times.',
    order: 1 },
  { id: 'sub-deep-1', entryId: 'entry-deepstate', title_es: 'Origen del concepto', title_en: 'Origin of the concept',
    content_es: 'El término "Estado profundo" proviene del turco "derin devlet", usado para describir la red de militares y servicios de inteligencia en Turquía que ha influido en la política desde la fundación de la república. En EE.UU., el concepto fue popularizado por la administración Trump para describir la resistencia burocrática interna.',
    content_en: 'The term "deep state" comes from Turkish "derin devlet," used to describe the network of military and intelligence services in Turkey that has influenced politics since the republic\'s founding. In the US, the concept was popularized by the Trump administration to describe internal bureaucratic resistance.',
    order: 0 },
  { id: 'sub-deep-2', entryId: 'entry-deepstate', title_es: 'Crítica académica', title_en: 'Academic critique',
    content_es: 'Científicos políticos señalan que el "Estado profundo" confunde la inercia burocrática normal con una conspiración deliberada. Las agencias gubernamentales tienen culturas organizacionales, intereses e inercias que persisten entre administraciones, pero esto no equivale a una red conspirativa. La transparencia y los mecanismos de control existen, aunque imperfectos.',
    content_en: 'Political scientists note that the "deep state" confuses normal bureaucratic inertia with deliberate conspiracy. Government agencies have organizational cultures, interests, and inertias that persist between administrations, but this does not equal a conspiratorial network. Transparency and oversight mechanisms exist, though imperfect.',
    order: 1 },
  { id: 'sub-bild-1', entryId: 'entry-bilderberg', title_es: 'Historia y secretismo', title_en: 'History and secrecy',
    content_es: 'La primera reunión de Bilderberg fue en 1954 en el Hotel de Bilderberg, Países Bajos, organizada por el polaco exiliado Józef Retinger y el príncipe Bernhard de los Países Bajos. El objetivo era fomentar la cooperación transatlántica tras la Segunda Guerra Mundial. La falta de actas públicas y la regla de confidencialidad alimentó las sospechas.',
    content_en: 'The first Bilderberg meeting was in 1954 at the Hotel de Bilderberg, Netherlands, organized by Polish exile Józef Retinger and Prince Bernhard of the Netherlands. The goal was fostering transatlantic cooperation after WWII. The lack of public minutes and confidentiality rule fueled suspicions.',
    order: 0 },
  { id: 'sub-bild-2', entryId: 'entry-bilderberg', title_es: 'Asistentes notables', title_en: 'Notable attendees',
    content_es: 'Entre los asistentes históricos a Bilderberg se encuentran Henry Kissinger, David Rockefeller, Bill Clinton, Tony Blair, Margaret Thatcher, Angela Merkel, Javier Solana y Christine Lagarde. Los críticos señalan que estas figuras representan el establishment global y que sus reuniones privadas son incompatibles con la transparencia democrática.',
    content_en: 'Historical Bilderberg attendees include Henry Kissinger, David Rockefeller, Bill Clinton, Tony Blair, Margaret Thatcher, Angela Merkel, Javier Solana, and Christine Lagarde. Critics note these figures represent the global establishment and that their private meetings are incompatible with democratic transparency.',
    order: 1 },
  { id: 'sub-blue-1', entryId: 'entry-bluebeam', title_es: 'Fases del proyecto', title_en: 'Project phases',
    content_es: 'Serge Monast describió cuatro fases: 1) desacreditación de religiones mediante fraudes arqueológicos; 2) proyección holográfica de seres divinos o extraterrestres; 3) comunicación telepática inducida tecnológicamente para que líderes mundiales "reciban" mensajes divinos; 4) simulación completa de invasión extraterrestre con naves holográficas y seres artificiales.',
    content_en: 'Serge Monast described four phases: 1) discrediting religions through archaeological frauds; 2) holographic projection of divine or extraterrestrial beings; 3) technologically induced telepathic communication for world leaders to "receive" divine messages; 4) full simulation of alien invasion with holographic ships and artificial beings.',
    order: 0 },
  { id: 'sub-blue-2', entryId: 'entry-bluebeam', title_es: 'Factibilidad tecnológica', title_en: 'Technological feasibility',
    content_es: 'La teoría ha ganado plausibilidad con avances en realidad aumentada, drones con pantallas LED, proyección de imágenes en nubes y generación de video por IA. Sin embargo, los escépticos señalan que simular una invasión extraterrestre global creíble sería logísticamente imposible de mantener sin filtraciones masivas.',
    content_en: 'The theory has gained plausibility with advances in augmented reality, LED-screen drones, cloud image projection, and AI video generation. However, skeptics note that simulating a credible global alien invasion would be logistically impossible to maintain without massive leaks.',
    order: 1 },

  // === DOMAIN 9: CONSPIRACY - Historical ===
  { id: 'sub-jfk-1', entryId: 'entry-jfk', title_es: 'La Comisión Warren', title_en: 'The Warren Commission',
    content_es: 'La Comisión Warren, presidida por el presidente del Tribunal Supremo Earl Warren, investigó el asesinato de JFK durante diez meses. Concluyó que Lee Harvey Oswald actuó solo y que Jack Ruby actuó solo al matar a Oswald. El informe ha sido criticado por omitir testimonios contradictorios y por la "teoría de la bala mágica" que muchos consideran físicamente imposible.',
    content_en: 'The Warren Commission, chaired by Chief Justice Earl Warren, investigated the JFK assassination for ten months. It concluded that Lee Harvey Oswald acted alone and Jack Ruby acted alone in killing Oswald. The report has been criticized for omitting contradictory testimony and the "magic bullet theory" many consider physically impossible.',
    order: 0 },
  { id: 'sub-jfk-2', entryId: 'entry-jfk', title_es: 'Nuevas investigaciones', title_en: 'New investigations',
    content_es: 'La Ley de Registros de JFK de 1992 ordenó la divulgación de todos los documentos relacionados en 25 años. Aunque millones de páginas se han publicado, algunos documentos siguen clasificados por razones de seguridad nacional. La divulgación gradual mantiene el interés público y la especulación sobre lo que podrían contener los archivos aún ocultos.',
    content_en: 'The 1992 JFK Records Act ordered disclosure of all related documents within 25 years. Although millions of pages have been released, some documents remain classified for national security reasons. Gradual disclosure maintains public interest and speculation about what the still-hidden files might contain.',
    order: 1 },
  { id: 'sub-moon-1', entryId: 'entry-moon-hoax', title_es: 'Anomalías fotográficas', title_en: 'Photographic anomalies',
    content_es: 'Las presuntas anomalías incluyen: sombras no paralelas (explicables por perspectiva en terreno irregular), ausencia de estrellas (las cámaras estaban configuradas para objetos brillantes en el suelo lunar), bandera ondeando (mástil horizontal y vibraciones al plantarla), y huellas demasiado marcadas (el regolito lunar, sin humedad, mantiene las huellas perfectamente).',
    content_en: 'Alleged anomalies include: non-parallel shadows (explainable by perspective on uneven terrain), absence of stars (cameras set for bright lunar ground objects), waving flag (horizontal pole and vibrations from planting), and overly sharp footprints (lunar regolith, without moisture, preserves footprints perfectly).',
    order: 0 },
  { id: 'sub-moon-2', entryId: 'entry-moon-hoax', title_es: 'Refutaciones científicas', title_en: 'Scientific refutations',
    content_es: 'La evidencia que refuta la teoría incluye: 382 kg de rocas lunares analizadas por científicos de todo el mundo sin encontrar evidencia de falsificación; reflectores láser colocados en la Luna que aún se usan para mediciones precisas; fotografías de misiones orbitales mostrando los sitios de alunizaje con los módulos y huellas visibles.',
    content_en: 'Evidence refuting the theory includes: 382 kg of lunar rocks analyzed by scientists worldwide with no evidence of forgery; laser reflectors placed on the Moon still used for precise measurements; photographs from orbital missions showing landing sites with modules and visible footprints.',
    order: 1 },
  { id: 'sub-titan-1', entryId: 'entry-titanic-switch', title_es: 'Diferencias técnicas', title_en: 'Technical differences',
    content_es: 'Aunque gemelos, el Titanic y el Olympic tenían diferencias: el Titanic tenía cubiertas de paseo cerradas en la cubierta A (el Olympic las tenía abiertas inicialmente), y el interior del Titanic fue más lujoso. Los defensores del cambio argumentan que fotos del Olympic muestran estas cubiertas cerradas, sugiriendo una modificación posterior para parecerse al Titanic.',
    content_en: 'Although twins, Titanic and Olympic had differences: Titanic had enclosed promenade decks on A-deck (Olympic initially had open ones), and Titanic\'s interior was more luxurious. Switch proponents argue that photos of Olympic show these enclosed decks, suggesting later modification to resemble Titanic.',
    order: 0 },
  { id: 'sub-titan-2', entryId: 'entry-titanic-switch', title_es: 'Contraargumentos', title_en: 'Counterarguments',
    content_es: 'Los historiadores señalan que sería imposible cambiar tantos detalles (mobiliario, vajilla, nombre grabado en miles de objetos) sin que nadie lo notara. El Olympic tuvo una exitosa carrera de 24 años como transatlántico y buque de guerra. Si hubiera sido el barco "falso", los marineros y oficiales que sirvieron en ambos barcos lo habrían detectado inmediatamente.',
    content_en: 'Historians note it would be impossible to change so many details (furniture, china, engraved name on thousands of objects) without anyone noticing. Olympic had a successful 24-year career as ocean liner and warship. Had it been the "fake" ship, sailors and officers who served on both vessels would have immediately detected it.',
    order: 1 },
  { id: 'sub-pearl-1', entryId: 'entry-pearl-harbor', title_es: 'Inteligencia disponible', title_en: 'Available intelligence',
    content_es: 'EE.UU. había roto el código diplomático japonés (MAGIC) y conocía las intenciones expansivas japonesas. En octubre de 1941, un oficial australiano advirtió de un posible ataque a Pearl Harbor. El 27 de noviembre, Washington envió un mensaje de "guerra inminente" a los comandos del Pacífico, pero no especificaba Pearl Harbor.',
    content_en: 'The US had broken the Japanese diplomatic code (MAGIC) and knew of Japanese expansionist intentions. In October 1941, an Australian officer warned of a possible Pearl Harbor attack. On November 27, Washington sent a "war imminent" message to Pacific commands but did not specify Pearl Harbor.',
    order: 0 },
  { id: 'sub-pearl-2', entryId: 'entry-pearl-harbor', title_es: 'Consecuencias políticas', title_en: 'Political consequences',
    content_es: 'El ataque de Pearl Harbor tuvo el efecto inmediato de unir a la opinión pública estadounidense en favor de la guerra. La declaración de guerra a Japón fue aprobada con un solo voto en contra. Alemania e Italia declararon la guerra a EE.UU. días después, llevando a EE.UU. a la guerra en Europa y Asia. La teoría sigue siendo debatida por historiadores.',
    content_en: 'The Pearl Harbor attack had the immediate effect of uniting American public opinion in favor of war. The declaration of war against Japan passed with only one dissenting vote. Germany and Italy declared war on the US days later, bringing the US into the European and Asian war. The theory continues to be debated by historians.',
    order: 1 },

  // === DOMAIN 9: CONSPIRACY - Tech ===
  { id: 'sub-haarp-1', entryId: 'entry-haarp', title_es: 'Funcionamiento real', title_en: 'Actual operation',
    content_es: 'HAARP transmite ondas de radio de alta frecuencia (3-10 MHz) a la ionosfera y mide las respuestas. El objetivo es estudiar cómo la ionosfera afecta las comunicaciones y el radar. La instalación consta de 180 antenas dipolo en una superficie de 13 hectáreas. Su potencia máxima de salida es de 3.6 MW, comparable a una estación de radio comercial.',
    content_en: 'HAARP transmits high-frequency radio waves (3-10 MHz) to the ionosphere and measures responses. The goal is studying how the ionosphere affects communications and radar. The facility consists of 180 dipole antennas across 13 hectares. Its maximum output power is 3.6 MW, comparable to a commercial radio station.',
    order: 0 },
  { id: 'sub-haarp-2', entryId: 'entry-haarp', title_es: 'Teorías asociadas', title_en: 'Associated theories',
    content_es: 'HAARP ha sido vinculado con numerosos desastres naturales, incluyendo el terremoto de Haití de 2010, el tsunami de Japón de 2011 y el huracán Katrina. Además, se afirma que puede crear "escudos de plasma" para defensa antimisiles y alterar el clima global. Ninguna de estas afirmaciones tiene respaldo científico.',
    content_en: 'HAARP has been linked to numerous natural disasters, including the 2010 Haiti earthquake, 2011 Japan tsunami, and Hurricane Katrina. Additionally, it is claimed to create "plasma shields" for missile defense and alter global weather. None of these claims have scientific support.',
    order: 1 },
  { id: 'sub-5g-1', entryId: 'entry-5g-conspiracy', title_es: 'Efectos biológicos', title_en: 'Biological effects',
    content_es: 'Las ondas milimétricas del 5G (24-100 GHz) son absorbidas principalmente en la piel y los ojos. No hay evidencia científica consistente de que causen cáncer u otros efectos graves en los niveles de exposición permitidos. Sin embargo, la falta de estudios a largo plazo alimenta la cautela y las sospechas.',
    content_en: '5G millimeter waves (24-100 GHz) are mainly absorbed in skin and eyes. There is no consistent scientific evidence they cause cancer or other serious effects at permitted exposure levels. However, lack of long-term studies fuels caution and suspicion.',
    order: 0 },
  { id: 'sub-5g-2', entryId: 'entry-5g-conspiracy', title_es: 'Impacto social', title_en: 'Social impact',
    content_es: 'El 5G permite la interconexión masiva de dispositivos (IoT) y la transmisión de datos en tiempo real. Esto tiene implicaciones para la vigilancia: las ciudades inteligentes pueden monitorizar el movimiento de personas, el reconocimiento facial puede operar en tiempo real, y la recopilación masiva de datos puede usarse para perfiles de comportamiento.',
    content_en: '5G enables massive device interconnection (IoT) and real-time data transmission. This has implications for surveillance: smart cities can monitor people movement, facial recognition can operate in real-time, and mass data collection can be used for behavioral profiling.',
    order: 1 },
  { id: 'sub-ai-1', entryId: 'entry-ai-conspiracy', title_es: 'AGI y secretismo', title_en: 'AGI and secrecy',
    content_es: 'La inteligencia artificial general (AGI) se refiere a una IA con capacidad cognitiva comparable a la humana. Las empresas tecnológicas admiten estar trabajando hacia AGI, pero afirman que aún no se ha alcanzado. Los teóricos de la conspiración creen que ya existe pero se mantiene en secreto por razones de seguridad y ventaja estratégica.',
    content_en: 'Artificial general intelligence (AGI) refers to AI with cognitive capacity comparable to humans. Tech companies admit to working toward AGI but claim it has not yet been achieved. Conspiracy theorists believe it already exists but is kept secret for security and strategic advantage reasons.',
    order: 0 },
  { id: 'sub-ai-2', entryId: 'entry-ai-conspiracy', title_es: 'Riesgos existenciales', title_en: 'Existential risks',
    content_es: 'Más allá de las teorías conspirativas, existe un debate legítimo sobre los riesgos de la IA. El problema del "alineamiento" se refiere a cómo asegurar que una IA superinteligente actúe según los valores humanos. Investigadores como Nick Bostrom y Eliezer Yudkowsky advierten que una IA desalineada podría ser la mayor amenaza existencial para la humanidad.',
    content_en: 'Beyond conspiracy theories, there is a legitimate debate about AI risks. The "alignment problem" refers to ensuring a superintelligent AI acts according to human values. Researchers like Nick Bostrom and Eliezer Yudkowsky warn that a misaligned AI could be the greatest existential threat to humanity.',
    order: 1 },
  { id: 'sub-snowden-1', entryId: 'entry-cyber-surveillance', title_es: 'Revelaciones de Snowden', title_en: 'Snowden revelations',
    content_es: 'Edward Snowden, excontratista de la NSA, filtró en 2013 documentos que revelaban programas de vigilancia masiva como PRISM (acceso directo a servidores de Google, Apple, Facebook), XKEYSCORE (análisis de tráfico global de Internet) y la interceptación de cables submarinos de fibra óptica por parte de la NSA y el GCHQ británico.',
    content_en: 'Edward Snowden, former NSA contractor, leaked documents in 2013 revealing mass surveillance programs like PRISM (direct access to Google, Apple, Facebook servers), XKEYSCORE (global Internet traffic analysis), and interception of submarine fiber optic cables by the NSA and British GCHQ.',
    order: 0 },
  { id: 'sub-snowden-2', entryId: 'entry-cyber-surveillance', title_es: 'Panóptico digital', title_en: 'Digital panopticon',
    content_es: 'El concepto de "panóptico digital" describe un sistema donde todos pueden ser vigilados en cualquier momento. Con la proliferación de dispositivos IoT, asistentes de voz, cámaras de seguridad y sensores urbanos, la capacidad de vigilancia es mayor que nunca. China ha implementado el sistema más avanzado con su programa de crédito social y reconocimiento facial masivo.',
    content_en: 'The "digital panopticon" concept describes a system where everyone can be watched at any time. With the proliferation of IoT devices, voice assistants, security cameras, and urban sensors, surveillance capacity is greater than ever. China has implemented the most advanced system with its social credit program and massive facial recognition.',
    order: 1 },

  // === DOMAIN 9: CONSPIRACY - Bio ===
  { id: 'sub-covid-1', entryId: 'entry-covid-lab', title_es: 'Investigación en Wuhan', title_en: 'Wuhan research',
    content_es: 'El Instituto de Virología de Wuhan (WIV) es uno de los laboratorios de mayor nivel de bioseguridad (BSL-4) en China. Investigaba coronavirus de murciélago y realizaba experimentos de "ganancia de función" para estudiar la transmisibilidad de estos virus. La proximidad del mercado de mariscos de Wuhan al WIV y la ausencia de un huésped intermediario claro alimentan las sospechas.',
    content_en: 'The Wuhan Institute of Virology (WIV) is one of the highest biosafety level (BSL-4) laboratories in China. It researched bat coronaviruses and conducted "gain of function" experiments studying transmissibility of these viruses. The proximity of Wuhan\'s seafood market to the WIV and absence of a clear intermediate host fuel suspicions.',
    order: 0 },
  { id: 'sub-covid-2', entryId: 'entry-covid-lab', title_es: 'Debate científico', title_en: 'Scientific debate',
    content_es: 'La comunidad científica sigue dividida sobre el origen del SARS-CoV-2. Un estudio de 2022 en Science analizó la genómica viral y concluyó que no hay evidencia de ingeniería genética. Sin embargo, la presencia del sitio de escisión de furina y la falta de un ancestro directo en murciélagos mantienen abierta la hipótesis del laboratorio.',
    content_en: 'The scientific community remains divided on SARS-CoV-2 origin. A 2022 study in Science analyzed viral genomics and concluded there is no evidence of genetic engineering. However, the presence of the furin cleavage site and lack of a direct bat ancestor keep the lab hypothesis open.',
    order: 1 },
  { id: 'sub-gmo-1', entryId: 'entry-gmo-conspiracy', title_es: 'El caso Monsanto', title_en: 'The Monsanto case',
    content_es: 'Monsanto, adquirida por Bayer en 2018 por 63,000 millones de dólares, ha sido el centro de controversias sobre OGM. La compañía desarrolló el glifosato (Roundup) y semillas genéticamente modificadas resistentes a este herbicida. Monsanto ha sido demandada por agricultores afectados por la deriva de glifosato y por supuestos efectos cancerígenos del herbicida.',
    content_en: 'Monsanto, acquired by Bayer in 2018 for $63 billion, has been the center of GMO controversies. The company developed glyphosate (Roundup) and GM seeds resistant to this herbicide. Monsanto has been sued by affected farmers for glyphosate drift and alleged carcinogenic effects of the herbicide.',
    order: 0 },
  { id: 'sub-gmo-2', entryId: 'entry-gmo-conspiracy', title_es: 'Seguridad alimentaria', title_en: 'Food safety',
    content_es: 'Las agencias reguladoras internacionales (OMS, FAO, EFSA, FDA) han concluido que los OGM aprobados son seguros para el consumo humano. Sin embargo, las preocupaciones sobre patentes de semillas, dependencia de agricultores, pérdida de biodiversidad y consolidación corporativa en la industria alimentaria son legítimas y merecen debate público.',
    content_en: 'International regulatory agencies (WHO, FAO, EFSA, FDA) have concluded that approved GMOs are safe for human consumption. However, concerns about seed patents, farmer dependence, biodiversity loss, and corporate consolidation in the food industry are legitimate and deserve public debate.',
    order: 1 },
  { id: 'sub-vax-1', entryId: 'entry-vaccine-conspiracy', title_es: 'El fraude de Wakefield', title_en: 'The Wakefield fraud',
    content_es: 'Andrew Wakefield publicó en 1998 un estudio en The Lancet con 12 niños, afirmando una relación entre la vacuna triple vírica (MMR) y el autismo. The Lancet retiró el estudio en 2010 al descubrirse que Wakefield había manipulado los datos, no había revelado conflictos de intereses financieros (recibió 400,000 libras de abogados que demandaban a fabricantes de vacunas), y actuaba sin aprobación ética.',
    content_en: 'Andrew Wakefield published a 1998 study in The Lancet with 12 children, claiming a link between the MMR vaccine and autism. The Lancet retracted the study in 2010 after discovering Wakefield had manipulated data, failed to disclose financial conflicts (he received £400,000 from lawyers suing vaccine manufacturers), and acted without ethical approval.',
    order: 0 },
  { id: 'sub-vax-2', entryId: 'entry-vaccine-conspiracy', title_es: 'Consecuencias globales', title_en: 'Global consequences',
    content_es: 'El movimiento antivacunas ha provocado brotes de enfermedades prevenibles en todo el mundo. En 2019, la OMS declaró la renuencia a vacunarse como una de las diez mayores amenazas para la salud global. La desinformación sobre vacunas se ha extendido por redes sociales, llevando a plataformas como Facebook y YouTube a implementar políticas contra la desinformación sanitaria.',
    content_en: 'The anti-vaccine movement has caused outbreaks of preventable diseases worldwide. In 2019, WHO declared vaccine hesitancy one of the ten greatest threats to global health. Vaccine misinformation has spread through social media, leading platforms like Facebook and YouTube to implement anti-health-misinformation policies.',
    order: 1 },
  { id: 'sub-pop-1', entryId: 'entry-population-control', title_es: 'Georgia Guidestones', title_en: 'Georgia Guidestones',
    content_es: 'El monumento de granito erigido en 1980 en Elberton, Georgia, contenía diez principios escritos en doce idiomas, incluyendo "Mantener a la humanidad por debajo de 500,000,000 en perpetuo equilibrio con la naturaleza". Fue destruido en 2022 por una explosión. Para los teóricos, era el manifiesto de las élites globales para el control poblacional.',
    content_en: 'The granite monument erected in 1980 in Elberton, Georgia, contained ten principles in twelve languages, including "Maintain humanity under 500,000,000 in perpetual balance with nature." It was destroyed in 2022 by an explosion. For theorists, it was the global elite manifesto for population control.',
    order: 0 },
  { id: 'sub-pop-2', entryId: 'entry-population-control', title_es: 'Agenda 2030/2050', title_en: 'Agenda 2030/2050',
    content_es: 'Los Objetivos de Desarrollo Sostenible de la ONU (Agenda 2030) y el concepto de "Gran Reinicio" del Foro Económico Mundial son interpretados por los teóricos como planes para el control poblacional global. Argumentan que las políticas climáticas y de sostenibilidad son excusas para imponer restricciones y reducir la población mediante medidas de "descarbonización".',
    content_en: 'The UN Sustainable Development Goals (Agenda 2030) and the World Economic Forum\'s "Great Reset" concept are interpreted by theorists as plans for global population control. They argue that climate and sustainability policies are excuses to impose restrictions and reduce population through "decarbonization" measures.',
    order: 1 },
]
