import type { SeedCategory } from './seed'

export const newExpandedCategories: SeedCategory[] = [
  // ===== TECHNOLOGY =====
  {
    id: 'cat-computing',
    name_es: 'Computación',
    name_en: 'Computing',
    slug: 'computing',
    description_es: 'Evolución de los ordenadores, lenguajes de programación, sistemas operativos y la revolución digital.',
    description_en: 'Evolution of computers, programming languages, operating systems, and the digital revolution.',
    icon: '💻',
    parentId: 'cat-technology',
  },
  {
    id: 'cat-internet',
    name_es: 'Internet y Redes',
    name_en: 'Internet & Networks',
    slug: 'internet-networks',
    description_es: 'El origen, desarrollo y funcionamiento de internet, la world wide web y las redes de comunicación global.',
    description_en: 'The origin, development, and functioning of the internet, worldwide web, and global communication networks.',
    icon: '🌐',
    parentId: 'cat-technology',
  },
  {
    id: 'cat-artificial-intelligence',
    name_es: 'Inteligencia Artificial',
    name_en: 'Artificial Intelligence',
    slug: 'artificial-intelligence',
    description_es: 'Sistemas que simulan inteligencia humana: machine learning, redes neuronales, robótica inteligente y ética de la IA.',
    description_en: 'Systems that simulate human intelligence: machine learning, neural networks, intelligent robotics, and AI ethics.',
    icon: '🤖',
    parentId: 'cat-technology',
  },
  {
    id: 'cat-engineering',
    name_es: 'Ingeniería',
    name_en: 'Engineering',
    slug: 'engineering',
    description_es: 'Aplicación de principios científicos al diseño y construcción de estructuras, máquinas y sistemas.',
    description_en: 'Application of scientific principles to the design and construction of structures, machines, and systems.',
    icon: '⚙️',
    parentId: 'cat-technology',
  },
  {
    id: 'cat-transportation',
    name_es: 'Transporte',
    name_en: 'Transportation',
    slug: 'transportation',
    description_es: 'Vehículos y sistemas de desplazamiento: automóviles, trenes, barcos, aviones y el futuro del transporte.',
    description_en: 'Vehicles and mobility systems: automobiles, trains, ships, aircraft, and the future of transportation.',
    icon: '🚂',
    parentId: 'cat-technology',
  },
  {
    id: 'cat-energy',
    name_es: 'Energía',
    name_en: 'Energy',
    slug: 'energy',
    description_es: 'Fuentes de energía: combustibles fósiles, nuclear, solar, eólica y renovables. Generación y almacenamiento.',
    description_en: 'Energy sources: fossil fuels, nuclear, solar, wind, and renewables. Generation and storage.',
    icon: '⚡',
    parentId: 'cat-technology',
  },
  {
    id: 'cat-telecom',
    name_es: 'Telecomunicaciones',
    name_en: 'Telecommunications',
    slug: 'telecommunications',
    description_es: 'Transmisión de información a distancia: telégrafo, teléfono, radio, televisión y comunicaciones modernas.',
    description_en: 'Long-distance information transmission: telegraph, telephone, radio, television, and modern communications.',
    icon: '📡',
    parentId: 'cat-technology',
  },
  {
    id: 'cat-space-tech',
    name_es: 'Exploración Espacial',
    name_en: 'Space Exploration',
    slug: 'space-exploration',
    description_es: 'Tecnología para la exploración del espacio: cohetes, satélites, estaciones espaciales y misiones interplanetarias.',
    description_en: 'Technology for space exploration: rockets, satellites, space stations, and interplanetary missions.',
    icon: '🚀',
    parentId: 'cat-technology',
  },
  {
    id: 'cat-robotics',
    name_es: 'Robótica',
    name_en: 'Robotics',
    slug: 'robotics',
    description_es: 'Diseño, construcción y programación de robots para aplicaciones industriales, médicas y domésticas.',
    description_en: 'Design, construction, and programming of robots for industrial, medical, and domestic applications.',
    icon: '🦾',
    parentId: 'cat-technology',
  },
  {
    id: 'cat-biotech',
    name_es: 'Biotecnología',
    name_en: 'Biotechnology',
    slug: 'biotechnology',
    description_es: 'Uso de organismos vivos y sistemas biológicos para crear productos y tecnologías aplicadas.',
    description_en: 'Use of living organisms and biological systems to create applied products and technologies.',
    icon: '🧫',
    parentId: 'cat-technology',
  },
  {
    id: 'cat-nanotech',
    name_es: 'Nanotecnología',
    name_en: 'Nanotechnology',
    slug: 'nanotechnology',
    description_es: 'Manipulación de la materia a escala molecular y atómica para crear materiales y dispositivos novedosos.',
    description_en: 'Manipulation of matter at molecular and atomic scales to create novel materials and devices.',
    icon: '🔬',
    parentId: 'cat-technology',
  },

  // ===== ARTS & CULTURE =====
  {
    id: 'cat-music',
    name_es: 'Música',
    name_en: 'Music',
    slug: 'music',
    description_es: 'Historia y evolución de la música: desde los primeros instrumentos hasta la producción digital moderna.',
    description_en: 'History and evolution of music: from the earliest instruments to modern digital production.',
    icon: '🎵',
    parentId: 'cat-arts',
  },
  {
    id: 'cat-visual-arts',
    name_es: 'Artes Visuales',
    name_en: 'Visual Arts',
    slug: 'visual-arts',
    description_es: 'Pintura, escultura, grabado y otras formas de expresión visual a lo largo de la historia.',
    description_en: 'Painting, sculpture, printmaking, and other forms of visual expression throughout history.',
    icon: '🎨',
    parentId: 'cat-arts',
  },
  {
    id: 'cat-architecture',
    name_es: 'Arquitectura',
    name_en: 'Architecture',
    slug: 'architecture',
    description_es: 'Diseño y construcción de edificios y espacios: desde las pirámides hasta los rascacielos contemporáneos.',
    description_en: 'Design and construction of buildings and spaces: from the pyramids to contemporary skyscrapers.',
    icon: '🏛️',
    parentId: 'cat-arts',
  },
  {
    id: 'cat-performing-arts',
    name_es: 'Artes Escénicas',
    name_en: 'Performing Arts',
    slug: 'performing-arts',
    description_es: 'Teatro, danza, ópera y otras expresiones artísticas que se representan ante un público en vivo.',
    description_en: 'Theatre, dance, opera, and other artistic expressions performed before a live audience.',
    icon: '🎭',
    parentId: 'cat-arts',
  },
  {
    id: 'cat-cinema',
    name_es: 'Cine',
    name_en: 'Cinema',
    slug: 'cinema',
    description_es: 'Historia del séptimo arte: desde el cine mudo hasta el blockbuster moderno y el cine de autor.',
    description_en: 'History of the seventh art: from silent film to the modern blockbuster and auteur cinema.',
    icon: '🎬',
    parentId: 'cat-arts',
  },
  {
    id: 'cat-photography',
    name_es: 'Fotografía',
    name_en: 'Photography',
    slug: 'photography',
    description_es: 'Arte y técnica de capturar imágenes: desde el daguerrotipo hasta la fotografía digital contemporánea.',
    description_en: 'Art and technique of capturing images: from the daguerreotype to contemporary digital photography.',
    icon: '📷',
    parentId: 'cat-arts',
  },
  {
    id: 'cat-cultural-movements',
    name_es: 'Movimientos Culturales',
    name_en: 'Cultural Movements',
    slug: 'cultural-movements',
    description_es: 'Corrientes que transformaron la cultura: Renacimiento, Romanticismo, Modernismo, Vanguardia y contracultura.',
    description_en: 'Movements that transformed culture: Renaissance, Romanticism, Modernism, Avant-garde, and counterculture.',
    icon: '🎯',
    parentId: 'cat-arts',
  },
  {
    id: 'cat-design',
    name_es: 'Diseño',
    name_en: 'Design',
    slug: 'design',
    description_es: 'Diseño gráfico, industrial, de moda y de interiores: creatividad aplicada a la forma y función.',
    description_en: 'Graphic, industrial, fashion, and interior design: creativity applied to form and function.',
    icon: '✏️',
    parentId: 'cat-arts',
  },
  {
    id: 'cat-gastronomy',
    name_es: 'Gastronomía',
    name_en: 'Gastronomy',
    slug: 'gastronomy',
    description_es: 'Historia y cultura de la alimentación: cocinas del mundo, técnicas culinarias y evolución de la gastronomía.',
    description_en: 'History and culture of food: world cuisines, culinary techniques, and evolution of gastronomy.',
    icon: '🍽️',
    parentId: 'cat-arts',
  },

  // ===== HISTORY - Expanded =====
  {
    id: 'cat-modern-history',
    name_es: 'Historia Moderna',
    name_en: 'Modern History',
    slug: 'modern-history',
    description_es: 'Desde el Renacimiento hasta la Revolución Francesa: exploración, reforma, absolutismo e ilustración.',
    description_en: 'From the Renaissance to the French Revolution: exploration, reform, absolutism, and enlightenment.',
    icon: '⛵',
    parentId: 'cat-history',
  },
  {
    id: 'cat-contemporary-history',
    name_es: 'Historia Contemporánea',
    name_en: 'Contemporary History',
    slug: 'contemporary-history',
    description_es: 'Desde la Revolución Industrial hasta el presente: guerras mundiales, globalización y era digital.',
    description_en: 'From the Industrial Revolution to the present: world wars, globalization, and the digital age.',
    icon: '📻',
    parentId: 'cat-history',
  },
  {
    id: 'cat-asian-history',
    name_es: 'Historia de Asia',
    name_en: 'Asian History',
    slug: 'asian-history',
    description_es: 'Grandes civilizaciones de Asia: China imperial, Japón feudal, India mogol y el sudeste asiático.',
    description_en: 'Great civilizations of Asia: Imperial China, feudal Japan, Mughal India, and Southeast Asia.',
    icon: '🏯',
    parentId: 'cat-history',
  },
  {
    id: 'cat-african-history',
    name_es: 'Historia de África',
    name_en: 'African History',
    slug: 'african-history',
    description_es: 'Reinos y culturas africanas: Egipto faraónico, reinos sahelianos, África subsahariana y descolonización.',
    description_en: 'African kingdoms and cultures: Pharaonic Egypt, Sahelian kingdoms, sub-Saharan Africa, and decolonization.',
    icon: '🌍',
    parentId: 'cat-history',
  },
  {
    id: 'cat-middle-east-history',
    name_es: 'Historia de Oriente Medio',
    name_en: 'Middle Eastern History',
    slug: 'middle-east-history',
    description_es: 'Cuna de la civilización: Mesopotamia, Persia, el mundo otomano y el Medio Oriente contemporáneo.',
    description_en: 'Cradle of civilization: Mesopotamia, Persia, the Ottoman world, and the contemporary Middle East.',
    icon: '🕌',
    parentId: 'cat-history',
  },

  // ===== RELIGION - Expanded =====
  {
    id: 'cat-christianity',
    name_es: 'Cristianismo',
    name_en: 'Christianity',
    slug: 'christianity',
    description_es: 'Historia, doctrina y expansión del cristianismo: desde Jesús hasta las denominaciones contemporáneas.',
    description_en: 'History, doctrine, and expansion of Christianity: from Jesus to contemporary denominations.',
    icon: '✝️',
    parentId: 'cat-religion',
  },
  {
    id: 'cat-islam',
    name_es: 'Islam',
    name_en: 'Islam',
    slug: 'islam',
    description_es: 'Historia y pilares del islam: el profeta Mahoma, el Corán, la expansión islámica y sus ramas principales.',
    description_en: 'History and pillars of Islam: the prophet Muhammad, the Quran, Islamic expansion, and its main branches.',
    icon: '☪️',
    parentId: 'cat-religion',
  },
  {
    id: 'cat-judaism',
    name_es: 'Judaísmo',
    name_en: 'Judaism',
    slug: 'judaism',
    description_es: 'Historia, textos y tradiciones del judaísmo: desde Abraham hasta el judaísmo moderno y el sionismo.',
    description_en: 'History, texts, and traditions of Judaism: from Abraham to modern Judaism and Zionism.',
    icon: '✡️',
    parentId: 'cat-religion',
  },
  {
    id: 'cat-buddhism',
    name_es: 'Budismo',
    name_en: 'Buddhism',
    slug: 'buddhism',
    description_es: 'Enseñanzas de Buda, el dharma, el sangha y las diferentes tradiciones budistas a través de Asia.',
    description_en: 'Teachings of the Buddha, dharma, sangha, and the different Buddhist traditions across Asia.',
    icon: '☸️',
    parentId: 'cat-religion',
  },
  {
    id: 'cat-hinduism',
    name_es: 'Hinduismo',
    name_en: 'Hinduism',
    slug: 'hinduism',
    description_es: 'La tradición religiosa más antigua de la India: vedas, upanishads, dioses, castas y filosofía hindú.',
    description_en: "India's oldest religious tradition: Vedas, Upanishads, gods, castes, and Hindu philosophy.",
    icon: '🕉️',
    parentId: 'cat-religion',
  },
  {
    id: 'cat-taoism',
    name_es: 'Taoísmo',
    name_en: 'Taoism',
    slug: 'taoism',
    description_es: 'Filosofía y religión china basada en el Tao Te King: wu wei, yin-yang y la búsqueda de la armonía.',
    description_en: 'Chinese philosophy and religion based on the Tao Te Ching: wu wei, yin-yang, and the pursuit of harmony.',
    icon: '☯️',
    parentId: 'cat-religion',
  },
  {
    id: 'cat-new-religions',
    name_es: 'Nuevos Movimientos Religiosos',
    name_en: 'New Religious Movements',
    slug: 'new-religious-movements',
    description_es: 'Movimientos espirituales surgidos en los siglos XIX-XXI: mormonismo, cientología, fe baháʼí y otros.',
    description_en: 'Spiritual movements that emerged in the 19th-21st centuries: Mormonism, Scientology, Baháʼí Faith, and others.',
    icon: '🔮',
    parentId: 'cat-religion',
  },

  // ===== SCIENCE - Expanded =====
  {
    id: 'cat-geology',
    name_es: 'Geología',
    name_en: 'Geology',
    slug: 'geology',
    description_es: 'Estudio de la Tierra: minerales, rocas, tectónica de placas, volcanes, terremotos y la historia geológica.',
    description_en: 'Study of the Earth: minerals, rocks, plate tectonics, volcanoes, earthquakes, and geological history.',
    icon: '🏔️',
    parentId: 'cat-science',
  },
  {
    id: 'cat-oceanography',
    name_es: 'Oceanografía',
    name_en: 'Oceanography',
    slug: 'oceanography',
    description_es: 'Estudio de los océanos: corrientes marinas, ecosistemas acuáticos, geología submarina y clima.',
    description_en: 'Study of the oceans: marine currents, aquatic ecosystems, submarine geology, and climate.',
    icon: '🌊',
    parentId: 'cat-science',
  },
  {
    id: 'cat-neuroscience',
    name_es: 'Neurociencia',
    name_en: 'Neuroscience',
    slug: 'neuroscience',
    description_es: 'Estudio del sistema nervioso: estructura y función del cerebro, plasticidad neuronal y trastornos neurológicos.',
    description_en: 'Study of the nervous system: brain structure and function, neuronal plasticity, and neurological disorders.',
    icon: '🧠',
    parentId: 'cat-science',
  },
  {
    id: 'cat-environment',
    name_es: 'Medio Ambiente',
    name_en: 'Environment',
    slug: 'environment',
    description_es: 'Estudio de los ecosistemas, el cambio climático, la conservación y la relación entre humanos y naturaleza.',
    description_en: 'Study of ecosystems, climate change, conservation, and the relationship between humans and nature.',
    icon: '🌿',
    parentId: 'cat-science',
  },
  {
    id: 'cat-meteorology',
    name_es: 'Meteorología',
    name_en: 'Meteorology',
    slug: 'meteorology',
    description_es: 'Estudio de la atmósfera, el clima y el tiempo atmosférico: fenómenos meteorológicos y predicción climática.',
    description_en: 'Study of the atmosphere, weather, and climate: meteorological phenomena and climate prediction.',
    icon: '🌤️',
    parentId: 'cat-science',
  },
]
